function defs = defs()
%BCT.REGISTRY.KERNELS.DEFS  Authoritative kernel definitions registry
%
%   defs = bct.registry.kernels.defs()
%
% Purpose
%   Single source of truth for all kernel specifications in BCT.
%   This is the canonical registry - all other kernel functions must
%   delegate to this.
%
% Output
%   defs - struct array (1×K) with required fields:
%          Id            (string): unique canonical identifier
%          Kind          (string): "smoothing"|"wavelet"|"window"|"impulse"|"distance"
%          AxisKinds     (string array): allowed axes ["lambda"|"time"|"freq"|"distance"|"generic"]
%          ParamNames    (string array): parameter names used in Evaluate(x,p)
%          DefaultParams (function_handle): @(axis)->struct
%          ParamRanges   (function_handle): @(axis)->struct  
%          Evaluate      (function_handle): @(x,p)->y (canonical evaluator)
%
%          Optional fields:
%          Name          (string): display name
%          Tags          (string array): classification tags
%          EquationLatex (string): LaTeX equation
%          Notes         (string): description
%          IsComplex     (logical): returns complex values
%
% Contract
%   - Evaluate(x,p) is the ONLY required execution signature
%   - Alternative forms (@(p)@(x)...) are derived in runtime if needed
%   - DefaultParams(axis) must return struct with all ParamNames fields
%   - ParamRanges(axis) must return struct with all ParamNames fields
%   - Registry must be deterministic (no randomness, no external state)
%
% See also: bct.registry.kernels.schema, bct.registry.kernels.validate

    % Initialize empty struct array with proper field order
    defs = initializeEmpty();
    
    %% =========================================================
    % SMOOTHING / LOW-PASS KERNELS
    %% =========================================================
    
    defs(end+1) = struct( ...
        'Id', "Heat", ...
        'Kind', "smoothing", ...
        'AxisKinds', ["lambda"], ...
        'ParamNames', ["tau"], ...
        'DefaultParams', @(axis) struct('tau', 1/max(abs(axis))), ...
        'ParamRanges', @(axis) struct('tau', [0.1/max(abs(axis)), 10/max(abs(axis))]), ...
        'Evaluate', @(x,p) exp(-p.tau .* x ./ max(x)), ...
        'Name', "Heat Kernel", ...
        'Tags', ["smooth", "lowpass", "monotonic"], ...
        'EquationLatex', "$$g(\lambda)=e^{-\tau \lambda/\lambda_{\max}}$$", ...
        'Notes', "Exponential decay: exp(-τλ/λmax). Matches GSPBox gsp_design_heat", ...
        'IsComplex', false ...
    );
    
    defs(end+1) = struct( ...
        'Id', "Gaussian", ...
        'Kind', "smoothing", ...
        'AxisKinds', ["lambda", "time", "frequency", "distance", "generic"], ...
        'ParamNames', ["mu", "sigma"], ...
        'DefaultParams', @(axis) struct('mu', mean(axis), 'sigma', 0.1*range(axis)), ...
        'ParamRanges', @(axis) struct('mu', [min(axis), max(axis)], 'sigma', [0.02*range(axis), 0.5*range(axis)]), ...
        'Evaluate', @(x,p) exp(-(x - p.mu).^2 ./ (2*p.sigma^2)), ...
        'Name', "Gaussian", ...
        'Tags', ["smooth", "bandpass", "symmetric"], ...
        'EquationLatex', "$$g(x)=\exp\!\left(-\frac{(x-\mu)^2}{2\sigma^2}\right)$$", ...
        'Notes', "Gaussian bell curve: exp(-(x-μ)²/(2σ²))", ...
        'IsComplex', false ...
    );
    
    defs(end+1) = struct( ...
        'Id', "Laplacian", ...
        'Kind', "smoothing", ...
        'AxisKinds', ["lambda", "time", "frequency", "distance", "generic"], ...
        'ParamNames', ["mu", "b"], ...
        'DefaultParams', @(axis) struct('mu', mean(axis), 'b', 0.1*range(axis)), ...
        'ParamRanges', @(axis) struct('mu', [min(axis), max(axis)], 'b', [0.02*range(axis), 0.5*range(axis)]), ...
        'Evaluate', @(x,p) exp(-abs(x - p.mu) ./ p.b), ...
        'Name', "Laplacian (Double Exponential)", ...
        'Tags', ["sharp", "bandpass"], ...
        'EquationLatex', "$$g(x)=\exp\!\left(-\frac{|x-\mu|}{b}\right)$$", ...
        'Notes', "Double exponential: exp(-|x-μ|/b)", ...
        'IsComplex', false ...
    );
    
    defs(end+1) = struct( ...
        'Id', "Cauchy", ...
        'Kind', "smoothing", ...
        'AxisKinds', ["lambda", "frequency", "generic"], ...
        'ParamNames', ["mu", "gamma"], ...
        'DefaultParams', @(axis) struct('mu', mean(axis), 'gamma', 0.1*range(axis)), ...
        'ParamRanges', @(axis) struct('mu', [min(axis), max(axis)], 'gamma', [0.02*range(axis), 0.5*range(axis)]), ...
        'Evaluate', @(x,p) 1 ./ (1 + ((x - p.mu) ./ p.gamma).^2), ...
        'Name', "Cauchy / Lorentzian", ...
        'Tags', ["heavy-tails", "bandpass"], ...
        'EquationLatex', "$$g(x)=\frac{1}{1+\left(\frac{x-\mu}{\gamma}\right)^2}$$", ...
        'Notes', "Lorentzian: 1/(1+((x-μ)/γ)²)", ...
        'IsComplex', false ...
    );
    
    %% =========================================================
    % WAVELET / OSCILLATORY KERNELS
    %% =========================================================
    
    defs(end+1) = struct( ...
        'Id', "Ricker", ...
        'Kind', "wavelet", ...
        'AxisKinds', ["time", "distance", "generic"], ...
        'ParamNames', ["sigma"], ...
        'DefaultParams', @(axis) struct('sigma', 0.1*range(axis)), ...
        'ParamRanges', @(axis) struct('sigma', [0.02*range(axis), 0.5*range(axis)]), ...
        'Evaluate', @(x,p) (1 - (x.^2 ./ p.sigma^2)) .* exp(-x.^2 ./ (2*p.sigma^2)), ...
        'Name', "Ricker Wavelet (Mexican Hat)", ...
        'Tags', ["wavelet", "bandpass", "oscillatory"], ...
        'EquationLatex', "$$g(x)=\left(1-\frac{x^2}{\sigma^2}\right)\exp\!\left(-\frac{x^2}{2\sigma^2}\right)$$", ...
        'Notes', "Classical Mexican hat: (1-x²/σ²)exp(-x²/(2σ²))", ...
        'IsComplex', false ...
    );
    
    defs(end+1) = struct( ...
        'Id', "SpectralMexicanHat", ...
        'Kind', "wavelet", ...
        'AxisKinds', ["lambda"], ...
        'ParamNames', ["tau"], ...
        'DefaultParams', @(axis) struct('tau', 1/max(abs(axis))), ...
        'ParamRanges', @(axis) struct('tau', [0.1/max(abs(axis)), 10/max(abs(axis))]), ...
        'Evaluate', @(x,p) (p.tau .* x) .* exp(-p.tau .* x), ...
        'Name', "Spectral Mexican Hat", ...
        'Tags', ["bandpass", "spectral"], ...
        'EquationLatex', "$$g(\lambda)=\tau\lambda\,e^{-\tau \lambda}$$", ...
        'Notes', "Graph spectral: τλ·exp(-τλ). Matches GSPBox gsp_design_mexican_hat", ...
        'IsComplex', false ...
    );
    
    defs(end+1) = struct( ...
        'Id', "Morlet", ...
        'Kind', "wavelet", ...
        'AxisKinds', ["time", "distance"], ...
        'ParamNames', ["mu", "sigma", "omega"], ...
        'DefaultParams', @(axis) struct('mu', mean(axis), 'sigma', 0.1*range(axis), 'omega', 5), ...
        'ParamRanges', @(axis) struct('mu', [min(axis), max(axis)], 'sigma', [0.02*range(axis), 0.5*range(axis)], 'omega', [1, 20]), ...
        'Evaluate', @(x,p) exp(-(x - p.mu).^2 ./ (2*p.sigma^2)) .* exp(1i * p.omega * (x - p.mu)), ...
        'Name', "Morlet Wavelet", ...
        'Tags', ["wavelet", "complex", "oscillatory"], ...
        'EquationLatex', "$$g(x)=\exp\!\left(-\frac{(x-\mu)^2}{2\sigma^2}\right)\cdot e^{i\omega(x-\mu)}$$", ...
        'Notes', "Complex wavelet: exp(-(x-μ)²/(2σ²))·exp(iω(x-μ))", ...
        'IsComplex', true ...
    );
    
    defs(end+1) = struct( ...
        'Id', "Gabor", ...
        'Kind', "wavelet", ...
        'AxisKinds', ["time", "distance"], ...
        'ParamNames', ["mu", "sigma", "f0"], ...
        'DefaultParams', @(axis) struct('mu', mean(axis), 'sigma', 0.1*range(axis), 'f0', 5), ...
        'ParamRanges', @(axis) struct('mu', [min(axis), max(axis)], 'sigma', [0.02*range(axis), 0.5*range(axis)], 'f0', [1, 20]), ...
        'Evaluate', @(x,p) exp(-(x - p.mu).^2 ./ (2*p.sigma^2)) .* cos(2*pi*p.f0*(x - p.mu)), ...
        'Name', "Gabor Filter", ...
        'Tags', ["wavelet", "oscillatory", "real"], ...
        'EquationLatex', "$$g(x)=\exp\!\left(-\frac{(x-\mu)^2}{2\sigma^2}\right)\cdot\cos(2\pi f_0(x-\mu))$$", ...
        'Notes', "Gabor: exp(-(x-μ)²/(2σ²))·cos(2πf₀(x-μ))", ...
        'IsComplex', false ...
    );
    
    %% =========================================================
    % BAND-PASS / FILTER SHAPES
    %% =========================================================
    
    defs(end+1) = struct( ...
        'Id', "DoG", ...
        'Kind', "smoothing", ...
        'AxisKinds', ["lambda"], ...
        'ParamNames', ["tau1", "tau2"], ...
        'DefaultParams', @(axis) struct('tau1', 0.5/max(abs(axis)), 'tau2', 2/max(abs(axis))), ...
        'ParamRanges', @(axis) struct('tau1', [0.1/max(abs(axis)), 10/max(abs(axis))], 'tau2', [0.1/max(abs(axis)), 10/max(abs(axis))]), ...
        'Evaluate', @(x,p) exp(-p.tau1 .* x) - exp(-p.tau2 .* x), ...
        'Name', "Difference of Gaussians", ...
        'Tags', ["bandpass", "spectral"], ...
        'EquationLatex', "$$g(\lambda)=e^{-\tau_1 \lambda}-e^{-\tau_2 \lambda}$$", ...
        'Notes', "DoG: exp(-τ₁λ) - exp(-τ₂λ). Band-pass on λ", ...
        'IsComplex', false ...
    );
    
    %% =========================================================
    % WINDOW FUNCTIONS
    %% =========================================================
    
    defs(end+1) = struct( ...
        'Id', "Boxcar", ...
        'Kind', "window", ...
        'AxisKinds', ["generic"], ...
        'ParamNames', ["center", "width"], ...
        'DefaultParams', @(axis) struct('center', mean(axis), 'width', 0.2*range(axis)), ...
        'ParamRanges', @(axis) struct('center', [min(axis), max(axis)], 'width', [0.01*range(axis), range(axis)]), ...
        'Evaluate', @(x,p) double(abs(x - p.center) <= p.width/2), ...
        'Name', "Boxcar / Rectangular", ...
        'Tags', ["sharp", "compact"], ...
        'EquationLatex', "$$g(x)=\begin{cases}1 & |x-c|\le w/2\\0 & \text{else}\end{cases}$$", ...
        'Notes', "Rectangular window centered at specified location", ...
        'IsComplex', false ...
    );
    
    defs(end+1) = struct( ...
        'Id', "Triangle", ...
        'Kind', "window", ...
        'AxisKinds', ["generic"], ...
        'ParamNames', ["center", "width"], ...
        'DefaultParams', @(axis) struct('center', mean(axis), 'width', 0.2*range(axis)), ...
        'ParamRanges', @(axis) struct('center', [min(axis), max(axis)], 'width', [0.01*range(axis), range(axis)]), ...
        'Evaluate', @(x,p) max(0, 1 - abs(x - p.center) ./ (p.width/2)), ...
        'Name', "Triangle", ...
        'Tags', ["smooth", "compact"], ...
        'EquationLatex', "$$g(x)=\max\left(0,1-\frac{|x-c|}{w/2}\right)$$", ...
        'Notes', "Triangular window with linear falloff", ...
        'IsComplex', false ...
    );
    
    defs(end+1) = struct( ...
        'Id', "RaisedCosine", ...
        'Kind', "window", ...
        'AxisKinds', ["generic"], ...
        'ParamNames', ["x1", "x2"], ...
        'DefaultParams', @(axis) struct('x1', min(axis)+0.25*range(axis), 'x2', min(axis)+0.75*range(axis)), ...
        'ParamRanges', @(axis) struct('x1', [min(axis), max(axis)], 'x2', [min(axis), max(axis)]), ...
        'Evaluate', @(x,p) raisedCosineImpl(x, p.x1, p.x2), ...
        'Name', "Raised Cosine", ...
        'Tags', ["smooth", "transition"], ...
        'EquationLatex', "$$g(x)=\frac{1}{2}\left[1+\cos\left(\pi\frac{x-x_1}{x_2-x_1}\right)\right]$$", ...
        'Notes', "Smooth cosine transition between x1 and x2", ...
        'IsComplex', false ...
    );
    
    defs(end+1) = struct( ...
        'Id', "Hann", ...
        'Kind', "window", ...
        'AxisKinds', ["time", "index"], ...
        'ParamNames', ["T"], ...
        'DefaultParams', @(axis) struct('T', range(axis)), ...
        'ParamRanges', @(axis) struct('T', [0.1*range(axis), 2*range(axis)]), ...
        'Evaluate', @(x,p) 0.5 * (1 - cos(2*pi*x/p.T)), ...
        'Name', "Hann Window", ...
        'Tags', ["smooth", "window"], ...
        'EquationLatex', "$$g(x)=\frac{1}{2}\left[1-\cos\left(\frac{2\pi x}{T}\right)\right]$$", ...
        'Notes', "Hann window: 0.5(1-cos(2πt/T))", ...
        'IsComplex', false ...
    );
    
    defs(end+1) = struct( ...
        'Id', "Hamming", ...
        'Kind', "window", ...
        'AxisKinds', ["time", "index"], ...
        'ParamNames', ["T"], ...
        'DefaultParams', @(axis) struct('T', range(axis)), ...
        'ParamRanges', @(axis) struct('T', [0.1*range(axis), 2*range(axis)]), ...
        'Evaluate', @(x,p) 0.54 - 0.46*cos(2*pi*x/p.T), ...
        'Name', "Hamming Window", ...
        'Tags', ["smooth", "window"], ...
        'EquationLatex', "$$g(x)=0.54-0.46\cos\left(\frac{2\pi x}{T}\right)$$", ...
        'Notes', "Hamming window: 0.54 - 0.46cos(2πt/T)", ...
        'IsComplex', false ...
    );
    
    %% =========================================================
    % IMPULSE / INDICATOR FUNCTIONS
    %% =========================================================
    
    defs(end+1) = struct( ...
        'Id', "Delta", ...
        'Kind', "impulse", ...
        'AxisKinds', ["generic"], ...
        'ParamNames', ["center"], ...
        'DefaultParams', @(axis) struct('center', mean(axis)), ...
        'ParamRanges', @(axis) struct('center', [min(axis), max(axis)]), ...
        'Evaluate', @(x,p) deltaImpl(x, p.center), ...
        'Name', "Delta / Kronecker", ...
        'Tags', ["impulse", "sharp"], ...
        'EquationLatex', "$$g(x)=\delta(x-c)$$", ...
        'Notes', "Impulse at specified location", ...
        'IsComplex', false ...
    );
    
    defs(end+1) = struct( ...
        'Id', "Indicator", ...
        'Kind', "impulse", ...
        'AxisKinds', ["generic"], ...
        'ParamNames', ["xmin", "xmax"], ...
        'DefaultParams', @(axis) struct('xmin', min(axis)+0.25*range(axis), 'xmax', min(axis)+0.75*range(axis)), ...
        'ParamRanges', @(axis) struct('xmin', [min(axis), max(axis)], 'xmax', [min(axis), max(axis)]), ...
        'Evaluate', @(x,p) double(x >= p.xmin & x <= p.xmax), ...
        'Name', "Indicator Function", ...
        'Tags', ["sharp", "compact"], ...
        'EquationLatex', "$$g(x)=\mathbb{1}_{[x_{\min},x_{\max}]}(x)$$", ...
        'Notes', "Characteristic function of interval [xmin, xmax]", ...
        'IsComplex', false ...
    );
    
    defs(end+1) = struct( ...
        'Id', "Constant", ...
        'Kind', "impulse", ...
        'AxisKinds', ["generic"], ...
        'ParamNames', ["value"], ...
        'DefaultParams', @(axis) struct('value', 1), ...
        'ParamRanges', @(axis) struct('value', [0, 10]), ...
        'Evaluate', @(x,p) p.value * ones(size(x)), ...
        'Name', "Constant", ...
        'Tags', ["trivial"], ...
        'EquationLatex', "$$g(x)=c$$", ...
        'Notes', "Constant value across all axes", ...
        'IsComplex', false ...
    );
    
    %% =========================================================
    % DISTANCE-BASED KERNELS
    %% =========================================================
    
    defs(end+1) = struct( ...
        'Id', "InverseDistance", ...
        'Kind', "distance", ...
        'AxisKinds', ["distance"], ...
        'ParamNames', ["p"], ...
        'DefaultParams', @(axis) struct('p', 1), ...
        'ParamRanges', @(axis) struct('p', [0.5, 3]), ...
        'Evaluate', @(x,p) 1 ./ (abs(x).^p.p + eps), ...
        'Name', "Inverse Distance", ...
        'Tags', ["decay", "spatial"], ...
        'EquationLatex', "$$g(d)=\frac{1}{d^p + \epsilon}$$", ...
        'Notes', "Inverse power: 1/(d^p + ε)", ...
        'IsComplex', false ...
    );
    
    defs(end+1) = struct( ...
        'Id', "GaussianDistance", ...
        'Kind', "distance", ...
        'AxisKinds', ["distance"], ...
        'ParamNames', ["sigma"], ...
        'DefaultParams', @(axis) struct('sigma', 0.1*range(axis)), ...
        'ParamRanges', @(axis) struct('sigma', [0.01*range(axis), 0.5*range(axis)]), ...
        'Evaluate', @(x,p) exp(-x.^2 ./ (2*p.sigma^2)), ...
        'Name', "Gaussian Distance Kernel", ...
        'Tags', ["smooth", "decay", "spatial"], ...
        'EquationLatex', "$$g(d)=\exp\!\left(-\frac{d^2}{2\sigma^2}\right)$$", ...
        'Notes', "Gaussian decay with distance: exp(-d²/(2σ²))", ...
        'IsComplex', false ...
    );
    
    defs(end+1) = struct( ...
        'Id', "CompactSupport", ...
        'Kind', "distance", ...
        'AxisKinds', ["distance"], ...
        'ParamNames', ["R"], ...
        'DefaultParams', @(axis) struct('R', 0.2*range(axis)), ...
        'ParamRanges', @(axis) struct('R', [0.01*range(axis), range(axis)]), ...
        'Evaluate', @(x,p) max(0, 1 - abs(x) ./ p.R), ...
        'Name', "Compact Support Kernel", ...
        'Tags', ["compact", "spatial"], ...
        'EquationLatex', "$$g(d)=\max\left(0,1-\frac{d}{R}\right)$$", ...
        'Notes', "Linear decay to zero at radius R: max(0, 1-d/R)", ...
        'IsComplex', false ...
    );
    
    % Validation (optional but recommended)
    bct.registry.kernels.validate(defs);
end

%% Helper functions
function empty = initializeEmpty()
    % Initialize with all required and optional fields in proper order
    empty = struct( ...
        'Id', string.empty, ...
        'Kind', string.empty, ...
        'AxisKinds', string.empty(0,0), ...
        'ParamNames', string.empty(0,0), ...
        'DefaultParams', [], ...
        'ParamRanges', [], ...
        'Evaluate', [], ...
        'Name', string.empty, ...
        'Tags', string.empty(0,0), ...
        'EquationLatex', string.empty, ...
        'Notes', string.empty, ...
        'IsComplex', false);
    empty(:) = [];  % Make 0×1 array with proper fields
end

function y = raisedCosineImpl(x, x1, x2)
    % Raised cosine transition from 0 at x1 to 1 at x2
    y = zeros(size(x));
    mask = x >= x1 & x <= x2;
    if x2 > x1
        y(mask) = 0.5 * (1 + cos(pi * (x(mask) - x1) / (x2 - x1)));
    elseif x1 == x2
        y(x >= x1) = 1;
    end
end

function y = deltaImpl(x, center)
    % Discrete delta function (1 at nearest point to center, 0 elsewhere)
    [~, idx] = min(abs(x - center));
    y = zeros(size(x));
    y(idx) = 1;
end
