% Decomposition coefficients for nondecimated wavelet analysis

% Generated by MATLAB(R) 25.2 and Wavelet Toolbox 25.2.
% Generated on: 31-Mar-2026 04:00:43

% Perform the decomposition using MODWT
numberOfLevels = 4;
wt = modwt(x1,"sym4",numberOfLevels);

% Energy by level for the decomposition
energyByLevel = 100*sum((wt.^2),2)/sum(wt.^2,"all");
