function registry = registry()
%BCT.KERNEL.REGISTRY  Declarative kernel registry (façade)
%
%   registry = bct.kernel.registry()
%
% Purpose
%   User-facing wrapper that delegates to bct.registry.kernels.defs().
%   Returns kernel definitions as struct array.
%
% Output
%   registry - struct array of kernel definitions
%
% Note
%   This is a façade function. The authoritative registry is:
%   bct.registry.kernels.defs()
%
%   For new code, prefer:
%     defs = bct.registry.kernels.defs();
%
% See also: bct.registry.kernels.defs, bct.kernel.dictionary, bct.kernel.list

    % Delegate to authoritative registry
    registry = bct.registry.kernels.defs();

    %% =========================================================
    % Heat kernel (diffusion / low-pass)
    %   g(λ) = exp(-τ λ/λ_max)  — matches GSPBox gsp_design_heat
    % =========================================================
    registry.Heat = struct( ...
        'Name', 'Heat', ...
        'NumParams', 1, ...
        'ParamNames', {{'tau'}}, ...
        'EquationLatex', '$$g(\lambda)=e^{-\tau \lambda/\lambda_{\max}}$$', ...
        'DefaultParams', @(axis) struct( ...
            'tau', 1 / range(axis) ), ...
        'ParamRanges', @(axis) struct( ...
            'tau', [0.1/range(axis), 10/range(axis)] ), ...
        'Function', @(p) @(x) exp(-p.tau .* x ./ max(x)) ...
    );

    %% =========================================================
    % Gaussian
    %   g(x) = exp(-(x-mu)^2 / (2 sigma^2))
    % =========================================================
    registry.Gaussian = struct( ...
        'Name', 'Gaussian', ...
        'NumParams', 2, ...
        'ParamNames', {{'sigma','mu'}}, ...
        'EquationLatex', ...
            '$$g(x)=\exp\!\left(-\frac{(x-\mu)^2}{2\sigma^2}\right)$$', ...
        'DefaultParams', @(axis) struct( ...
            'sigma', 0.1 * range(axis), ...
            'mu', mean(axis) ), ...
        'ParamRanges', @(axis) struct( ...
            'sigma', [0.02*range(axis), 0.5*range(axis)], ...
            'mu', [min(axis), max(axis)] ), ...
        'Function', @(p) @(x) ...
            exp(-(x - p.mu).^2 ./ (2*p.sigma^2)), ...
        'Evaluate', @(x,p) ...
            exp(-(x - p.mu).^2 ./ (2*p.sigma^2)) ...
    );

    %% =========================================================
    % Ricker / Classical Mexican Hat
    % =========================================================
    registry.Ricker = struct( ...
        'Name', 'Ricker (Classical Mexican Hat)', ...
        'NumParams', 1, ...
        'ParamNames', {{'sigma'}}, ...
        'EquationLatex', ...
            ['$$g(x)=\left(1-\frac{x^2}{\sigma^2}\right)' ...
             '\exp\!\left(-\frac{x^2}{2\sigma^2}\right)$$'], ...
        'DefaultParams', @(axis) struct( ...
            'sigma', 0.1 * range(axis) ), ...
        'ParamRanges', @(axis) struct( ...
            'sigma', [0.02*range(axis), 0.5*range(axis)] ), ...
        'Function', @(p) @(x) ...
            (1 - (x.^2 ./ p.sigma^2)) .* ...
            exp(-x.^2 ./ (2*p.sigma^2)), ...
        'Evaluate', @(x,p) ...
            (1 - (x.^2 ./ p.sigma^2)) .* ...
            exp(-x.^2 ./ (2*p.sigma^2)) ...
    );

    %% =========================================================
    % Spectral Mexican Hat (Laplacian-native)
    %   g(λ) = τλ exp(-τ λ)  — matches GSPBox gsp_design_mexican_hat
    % =========================================================
    registry.SpectralMexicanHat = struct( ...
        'Name', 'Spectral Mexican Hat (GSP)', ...
        'NumParams', 1, ...
        'ParamNames', {{'tau'}}, ...
        'EquationLatex', ...
            '$$g(\lambda)=\tau\lambda\,e^{-\tau \lambda}$$', ...
        'DefaultParams', @(axis) struct( ...
            'tau', 1 / range(axis) ), ...
        'ParamRanges', @(axis) struct( ...
            'tau', [0.1/range(axis), 10/range(axis)] ), ...
        'Function', @(p) @(x) ...
            (p.tau .* x) .* exp(-p.tau .* x) ...
    );

    %% =========================================================
    % Difference of Gaussians (DoG)
    % =========================================================
    registry.DoG = struct( ...
        'Name', 'Difference of Gaussians', ...
        'NumParams', 2, ...
        'ParamNames', {{'tau1','tau2'}}, ...
        'EquationLatex', ...
            '$$g(\lambda)=e^{-\tau_1 \lambda}-e^{-\tau_2 \lambda}$$', ...
        'DefaultParams', @(axis) struct( ...
            'tau1', 1 / range(axis), ...
            'tau2', 5 / range(axis) ), ...
        'ParamRanges', @(axis) struct( ...
            'tau1', [0.1/range(axis), 5/range(axis)], ...
            'tau2', [1/range(axis), 20/range(axis)] ), ...
        'Function', @(p) @(x) ...
            exp(-p.tau1 .* x) - exp(-p.tau2 .* x) ...
    );

    %% =========================================================
    % Delta / Kronecker impulse
    % =========================================================
    registry.Delta = struct( ...
        'Name', 'Delta', ...
        'NumParams', 1, ...
        'ParamNames', {{'center'}}, ...
        'EquationLatex', '$$\delta(x-x_0)$$', ...
        'DefaultParams', @(axis) struct( ...
            'center', axis(round(end/2)) ), ...
        'ParamRanges', @(axis) struct( ...
            'center', [min(axis), max(axis)] ), ...
        'Evaluate', @(x,p) double(x == p.center) ...
    );

    %% =========================================================
    % Constant signal
    % =========================================================
    registry.Constant = struct( ...
        'Name', 'Constant', ...
        'NumParams', 1, ...
        'ParamNames', {{'value'}}, ...
        'EquationLatex', '$$f(x)=c$$', ...
        'DefaultParams', @(~) struct('value',1), ...
        'Evaluate', @(x,p) p.value * ones(numel(x),1) ...
    );

    %% =========================================================
    % White noise
    % =========================================================
    registry.WhiteNoise = struct( ...
        'Name', 'White Noise', ...
        'NumParams', 0, ...
        'ParamNames', {{}}, ...
        'EquationLatex', '$$\mathcal{N}(0,1)$$', ...
        'Evaluate', @(x,~) randn(numel(x),1) ...
    );

    %% =========================================================
    % Indicator / box function
    % =========================================================
    registry.Indicator = struct( ...
        'Name', 'Indicator', ...
        'NumParams', 2, ...
        'ParamNames', {{'min','max'}}, ...
        'EquationLatex', '$$\mathbf{1}_{[a,b]}(x)$$', ...
        'DefaultParams', @(axis) struct( ...
            'min', axis(round(end/3)), ...
            'max', axis(round(2*end/3)) ), ...
        'Evaluate', @(x,p) double(x >= p.min & x <= p.max) ...
    );

    %% =========================================================
    % Sine wave
    % =========================================================
    registry.Sine = struct( ...
        'Name', 'Sine', ...
        'NumParams', 2, ...
        'ParamNames', {{'freq','phase'}}, ...
        'EquationLatex', '$$\sin(2\pi f x + \phi)$$', ...
        'DefaultParams', @(axis) struct( ...
            'freq', 1 / range(axis), ...
            'phase', 0 ), ...
        'Evaluate', @(x,p) ...
            sin(2*pi*p.freq*x + p.phase) ...
    );

end
