%% Test TailwindSidebar Component
% Quick test script for the sidebar component

clear; clc;
addpath('matlab');

%% Create figure and sidebar
fig = uifigure('Name', 'Sidebar Test', 'Position', [100 100 400 600]);

% Create sidebar component
sidebar = TailwindSidebar(fig, [0 0 400 600]);

%% Add a section with controls
sidebar.send(struct(...
    'cmd', 'addSection', ...
    'section', struct(...
        'id', 'filters', ...
        'title', 'Filter Controls', ...
        'collapsible', true, ...
        'controls', {{
            struct('id', 'cutoff', 'type', 'slider', 'label', 'Cutoff Frequency', ...
                   'min', 0, 'max', 100, 'value', 50, 'step', 1), ...
            struct('id', 'order', 'type', 'slider', 'label', 'Filter Order', ...
                   'min', 1, 'max', 10, 'value', 4, 'step', 1), ...
            struct('id', 'enable', 'type', 'toggle', 'label', 'Enable Filter', ...
                   'value', true), ...
            struct('id', 'type', 'type', 'dropdown', 'label', 'Filter Type', ...
                   'options', {{'lowpass', 'highpass', 'bandpass'}}, ...
                   'value', 'lowpass')
        }}...
    )...
));

%% Add another section
pause(0.5);
sidebar.send(struct(...
    'cmd', 'addSection', ...
    'section', struct(...
        'id', 'display', ...
        'title', 'Display Settings', ...
        'collapsible', true, ...
        'controls', {{
            struct('id', 'opacity', 'type', 'slider', 'label', 'Opacity', ...
                   'min', 0, 'max', 1, 'value', 1, 'step', 0.1), ...
            struct('id', 'colormap', 'type', 'dropdown', 'label', 'Colormap', ...
                   'options', {{'viridis', 'plasma', 'jet', 'hot'}}, ...
                   'value', 'viridis'), ...
            struct('id', 'apply', 'type', 'button', 'label', 'Apply Changes')
        }}...
    )...
));

disp('Sidebar created successfully!');
disp('Interact with the controls in the figure.');
