function out = face(meshInput, varargin)
%FACE Compute all face-based geometric properties
%
% Syntax:
%   faceGeom = bct.manifold.geometry.face(M)
%   faceGeom = bct.manifold.geometry.face(V, F)
%   faceGeom = bct.manifold.geometry.face(___, Name, Value)
%
% Inputs:
%   M    - bct.Manifold object
%   OR
%   V    - [Nv×3] vertex coordinates
%   F    - [Nf×3] face connectivity (1-indexed)
%
% Name-Value Arguments:
%   'precision'          - 'double' (default) or 'single'
%   'circumcenterMethod' - 'native' (default) or 'triangulation'
%
% Outputs:
%   out - Structure matching bct.manifold.geometry.face.schema:
%     .attributes              - Group-level metadata (computation options)
%     .areas.value             - [Nf×1] Area of each triangular face
%     .areas.attributes        - Dataset metadata
%     .circumcenters.value     - [Nf×3] Circumcenter of each face
%     .circumcenters.attributes - Dataset metadata
%     .centroids.value         - [Nf×3] Centroid (barycenter) of each face
%     .centroids.attributes    - Dataset metadata
%     .cotan.value             - [Nf×3] Cotangent weights per face vertex
%     .cotan.attributes        - Dataset metadata
%     .normals.value           - [Nf×3] Face normal vectors (unit)
%     .normals.attributes      - Dataset metadata
%     .tangent1.value          - [Nf×3] First tangent vectors (unit)
%     .tangent1.attributes     - Dataset metadata
%     .tangent2.value          - [Nf×3] Second tangent vectors (unit)
%     .tangent2.attributes     - Dataset metadata
%     .angleDefect.value       - [Nv×1] Angle defect (integrated Gaussian curvature)
%     .angleDefect.attributes  - Dataset metadata
%
% Description:
%   Aggregator function that computes all face-based geometric properties.
%   Output structure conforms to bct.manifold.geometry.face.schema for
%   seamless serialization to HDF5/Zarr formats.
%   The normals, tangent1, and tangent2 form right-handed orthonormal frames.
%
% Examples:
%   % Compute all face geometry
%   M = bct.Manifold(V, F);
%   faceGeom = bct.manifold.geometry.face(M);
%   
%   % Access individual properties
%   areas = faceGeom.areas.value;
%   normals = faceGeom.normals.value;
%   tangent1 = faceGeom.tangent1.value;
%   
%   % Compute with single precision
%   faceGeom = bct.manifold.geometry.face(M, 'precision', 'single');
%
% See also: bct.manifold.geometry.vertex, bct.manifold.geometry.edge,
%           bct.manifold.geometry

% Parse inputs
p = inputParser;
p.FunctionName = 'bct.manifold.geometry.face';
p.KeepUnmatched = true;

if isa(meshInput, 'bct.Manifold')
    addRequired(p, 'M', @(x) isa(x, 'bct.Manifold'));
    parse(p, meshInput);
else
    addRequired(p, 'V', @isnumeric);
    addRequired(p, 'F', @isnumeric);
    if isempty(varargin) || ~isnumeric(varargin{1})
        error('bct:manifold:geometry:face:InvalidInput', ...
            'Expected face(M) or face(V, F)');
    end
    parse(p, meshInput, varargin{1});
    varargin = varargin(2:end);  % Remove F from varargin
end

addParameter(p, 'precision', 'double', @(x) ischar(x) || isstring(x));
addParameter(p, 'circumcenterMethod', 'native', @(x) ischar(x) || isstring(x));
parse(p, meshInput, varargin{:});

precision = string(p.Results.precision);
circumcenterMethod = string(p.Results.circumcenterMethod);

% Create surfaceMesh once to avoid redundant creation in subfunctions
if isa(meshInput, 'bct.Manifold')
    V = meshInput.Vertices;
    F = meshInput.Faces;
else
    V = meshInput;
    F = varargin{1};
end
mesh = surfaceMesh(V, F);

% Compute all face properties
[areaHeader, areas] = bct.manifold.geometry.face.areas(mesh, 'precision', precision);
[circumHeader, circumcenters] = bct.manifold.geometry.face.circumcenters(mesh, ...
    'method', circumcenterMethod, 'precision', precision);
[centroidHeader, centroids] = bct.manifold.geometry.face.centroids(mesh);
[cotanHeader, cotan] = bct.manifold.geometry.face.cotan(mesh);
[frameHeader, normals, tangent1, tangent2] = bct.manifold.geometry.face.frame(mesh);
[angleDefectHeader, angleDefect] = bct.manifold.geometry.face.angleDefect(mesh, 'precision', precision);

% Initialize output structure matching schema
out = struct();

% Group-level attributes (matches s.group.attributes in schema)
out.attributes = struct();
out.attributes.schema = 'bct.manifold.geometry.face@1.0.0';
out.attributes.package = 'bct.manifold.geometry.face';
out.attributes.frame_handedness = 'right-handed';
out.attributes.frame_convention = 'tangent2 = normal × tangent1';
out.attributes.precision = char(precision);
out.attributes.circumcenterMethod = char(circumcenterMethod);
out.attributes.computed_utc = char(datetime('now', 'TimeZone', 'UTC', ...
    'Format', 'yyyy-MM-dd''T''HH:mm:ss''Z'''));

nF = size(F, 1);

% Dataset 1: areas
out.areas.value = areas;
out.areas.attributes = struct(...
    'name', 'areas', ...
    'path', 'geometry/face/areas', ...
    'description', 'Area of each triangular face', ...
    'shape', [nF, 1], ...
    'dtype', 'double', ...
    'units', 'm^2', ...
    'support', 'face', ...
    'computedBy', 'bct.manifold.geometry.face.areas');

% Dataset 2: circumcenters
out.circumcenters.value = circumcenters;
out.circumcenters.attributes = struct(...
    'name', 'circumcenters', ...
    'path', 'geometry/face/circumcenters', ...
    'description', 'Circumcenter of each triangular face', ...
    'shape', [nF, 3], ...
    'dtype', 'double', ...
    'units', 'm', ...
    'support', 'face', ...
    'computedBy', 'bct.manifold.geometry.face.circumcenters');

% Dataset 3: centroids
out.centroids.value = centroids;
out.centroids.attributes = struct(...
    'name', 'centroids', ...
    'path', 'geometry/face/centroids', ...
    'description', 'Centroid (barycenter) of each triangular face', ...
    'shape', [nF, 3], ...
    'dtype', 'double', ...
    'units', 'm', ...
    'support', 'face', ...
    'computedBy', 'bct.manifold.geometry.face.centroids');

% Dataset 4: cotan
out.cotan.value = cotan;
out.cotan.attributes = struct(...
    'name', 'cotan', ...
    'path', 'geometry/face/cotan', ...
    'description', 'Cotangent weights per face vertex', ...
    'shape', [nF, 3], ...
    'dtype', 'double', ...
    'units', '1', ...
    'support', 'face', ...
    'computedBy', 'bct.manifold.geometry.face.cotan');

% Dataset 5: normals
out.normals.value = normals;
out.normals.attributes = struct(...
    'name', 'normals', ...
    'path', 'geometry/face/normals', ...
    'description', 'Face normal vectors (unit)', ...
    'shape', [nF, 3], ...
    'dtype', 'double', ...
    'units', '1', ...
    'support', 'face', ...
    'normalization', 'unit', ...
    'computedBy', 'bct.manifold.geometry.face.frame');

% Dataset 6: tangent1
out.tangent1.value = tangent1;
out.tangent1.attributes = struct(...
    'name', 'tangent1', ...
    'path', 'geometry/face/tangent1', ...
    'description', 'First tangent vectors (unit)', ...
    'shape', [nF, 3], ...
    'dtype', 'double', ...
    'units', '1', ...
    'support', 'face', ...
    'normalization', 'unit', ...
    'computedBy', 'bct.manifold.geometry.face.frame');

% Dataset 7: tangent2
out.tangent2.value = tangent2;
out.tangent2.attributes = struct(...
    'name', 'tangent2', ...
    'path', 'geometry/face/tangent2', ...
    'description', 'Second tangent vectors (unit)', ...
    'shape', [nF, 3], ...
    'dtype', 'double', ...
    'units', '1', ...
    'support', 'face', ...
    'normalization', 'unit', ...
    'computedBy', 'bct.manifold.geometry.face.frame');

% Dataset 8: angleDefect
nV = size(V, 1);
out.angleDefect.value = angleDefect;
out.angleDefect.attributes = struct(...
    'name', 'angleDefect', ...
    'path', 'geometry/face/angleDefect', ...
    'description', 'Angle defect (integrated Gaussian curvature at vertices)', ...
    'shape', [nV, 1], ...
    'dtype', 'double', ...
    'units', 'rad', ...
    'support', 'vertex', ...
    'formula', 'K = 2π - Σ(angles)', ...
    'computedBy', 'bct.manifold.geometry.face.angleDefect');

end
