function s = schema()
%SCHEMA Schema definition for bct.manifold.geometry (top-level aggregator)
%
% Syntax:
%   s = bct.manifold.geometry.schema()
%
% Outputs:
%   s - Schema structure with fields:
%     .group      - Group metadata for HDF5/Zarr
%     .subgroups  - Array of subgroup schemas
%     .dimensions - (empty, dimensions defined in subgroups)
%     .datasets   - (empty, datasets defined in subgroups)
%
% Description:
%   This schema defines the hierarchical structure for complete manifold
%   geometry, aggregating vertex, face, edge, and dual submodules.
%   
%   HDF5/Zarr hierarchy:
%     geometry/                    (this group)
%       ├── vertex/                (vertex geometry subgroup)
%       │   ├── normals
%       │   ├── tangent1
%       │   └── tangent2
%       ├── face/                  (face geometry subgroup)
%       │   ├── areas
%       │   ├── circumcenters
%       │   ├── centroids
%       │   ├── cotan
%       │   ├── normals
%       │   ├── tangent1
%       │   └── tangent2
%       ├── edge/                  (edge geometry subgroup)
%       │   ├── lengths
%       │   ├── weights_cotangent
%       │   └── weights_euclidean
%       └── dual/                  (dual geometry subgroup)
%           ├── edgeLengths
%           └── vertexAreas
%
% See also: bct.manifold.geometry.vertex.schema,
%           bct.manifold.geometry.face.schema,
%           bct.manifold.geometry.edge.schema,
%           bct.manifold.geometry.dual.schema

% Initialize schema structure
s = struct();

%% Group metadata
s.group = struct();
s.group.name = 'geometry';
s.group.path = 'geometry';
s.group.schema = 'bct.manifold.geometry@1.0.0';

% Group-level attributes
s.group.attributes = struct();
s.group.attributes.schema = 'bct.manifold.geometry@1.0.0';
s.group.attributes.package = 'bct.manifold.geometry';
s.group.attributes.description = 'Complete geometric properties of the manifold';
s.group.attributes.subgroups = {'vertex', 'face', 'edge', 'dual'};

%% Subgroup schemas
% Each subgroup has its own schema defining its structure
s.subgroups = containers.Map();

% Vertex geometry subgroup
s.subgroups('vertex') = struct(...
    'name', 'vertex', ...
    'path', 'geometry/vertex', ...
    'schema_function', 'bct.manifold.geometry.vertex.schema', ...
    'required', true, ...
    'description', 'Vertex-based geometric properties (normals, tangent frames)');

% Face geometry subgroup
s.subgroups('face') = struct(...
    'name', 'face', ...
    'path', 'geometry/face', ...
    'schema_function', 'bct.manifold.geometry.face.schema', ...
    'required', true, ...
    'description', 'Face-based geometric properties (areas, centroids, normals, tangent frames)');

% Edge geometry subgroup
s.subgroups('edge') = struct(...
    'name', 'edge', ...
    'path', 'geometry/edge', ...
    'schema_function', 'bct.manifold.geometry.edge.schema', ...
    'required', true, ...
    'description', 'Edge-based geometric properties (lengths, weights)');

% Dual geometry subgroup
s.subgroups('dual') = struct(...
    'name', 'dual', ...
    'path', 'geometry/dual', ...
    'schema_function', 'bct.manifold.geometry.dual.schema', ...
    'required', false, ...
    'description', 'Dual mesh geometric properties (edge lengths, vertex areas)');

%% Dimensions
% No dimensions at this level - all defined in subgroups
s.dimensions = containers.Map();

%% Datasets
% No datasets at this level - all defined in subgroups
s.datasets = containers.Map();

%% Computation options
% Document available options for geometry computation
s.options = containers.Map();

s.options('precision') = struct(...
    'name', 'precision', ...
    'type', 'string', ...
    'allowed', {{'double', 'single'}}, ...
    'default', 'double', ...
    'description', 'Numeric precision for geometric computations');

s.options('circumcenterMethod') = struct(...
    'name', 'circumcenterMethod', ...
    'type', 'string', ...
    'allowed', {{'native', 'triangulation'}}, ...
    'default', 'native', ...
    'description', 'Method for computing face circumcenters');

s.options('boundaryPolicy') = struct(...
    'name', 'boundaryPolicy', ...
    'type', 'string', ...
    'allowed', {{'error', 'skip', 'extrapolate'}}, ...
    'default', 'error', ...
    'description', 'Policy for handling boundary edges in dual geometry');

s.options('dualCellType') = struct(...
    'name', 'dualCellType', ...
    'type', 'string', ...
    'allowed', {{'circumcentric', 'barycentric'}}, ...
    'default', 'circumcentric', ...
    'description', 'Type of dual cell for vertex area computation');

s.options('includeDual') = struct(...
    'name', 'includeDual', ...
    'type', 'logical', ...
    'allowed', [true, false], ...
    'default', false, ...
    'description', 'Whether to compute expensive dual geometry');

end
