% Decompose image using the CWTFT2 function

% Generated by MATLAB(R) 24.1 and Wavelet Toolbox 24.1.
% Generated on: 07-May-2025 02:37:25

% Define wavelet parameters
wname = "morlet";      % Name
k0 = 5;                % Higher center frequency for sharper localization
sigma = 8;             % Narrower bandwidth for better time localization

waveletStruct.name = wname;
waveletStruct.param = {k0, sqrt(sigma)};

% Define 2-D CWT parameters
scales = 2.^(0:0.25:5);  % Extended scale range for better frequency coverage
angles = linspace(0, 2*pi, 16);  % More angular precision
nm = "L2";  % Energy-preserving normalization


% Perform the decomposition using CWTFT2 to obtain the 2-D CWT structure
sensorData2_CWT = cwtft2(sensorData,Wavelet=waveletStruct,Scales=scales, ...
    Angles=angles,Norm=nm);

% For an image of size M-by-N-by-K, where K is 1 or 3, CWT coefficients
% are returned in the structure field sensorData2_CWT.cfs as an
% M-by-N-by-K-by-Nscales-by-Nangles array, where:
% * Nscales is the number of scales.
% * Nangles is the number of angles.

% To view the magnitude of the coefficients with the IMSHOW function,
% try scaling them with the WCODEMAT function. For example:
% >> imshow(uint8(wcodemat(abs(sensorData2_CWT.cfs(:,:,:,1,1)),255)))


% Visualize a single scale and angle (adjust as needed)
imshow(uint8(wcodemat(abs(sensorData2_CWT.cfs(:,:,:,1,1)),255)));

