function defs = inspectors()
%BCT.REGISTRY.UI.INSPECTORS  Authoritative registry of UI inspector components
%
%   defs = bct.registry.ui.inspectors()
%
% Purpose
%   Single source of truth for available UI inspectors.
%   Used by bct.runtime.ui.resolveInspector for dispatch.
%
% Output
%   defs - struct array with fields:
%          Id        (string): unique inspector identifier
%          Class     (string): full class name (e.g., "bct.ui.manifold.Inspector")
%          Supports  (string array): model classes this inspector can display
%          Priority  (double): higher wins when multiple match (default: 10)
%          Tags      (string array): optional classification tags
%          Notes     (string): optional description
%
% Contract
%   Per BCTUIMANIFOLD_CONTRACT.md:
%   - Registry contains NO UI state (no graphics handles)
%   - Registry is deterministic (no randomness, no external state)
%   - Only Inspector components are registered (not renderers or adapters)
%
% See also: bct.runtime.ui.resolveInspector, bct.ui.show

    % Initialize empty with proper field order
    defs = initializeEmpty();
    
    % Manifold Inspector
    defs(end+1) = struct( ...
        'Id', "ManifoldInspector", ...
        'Class', "bct.ui.manifold.Inspector", ...
        'Supports', ["bct.Manifold"], ...
        'Priority', 10, ...
        'Tags', ["3d", "mesh", "viewer"], ...
        'Notes', "Interactive 3D manifold viewer with scalar/vector overlays" ...
    );
    
    % Manifold Selector (lightweight alternative)
    defs(end+1) = struct( ...
        'Id', "ManifoldSelector", ...
        'Class', "bct.ui.manifold.Selector", ...
        'Supports', ["bct.Manifold"], ...
        'Priority', 5, ...
        'Tags', ["3d", "viewer3d", "fast", "lightweight", "selection"], ...
        'Notes', "Lightweight viewer3d-based selector with vertex selection" ...
    );
    
    % Kernel Inspector (placeholder for future implementation)
    defs(end+1) = struct( ...
        'Id', "KernelInspector", ...
        'Class', "bct.ui.kernel.Inspector", ...
        'Supports', ["struct", "bct.KernelSpec"], ...
        'Priority', 10, ...
        'Tags', ["1d", "plot", "function"], ...
        'Notes', "Kernel function plot viewer with parameter controls" ...
    );
    
    % Fplot Component (function handle plotter)
    defs(end+1) = struct( ...
        'Id', "FplotComponent", ...
        'Class', "bct.ui.component.Fplot", ...
        'Supports', ["function_handle"], ...
        'Priority', 5, ...
        'Tags', ["1d", "plot", "function", "primitive"], ...
        'Notes', "Lightweight 1D function plotter for y=f(x) visualization" ...
    );
end

function empty = initializeEmpty()
    % Initialize with all fields in proper order
    empty = struct( ...
        'Id', string.empty, ...
        'Class', string.empty, ...
        'Supports', string.empty(0,0), ...
        'Priority', [], ...
        'Tags', string.empty(0,0), ...
        'Notes', string.empty);
    empty(:) = [];  % Make 0×1 array with proper fields
end
