function R = registry()
%BCT.BRUSH.REGISTRY  Brush registry (engine-level, stateless)
%
%   R = bct.brush.registry()
%
%   DEPRECATED: This function is maintained for backward compatibility.
%   New code should use bct.registry.brushes() and bct.runtime.brushes.*
%
%   Each entry declares:
%     - Name        : human-readable
%     - Category    : patch | trajectory | time | dynamic
%     - Algorithm   : function handle
%
%   See also: bct.registry.brushes, bct.runtime.brushes.dictionary

    % Issue deprecation warning once per session
    persistent hasWarned
    if isempty(hasWarned)
        warning('bct:brush:registry:Deprecated', ...
            ['bct.brush.registry() is deprecated. ' ...
             'Use bct.registry.brushes() and bct.runtime.brushes.* instead.']);
        hasWarned = true;
    end

    R = struct();

    % =========================================================
    % Patch brushes (unordered spatial selections)
    % =========================================================

    R.patch_nearest = struct( ...
        'Name',       'Nearest-neighbor patch', ...
        'Category',   'patch', ...
        'Algorithm',  @bct.brush.patch.nearest ...
    );

    R.patch_gaussian = struct( ...
        'Name',       'Gaussian-weighted patch', ...
        'Category',   'patch', ...
        'Algorithm',  @bct.brush.patch.gaussian ...
    );

    R.patch_spectral = struct( ...
        'Name',       'Spectral patch (eigenmode filtering)', ...
        'Category',   'patch', ...
        'Algorithm',  @bct.brush.patch.spectral ...
    );

    % =========================================================
    % Trajectory brushes (ordered spatial paths)
    % =========================================================

    R.trajectory_geodesic = struct( ...
        'Name',       'Geodesic shortest path', ...
        'Category',   'trajectory', ...
        'Algorithm',  @bct.brush.trajectory.geodesic ...
    );

    R.trajectory_gaussian = struct( ...
        'Name',       'Gaussian-weighted trajectory', ...
        'Category',   'trajectory', ...
        'Algorithm',  @bct.brush.trajectory.gaussian ...
    );

    R.trajectory_spectral = struct( ...
        'Name',       'Spectral-filtered trajectory', ...
        'Category',   'trajectory', ...
        'Algorithm',  @bct.brush.trajectory.spectral ...
    );

    % =========================================================
    % Time brushes (spatiotemporal patterns)
    % =========================================================

    R.time_heat = struct( ...
        'Name',       'Heat diffusion along trajectory', ...
        'Category',   'time', ...
        'Algorithm',  @bct.brush.time.heat ...
    );

    R.time_spectral = struct( ...
        'Name',       'Spectral patch at each time step', ...
        'Category',   'time', ...
        'Algorithm',  @bct.brush.time.spectral ...
    );

end
