function s = schema()
%SCHEMA HDF5/Zarr schema for operator data structure
%
% Syntax:
%   s = bct.manifold.operator.schema()
%
% Outputs:
%   s - Schema structure defining HDF5/Zarr layout for operator data
%
% Description:
%   Defines the canonical schema for differential operator structures to
%   enable HDF5 and Zarr serialization. The schema follows standard conventions:
%   
%   - Group-level metadata in attributes
%   - Sparse matrices stored as COO format (row, col, data)
%   - Dimensions define array shapes
%   - Paths define HDF5/Zarr hierarchy
%
%   Schema version: bct.manifold.operator@1.0.0
%
% Schema Structure:
%   operator/
%   ├── @attributes           # Group-level metadata
%   │   ├── schema           # "bct.manifold.operator@1.0.0"
%   │   ├── package          # "bct.manifold.operator"
%   │   ├── numVertices      # Number of vertices (N)
%   │   ├── numFaces         # Number of faces (M)
%   │   ├── numEdges         # Number of edges (E)
%   │   ├── massVariant      # Mass matrix type
%   │   ├── stiffnessVariant # Stiffness matrix type
%   │   └── stiffnessSign    # Stiffness sign convention
%   ├── mass/                # Mass matrix (sparse COO)
%   │   ├── row              # [nnz×1] row indices
%   │   ├── col              # [nnz×1] column indices
%   │   └── data             # [nnz×1] matrix values
%   ├── stiffness/           # Stiffness matrix (sparse COO)
%   │   ├── row
%   │   ├── col
%   │   └── data
%   ├── mft/                 # Forward manifold Fourier transform
%   │   ├── row
%   │   ├── col
%   │   └── data
%   └── imft/                # Inverse manifold Fourier transform
%       ├── row
%       ├── col
%       └── data
%
% Examples:
%   % Get schema
%   s = bct.manifold.operator.schema();
%   
%   % Access dimensions
%   dimNames = s.dimensions.keys();  % {'numVertices', 'numFaces', ...}
%   
%   % Access datasets
%   massData = s.datasets('mass_data');
%
% See also: bct.manifold.operator, bct.manifold.operator.mass,
%           bct.manifold.operator.stiffness, bct.manifold.operator.mft

% Schema metadata
s.group.name = 'operator';
s.group.path = 'operator';
s.group.schema = 'bct.manifold.operator@1.0.0';

% Group-level attributes (metadata)
s.group.attributes = {
    struct('name', 'schema',           'dtype', 'string',  'description', 'Schema version identifier');
    struct('name', 'package',          'dtype', 'string',  'description', 'MATLAB package path');
    struct('name', 'numVertices',      'dtype', 'uint32',  'description', 'Number of vertices (N)');
    struct('name', 'numFaces',         'dtype', 'uint32',  'description', 'Number of faces (M)');
    struct('name', 'numEdges',         'dtype', 'uint32',  'description', 'Number of edges (E)');
    struct('name', 'massVariant',      'dtype', 'string',  'description', 'Mass matrix type ("voronoi", "barycentric", "full")');
    struct('name', 'stiffnessVariant', 'dtype', 'string',  'description', 'Stiffness matrix type ("cotan")');
    struct('name', 'stiffnessSign',    'dtype', 'string',  'description', 'Sign convention ("positive", "negative")');
    struct('name', 'sparseFormat',     'dtype', 'string',  'description', 'Sparse matrix storage format ("coo" for HDF5/Zarr export)');
};

% Dimensions (array shapes)
s.dimensions = containers.Map();
s.dimensions('numVertices') = struct(...
    'description', 'Number of vertices (N)', ...
    'dynamic', true);
s.dimensions('numFaces') = struct(...
    'description', 'Number of faces (M)', ...
    'dynamic', true);
s.dimensions('numEdges') = struct(...
    'description', 'Number of edges (E)', ...
    'dynamic', true);
s.dimensions('nnz_mass') = struct(...
    'description', 'Number of non-zeros in mass matrix', ...
    'dynamic', true);
s.dimensions('nnz_stiffness') = struct(...
    'description', 'Number of non-zeros in stiffness matrix', ...
    'dynamic', true);
s.dimensions('nnz_mft') = struct(...
    'description', 'Number of non-zeros in MFT matrix', ...
    'dynamic', true);
s.dimensions('nnz_imft') = struct(...
    'description', 'Number of non-zeros in IMFT matrix', ...
    'dynamic', true);

% Datasets (data arrays)
s.datasets = containers.Map();

% Mass matrix - stored as MATLAB sparse, exported as COO
s.datasets('mass') = struct(...
    'name', 'mass', ...
    'path', 'operator/mass', ...
    'dims', 'numVertices,numVertices', ...
    'shape', [NaN, NaN], ...
    'dtype', struct(...
        'matlab', 'double sparse', ...
        'hdf5', 'COO format (row/col/data groups)', ...
        'zarr', 'COO format (row/col/data arrays)'), ...
    'description', 'FEM mass matrix (area-weighted inner product)', ...
    'units', 'area_units', ...
    'storage', 'sparse', ...
    'exportFormat', 'coo', ...
    'required', true);

% Stiffness matrix - stored as MATLAB sparse, exported as COO
s.datasets('stiffness') = struct(...
    'name', 'stiffness', ...
    'path', 'operator/stiffness', ...
    'dims', 'numVertices,numVertices', ...
    'shape', [NaN, NaN], ...
    'dtype', struct(...
        'matlab', 'double sparse', ...
        'hdf5', 'COO format (row/col/data groups)', ...
        'zarr', 'COO format (row/col/data arrays)'), ...
    'description', 'FEM stiffness matrix (cotangent Laplacian)', ...
    'units', 'dimensionless', ...
    'storage', 'sparse', ...
    'exportFormat', 'coo', ...
    'required', true);

% MFT (forward manifold Fourier transform) - stored as MATLAB sparse/dense, exported as COO
s.datasets('mft') = struct(...
    'name', 'mft', ...
    'path', 'operator/mft', ...
    'dims', 'numModes,numVertices', ...
    'shape', [NaN, NaN], ...
    'dtype', struct(...
        'matlab', 'double', ...
        'hdf5', 'COO format (row/col/data groups)', ...
        'zarr', 'COO format (row/col/data arrays)'), ...
    'description', 'Forward manifold Fourier transform operator (U'' * Mass)', ...
    'units', 'length_units', ...
    'storage', 'sparse', ...
    'exportFormat', 'coo', ...
    'required', false);

% IMFT (inverse manifold Fourier transform) - stored as MATLAB sparse/dense, exported as COO
s.datasets('imft') = struct(...
    'name', 'imft', ...
    'path', 'operator/imft', ...
    'dims', 'numVertices,numModes', ...
    'shape', [NaN, NaN], ...
    'dtype', struct(...
        'matlab', 'double', ...
        'hdf5', 'COO format (row/col/data groups)', ...
        'zarr', 'COO format (row/col/data arrays)'), ...
    'description', 'Inverse manifold Fourier transform operator (U)', ...
    'units', '1/length_units', ...
    'storage', 'sparse', ...
    'exportFormat', 'coo', ...
    'required', false);

% Schema validation function
s.validate = @(ops) validateOperatorSchema(ops);

end

function tf = validateOperatorSchema(ops)
%VALIDATEOPERATORSCHEMA Validate operator structure against schema
%
% Inputs:
%   ops - Structure to validate
%
% Outputs:
%   tf - true if valid, false otherwise (with error messages)

tf = true;

% Check required fields
requiredFields = {'mass', 'stiffness'};
for i = 1:length(requiredFields)
    field = requiredFields{i};
    if ~isfield(ops, field)
        warning('bct:manifold:operator:schema:MissingField', ...
            'Missing required field: %s', field);
        tf = false;
    end
end

% Check attributes exist
if ~isfield(ops, 'attributes')
    warning('bct:manifold:operator:schema:MissingAttributes', ...
        'Missing attributes field');
    tf = false;
    return;
end

% Check required attributes
requiredAttrs = {'schema', 'package', 'numVertices', 'numFaces', ...
                 'numEdges', 'massVariant', 'stiffnessVariant', ...
                 'stiffnessSign', 'sparseFormat'};
for i = 1:length(requiredAttrs)
    attr = requiredAttrs{i};
    if ~isfield(ops.attributes, attr)
        warning('bct:manifold:operator:schema:MissingAttribute', ...
            'Missing required attribute: %s', attr);
        tf = false;
    end
end

% Validate that matrices are sparse
if isfield(ops, 'mass') && ~issparse(ops.mass)
    warning('bct:manifold:operator:schema:NotSparse', ...
        'mass must be a sparse matrix');
    tf = false;
end

if isfield(ops, 'stiffness') && ~issparse(ops.stiffness)
    warning('bct:manifold:operator:schema:NotSparse', ...
        'stiffness must be a sparse matrix');
    tf = false;
end

end