function specs = kernels()
%BCT.REGISTRY.KERNELS Semantic catalog of all kernel specifications
%
% Syntax:
%   specs = bct.registry.kernels()
%
% Outputs:
%   specs - Array of KernelSpec structs
%
% Description:
%   Returns the authoritative semantic catalog of all kernels in the
%   BCT toolbox. Each KernelSpec contains:
%
%   Required fields:
%     Id          - Stable identifier matching dictionary key
%     Name        - UI-friendly display name
%     Category    - "kernel"|"window"|"pointwise"|"stochastic"|"phase"|"utility"
%     Signature   - Ordered parameter names (after x axis)
%     Defaults    - Struct with default parameter values
%
%   Optional fields:
%     Description   - Scientific description
%     AxisKinds     - Applicable axes: "lambda"|"time"|"frequency"|"distance"|"index"|"generic"
%     Tags          - ["smooth","lowpass","highpass","bandpass","oscillatory","compact"]
%     Dependencies  - Required toolboxes/functions
%     ParamSchema   - Validation rules per parameter
%
% See also: bct.kernel.dictionary, bct.kernel.get, bct.kernel.list

specs = [];

%% =================================================================
% SMOOTHING / LOW-PASS KERNELS
%% =================================================================

specs(end+1) = struct( ...
    'Id', "Heat", ...
    'Name', "Heat Kernel", ...
    'Category', "kernel", ...
    'Signature', ["tau"], ...
    'Defaults', struct('tau', 0.1), ...
    'Description', "Exponential decay: exp(-τλ). Diffusion-based low-pass filter", ...
    'AxisKinds', ["lambda"], ...
    'Tags', ["smooth", "lowpass", "monotonic"], ...
    'Dependencies', string.empty, ...
    'ParamSchema', struct('tau', struct('Type', 'double', 'Positive', true)) ...
);

specs(end+1) = struct( ...
    'Id', "Gaussian", ...
    'Name', "Gaussian", ...
    'Category', "kernel", ...
    'Signature', ["mu", "sigma"], ...
    'Defaults', struct('mu', 0, 'sigma', 0.2), ...
    'Description', "Gaussian bell curve: exp(-(x-μ)²/(2σ²))", ...
    'AxisKinds', ["lambda", "time", "frequency", "distance", "generic"], ...
    'Tags', ["smooth", "bandpass", "symmetric"], ...
    'Dependencies', string.empty, ...
    'ParamSchema', struct( ...
        'mu', struct('Type', 'double'), ...
        'sigma', struct('Type', 'double', 'Positive', true)) ...
);

specs(end+1) = struct( ...
    'Id', "Laplacian", ...
    'Name', "Laplacian (Double Exponential)", ...
    'Category', "kernel", ...
    'Signature', ["mu", "b"], ...
    'Defaults', struct('mu', 0, 'b', 0.2), ...
    'Description', "Double exponential: exp(-|x-μ|/b)", ...
    'AxisKinds', ["lambda", "time", "frequency", "distance", "generic"], ...
    'Tags', ["sharp", "bandpass"], ...
    'Dependencies', string.empty, ...
    'ParamSchema', struct( ...
        'mu', struct('Type', 'double'), ...
        'b', struct('Type', 'double', 'Positive', true)) ...
);

specs(end+1) = struct( ...
    'Id', "Cauchy", ...
    'Name', "Cauchy / Lorentzian", ...
    'Category', "kernel", ...
    'Signature', ["mu", "gamma"], ...
    'Defaults', struct('mu', 0, 'gamma', 0.2), ...
    'Description', "Lorentzian: 1/(1+((x-μ)/γ)²)", ...
    'AxisKinds', ["lambda", "frequency", "generic"], ...
    'Tags', ["heavy-tails", "bandpass"], ...
    'Dependencies', string.empty, ...
    'ParamSchema', struct( ...
        'mu', struct('Type', 'double'), ...
        'gamma', struct('Type', 'double', 'Positive', true)) ...
);

%% =================================================================
% WAVELET / OSCILLATORY KERNELS
%% =================================================================

specs(end+1) = struct( ...
    'Id', "Ricker", ...
    'Name', "Ricker Wavelet (Mexican Hat)", ...
    'Category', "kernel", ...
    'Signature', ["sigma"], ...
    'Defaults', struct('sigma', 0.2), ...
    'Description', "Classical Mexican hat: (1-x²/σ²)exp(-x²/(2σ²))", ...
    'AxisKinds', ["time", "distance", "generic"], ...
    'Tags', ["wavelet", "bandpass", "oscillatory"], ...
    'Dependencies', string.empty, ...
    'ParamSchema', struct('sigma', struct('Type', 'double', 'Positive', true)) ...
);

specs(end+1) = struct( ...
    'Id', "SpectralMexicanHat", ...
    'Name', "Spectral Mexican Hat", ...
    'Category', "kernel", ...
    'Signature', ["tau"], ...
    'Defaults', struct('tau', 0.1), ...
    'Description', "Graph spectral: λ·exp(-τλ). Emphasizes mid-frequencies", ...
    'AxisKinds', ["lambda"], ...
    'Tags', ["bandpass", "spectral"], ...
    'Dependencies', string.empty, ...
    'ParamSchema', struct('tau', struct('Type', 'double', 'Positive', true)) ...
);

specs(end+1) = struct( ...
    'Id', "Morlet", ...
    'Name', "Morlet Wavelet", ...
    'Category', "kernel", ...
    'Signature', ["mu", "sigma", "omega"], ...
    'Defaults', struct('mu', 0, 'sigma', 0.2, 'omega', 5), ...
    'Description', "Complex wavelet: exp(-(x-μ)²/(2σ²))·exp(iω(x-μ))", ...
    'AxisKinds', ["time", "distance"], ...
    'Tags', ["wavelet", "complex", "oscillatory"], ...
    'Dependencies', string.empty, ...
    'ParamSchema', struct( ...
        'mu', struct('Type', 'double'), ...
        'sigma', struct('Type', 'double', 'Positive', true), ...
        'omega', struct('Type', 'double')) ...
);

specs(end+1) = struct( ...
    'Id', "Gabor", ...
    'Name', "Gabor Filter", ...
    'Category', "kernel", ...
    'Signature', ["mu", "sigma", "f0"], ...
    'Defaults', struct('mu', 0, 'sigma', 0.2, 'f0', 5), ...
    'Description', "Gabor: exp(-(x-μ)²/(2σ²))·cos(2πf₀(x-μ))", ...
    'AxisKinds', ["time", "distance"], ...
    'Tags', ["wavelet", "oscillatory", "real"], ...
    'Dependencies', string.empty, ...
    'ParamSchema', struct( ...
        'mu', struct('Type', 'double'), ...
        'sigma', struct('Type', 'double', 'Positive', true), ...
        'f0', struct('Type', 'double')) ...
);

%% =================================================================
% BAND-PASS / FILTER SHAPES
%% =================================================================

specs(end+1) = struct( ...
    'Id', "DoG", ...
    'Name', "Difference of Gaussians", ...
    'Category', "kernel", ...
    'Signature', ["tau1", "tau2"], ...
    'Defaults', struct('tau1', 0.05, 'tau2', 0.2), ...
    'Description', "DoG: exp(-τ₁λ) - exp(-τ₂λ). Band-pass on λ", ...
    'AxisKinds', ["lambda"], ...
    'Tags', ["bandpass", "spectral"], ...
    'Dependencies', string.empty, ...
    'ParamSchema', struct( ...
        'tau1', struct('Type', 'double', 'Positive', true), ...
        'tau2', struct('Type', 'double', 'Positive', true)) ...
);

specs(end+1) = struct( ...
    'Id', "Boxcar", ...
    'Name', "Boxcar / Rectangular", ...
    'Category', "window", ...
    'Signature', ["center", "width"], ...
    'Defaults', struct('center', 0, 'width', 1), ...
    'Description', "Rectangular window centered at specified location", ...
    'AxisKinds', ["generic"], ...
    'Tags', ["sharp", "compact"], ...
    'Dependencies', string.empty, ...
    'ParamSchema', struct( ...
        'center', struct('Type', 'double'), ...
        'width', struct('Type', 'double', 'Positive', true)) ...
);

specs(end+1) = struct( ...
    'Id', "Triangle", ...
    'Name', "Triangle", ...
    'Category', "window", ...
    'Signature', ["center", "width"], ...
    'Defaults', struct('center', 0, 'width', 1), ...
    'Description', "Triangular window with linear falloff", ...
    'AxisKinds', ["generic"], ...
    'Tags', ["smooth", "compact"], ...
    'Dependencies', string.empty, ...
    'ParamSchema', struct( ...
        'center', struct('Type', 'double'), ...
        'width', struct('Type', 'double', 'Positive', true)) ...
);

specs(end+1) = struct( ...
    'Id', "RaisedCosine", ...
    'Name', "Raised Cosine", ...
    'Category', "window", ...
    'Signature', ["x1", "x2"], ...
    'Defaults', struct('x1', -0.5, 'x2', 0.5), ...
    'Description', "Smooth cosine transition between x1 and x2", ...
    'AxisKinds', ["generic"], ...
    'Tags', ["smooth", "transition"], ...
    'Dependencies', string.empty, ...
    'ParamSchema', struct( ...
        'x1', struct('Type', 'double'), ...
        'x2', struct('Type', 'double')) ...
);

%% =================================================================
% WINDOW FUNCTIONS
%% =================================================================

specs(end+1) = struct( ...
    'Id', "Hann", ...
    'Name', "Hann Window", ...
    'Category', "window", ...
    'Signature', ["T"], ...
    'Defaults', struct('T', 1), ...
    'Description', "Hann window: 0.5(1-cos(2πt/T))", ...
    'AxisKinds', ["time", "index"], ...
    'Tags', ["smooth", "window"], ...
    'Dependencies', string.empty, ...
    'ParamSchema', struct('T', struct('Type', 'double', 'Positive', true)) ...
);

specs(end+1) = struct( ...
    'Id', "Hamming", ...
    'Name', "Hamming Window", ...
    'Category', "window", ...
    'Signature', ["T"], ...
    'Defaults', struct('T', 1), ...
    'Description', "Hamming window: 0.54 - 0.46cos(2πt/T)", ...
    'AxisKinds', ["time", "index"], ...
    'Tags', ["smooth", "window"], ...
    'Dependencies', string.empty, ...
    'ParamSchema', struct('T', struct('Type', 'double', 'Positive', true)) ...
);

%% =================================================================
% IMPULSE / INDICATOR FUNCTIONS
%% =================================================================

specs(end+1) = struct( ...
    'Id', "Delta", ...
    'Name', "Delta / Kronecker", ...
    'Category', "kernel", ...
    'Signature', ["center"], ...
    'Defaults', struct('center', 0), ...
    'Description', "Impulse at specified location", ...
    'AxisKinds', ["generic"], ...
    'Tags', ["impulse", "sharp"], ...
    'Dependencies', string.empty, ...
    'ParamSchema', struct('center', struct('Type', 'double')) ...
);

specs(end+1) = struct( ...
    'Id', "Indicator", ...
    'Name', "Indicator Function", ...
    'Category', "kernel", ...
    'Signature', ["xmin", "xmax"], ...
    'Defaults', struct('xmin', -0.5, 'xmax', 0.5), ...
    'Description', "Characteristic function of interval [xmin, xmax]", ...
    'AxisKinds', ["generic"], ...
    'Tags', ["sharp", "compact"], ...
    'Dependencies', string.empty, ...
    'ParamSchema', struct( ...
        'xmin', struct('Type', 'double'), ...
        'xmax', struct('Type', 'double')) ...
);

specs(end+1) = struct( ...
    'Id', "Constant", ...
    'Name', "Constant", ...
    'Category', "kernel", ...
    'Signature', ["value"], ...
    'Defaults', struct('value', 1), ...
    'Description', "Constant value across all axes", ...
    'AxisKinds', ["generic"], ...
    'Tags', ["trivial"], ...
    'Dependencies', string.empty, ...
    'ParamSchema', struct('value', struct('Type', 'double')) ...
);

%% =================================================================
% DISTANCE-BASED KERNELS
%% =================================================================

specs(end+1) = struct( ...
    'Id', "InverseDistance", ...
    'Name', "Inverse Distance", ...
    'Category', "kernel", ...
    'Signature', ["p"], ...
    'Defaults', struct('p', 1), ...
    'Description', "Inverse power: 1/(d^p + ε)", ...
    'AxisKinds', ["distance"], ...
    'Tags', ["decay", "spatial"], ...
    'Dependencies', string.empty, ...
    'ParamSchema', struct('p', struct('Type', 'double', 'Positive', true)) ...
);

specs(end+1) = struct( ...
    'Id', "GaussianDistance", ...
    'Name', "Gaussian Distance Kernel", ...
    'Category', "kernel", ...
    'Signature', ["sigma"], ...
    'Defaults', struct('sigma', 0.2), ...
    'Description', "Gaussian decay with distance: exp(-d²/(2σ²))", ...
    'AxisKinds', ["distance"], ...
    'Tags', ["smooth", "decay", "spatial"], ...
    'Dependencies', string.empty, ...
    'ParamSchema', struct('sigma', struct('Type', 'double', 'Positive', true)) ...
);

specs(end+1) = struct( ...
    'Id', "CompactSupport", ...
    'Name', "Compact Support Kernel", ...
    'Category', "kernel", ...
    'Signature', ["R"], ...
    'Defaults', struct('R', 1), ...
    'Description', "Linear decay to zero at radius R: max(0, 1-d/R)", ...
    'AxisKinds', ["distance"], ...
    'Tags', ["compact", "spatial"], ...
    'Dependencies', string.empty, ...
    'ParamSchema', struct('R', struct('Type', 'double', 'Positive', true)) ...
);

end
