function specs = operators()
%OPERATORS Authoritative catalog of all operators in bct ecosystem
%
% Syntax:
%   specs = bct.registry.operators()
%
% Returns:
%   specs - Struct with operator specifications, keyed by operator ID
%
% Each OperatorSpec has fields:
%   id              - Stable canonical identifier (string)
%   name            - Display name (string)
%   domain          - "fem", "dec", "graph", "spectral", "kernel" (string)
%   representation  - Required class (e.g., "bct.FEM") (string)
%   inputType       - Semantic type: "signal", "coefficients", "0-form", etc.
%   outputType      - Semantic output type (string)
%   formDegree      - DEC form degree (double or [])
%   parameters      - Required parameters (struct)
%   requires        - Required capabilities (string array)
%   function        - Function handle to implementation
%   purity          - "pure" or "impure" (string)
%   description     - Human-readable description (string)
%
% Design principles (from OperatorsContract):
%   - Registry is declarative and static
%   - Registry describes what exists
%   - Registry never decides what runs
%   - Content is deterministic
%   - No runtime objects allowed
%
% See also: bct.runtime.operators

% Initialize specs struct
specs = struct();

%% ========================================================================
%% FEM OPERATORS (Tier 1: Representation-bound)
%% ========================================================================

specs.fem_heat = struct(...
    'id', "fem_heat", ...
    'name', "Heat Evolution (FEM)", ...
    'domain', "fem", ...
    'representation', "bct.FEM", ...
    'inputType', "signal", ...
    'outputType', "signal", ...
    'formDegree', [], ...
    'parameters', struct('t', 'time', 'k', 'num_modes'), ...
    'requires', ["Mass", "Stiffness", "Eigenpairs"], ...
    'function', @bct.fem.heat, ...
    'purity', "pure", ...
    'description', "Diffusion via heat equation: exp(-t*Δ)");

specs.fem_wave = struct(...
    'id', "fem_wave", ...
    'name', "Wave Evolution (FEM)", ...
    'domain', "fem", ...
    'representation', "bct.FEM", ...
    'inputType', "signal", ...
    'outputType', "signal", ...
    'formDegree', [], ...
    'parameters', struct('t', 'time', 'k', 'num_modes'), ...
    'requires', ["Mass", "Stiffness", "Eigenpairs"], ...
    'function', @bct.fem.wave, ...
    'purity', "pure", ...
    'description', "Wave propagation: cos(t*sqrt(Δ))");

specs.fem_schrodinger = struct(...
    'id', "fem_schrodinger", ...
    'name', "Schrödinger Evolution (FEM)", ...
    'domain', "fem", ...
    'representation', "bct.FEM", ...
    'inputType', "signal", ...
    'outputType', "signal", ...
    'formDegree', [], ...
    'parameters', struct('t', 'time', 'k', 'num_modes'), ...
    'requires', ["Mass", "Stiffness", "Eigenpairs"], ...
    'function', @bct.fem.schrodinger, ...
    'purity', "pure", ...
    'description', "Quantum dynamics: exp(-i*t*Δ)");

specs.fem_filter = struct(...
    'id', "fem_filter", ...
    'name', "Spectral Filter (FEM)", ...
    'domain', "fem", ...
    'representation', "bct.FEM", ...
    'inputType', "signal", ...
    'outputType', "signal", ...
    'formDegree', [], ...
    'parameters', struct('kernel', 'function_handle', 'k', 'num_modes'), ...
    'requires', ["Mass", "Stiffness", "Eigenpairs"], ...
    'function', @bct.fem.filter, ...
    'purity', "pure", ...
    'description', "Apply spectral kernel to signal");

specs.fem_applyLaplacian = struct(...
    'id', "fem_applyLaplacian", ...
    'name', "Apply Laplacian (FEM)", ...
    'domain', "fem", ...
    'representation', "bct.FEM", ...
    'inputType', "signal", ...
    'outputType', "signal", ...
    'formDegree', [], ...
    'parameters', struct(), ...
    'requires', ["Mass", "Stiffness"], ...
    'function', @bct.fem.applyLaplacian, ...
    'purity', "pure", ...
    'description', "Direct application: L = M^(-1)*K");

specs.fem_norm = struct(...
    'id', "fem_norm", ...
    'name', "L2 Norm (FEM)", ...
    'domain', "fem", ...
    'representation', "bct.FEM", ...
    'inputType', "signal", ...
    'outputType', "scalar", ...
    'formDegree', [], ...
    'parameters', struct(), ...
    'requires', ["Mass"], ...
    'function', @(fem, x) fem.norm(x), ...
    'purity', "pure", ...
    'description', "L2 norm with mass matrix");

specs.fem_energy = struct(...
    'id', "fem_energy", ...
    'name', "Dirichlet Energy (FEM)", ...
    'domain', "fem", ...
    'representation', "bct.FEM", ...
    'inputType', "signal", ...
    'outputType', "scalar", ...
    'formDegree', [], ...
    'parameters', struct(), ...
    'requires', ["Stiffness"], ...
    'function', @(fem, x) fem.energy(x), ...
    'purity', "pure", ...
    'description', "Dirichlet energy: x'*K*x");

%% ========================================================================
%% SPECTRAL OPERATORS (Tier 2: Eigenpairs-based)
%% ========================================================================

specs.spectral_project = struct(...
    'id', "spectral_project", ...
    'name', "Spectral Projection", ...
    'domain', "spectral", ...
    'representation', "bct.Eigenpairs", ...
    'inputType', "signal", ...
    'outputType', "coefficients", ...
    'formDegree', [], ...
    'parameters', struct(), ...
    'requires', ["Eigenvectors", "MassMatrix"], ...
    'function', @(E, x) E.project(x), ...
    'purity', "pure", ...
    'description', "Forward transform: U'*M*x");

specs.spectral_reconstruct = struct(...
    'id', "spectral_reconstruct", ...
    'name', "Spectral Reconstruction", ...
    'domain', "spectral", ...
    'representation', "bct.Eigenpairs", ...
    'inputType', "coefficients", ...
    'outputType', "signal", ...
    'formDegree', [], ...
    'parameters', struct(), ...
    'requires', ["Eigenvectors"], ...
    'function', @(E, c) E.reconstruct(c), ...
    'purity', "pure", ...
    'description', "Inverse transform: U*c");

specs.spectral_bandlimit = struct(...
    'id', "spectral_bandlimit", ...
    'name', "Bandlimit Eigenpairs", ...
    'domain', "spectral", ...
    'representation', "bct.Eigenpairs", ...
    'inputType', "eigenpairs", ...
    'outputType', "eigenpairs", ...
    'formDegree', [], ...
    'parameters', struct('range', 'lambda_range'), ...
    'requires', ["Eigenvalues"], ...
    'function', @(E, range) E.bandlimit(range), ...
    'purity', "pure", ...
    'description', "Filter modes by eigenvalue range");

specs.spectral_truncate = struct(...
    'id', "spectral_truncate", ...
    'name', "Truncate Eigenpairs", ...
    'domain', "spectral", ...
    'representation', "bct.Eigenpairs", ...
    'inputType', "eigenpairs", ...
    'outputType', "eigenpairs", ...
    'formDegree', [], ...
    'parameters', struct('k', 'num_modes'), ...
    'requires', ["Eigenvalues"], ...
    'function', @(E, k) E.truncate(k), ...
    'purity', "pure", ...
    'description', "Keep first k modes");

specs.spectral_energy = struct(...
    'id', "spectral_energy", ...
    'name', "Spectral Energy", ...
    'domain', "spectral", ...
    'representation', "bct.Eigenpairs", ...
    'inputType', "coefficients", ...
    'outputType', "scalar", ...
    'formDegree', [], ...
    'parameters', struct(), ...
    'requires', ["Eigenvalues"], ...
    'function', @(E, c) E.energy(c), ...
    'purity', "pure", ...
    'description', "Spectral energy: sum(λ*|c|^2)");

%% ========================================================================
%% EIGENPAIRS FACTORY OPERATORS (Tier 2: Construction)
%% ========================================================================

specs.eigenpairs_fromFEM = struct(...
    'id', "eigenpairs_fromFEM", ...
    'name', "Compute Eigenpairs (FEM)", ...
    'domain', "spectral", ...
    'representation', "bct.FEM", ...
    'inputType', "none", ...
    'outputType', "eigenpairs", ...
    'formDegree', [], ...
    'parameters', struct('k', 'num_modes'), ...
    'requires', ["Mass", "Stiffness"], ...
    'function', @bct.eigenpairs.fromFEM, ...
    'purity', "pure", ...
    'description', "Solve Laplace-Beltrami eigenproblem");

specs.eigenpairs_validate = struct(...
    'id', "eigenpairs_validate", ...
    'name', "Validate Eigenpairs", ...
    'domain', "spectral", ...
    'representation', "bct.Eigenpairs", ...
    'inputType', "eigenpairs", ...
    'outputType', "boolean", ...
    'formDegree', [], ...
    'parameters', struct(), ...
    'requires', ["Eigenvalues", "Eigenvectors", "MassMatrix"], ...
    'function', @bct.eigenpairs.validate, ...
    'purity', "pure", ...
    'description', "Check invariants and orthonormality");

specs.eigenpairs_merge = struct(...
    'id', "eigenpairs_merge", ...
    'name', "Merge Eigenpairs", ...
    'domain', "spectral", ...
    'representation', "bct.Eigenpairs", ...
    'inputType', "eigenpairs", ...
    'outputType', "eigenpairs", ...
    'formDegree', [], ...
    'parameters', struct('E2', 'second_eigenpairs'), ...
    'requires', ["ManifoldID"], ...
    'function', @bct.eigenpairs.merge, ...
    'purity', "pure", ...
    'description', "Combine two eigenpair sets");

specs.eigenpairs_reorder = struct(...
    'id', "eigenpairs_reorder", ...
    'name', "Reorder Eigenpairs", ...
    'domain', "spectral", ...
    'representation', "bct.Eigenpairs", ...
    'inputType', "eigenpairs", ...
    'outputType', "eigenpairs", ...
    'formDegree', [], ...
    'parameters', struct('ordering', 'ascending|descending|indices'), ...
    'requires', ["Eigenvalues"], ...
    'function', @bct.eigenpairs.reorder, ...
    'purity', "pure", ...
    'description', "Change eigenvalue ordering");

%% ========================================================================
%% DEC OPERATORS (Tier 1: Representation-bound - Exterior Calculus)
%% ========================================================================

% Primitive accessors (pass-throughs to backend)

specs.dec_d0 = struct(...
    'id', "dec_d0", ...
    'name', "Exterior Derivative (0→1)", ...
    'domain', "dec", ...
    'representation', "bct.DEC", ...
    'inputType', "operator", ...
    'outputType', "operator", ...
    'formDegree', 0, ...
    'parameters', struct(), ...
    'requires', ["d0"], ...
    'function', @bct.dec.d0, ...
    'purity', "pure", ...
    'description', "Exterior derivative mapping 0-forms to 1-forms");

specs.dec_d1 = struct(...
    'id', "dec_d1", ...
    'name', "Exterior Derivative (1→2)", ...
    'domain', "dec", ...
    'representation', "bct.DEC", ...
    'inputType', "operator", ...
    'outputType', "operator", ...
    'formDegree', 1, ...
    'parameters', struct(), ...
    'requires', ["d1"], ...
    'function', @bct.dec.d1, ...
    'purity', "pure", ...
    'description', "Exterior derivative mapping 1-forms to 2-forms");

specs.dec_star0 = struct(...
    'id', "dec_star0", ...
    'name', "Hodge Star (0-form)", ...
    'domain', "dec", ...
    'representation', "bct.DEC", ...
    'inputType', "operator", ...
    'outputType', "operator", ...
    'formDegree', 0, ...
    'parameters', struct(), ...
    'requires', ["hd0"], ...
    'function', @bct.dec.star0, ...
    'purity', "pure", ...
    'description', "Hodge star operator for 0-forms");

specs.dec_star1 = struct(...
    'id', "dec_star1", ...
    'name', "Hodge Star (1-form)", ...
    'domain', "dec", ...
    'representation', "bct.DEC", ...
    'inputType', "operator", ...
    'outputType', "operator", ...
    'formDegree', 1, ...
    'parameters', struct(), ...
    'requires', ["hd1"], ...
    'function', @bct.dec.star1, ...
    'purity', "pure", ...
    'description', "Hodge star operator for 1-forms");

specs.dec_star2 = struct(...
    'id', "dec_star2", ...
    'name', "Hodge Star (2-form)", ...
    'domain', "dec", ...
    'representation', "bct.DEC", ...
    'inputType', "operator", ...
    'outputType', "operator", ...
    'formDegree', 2, ...
    'parameters', struct(), ...
    'requires', ["hd2"], ...
    'function', @bct.dec.star2, ...
    'purity', "pure", ...
    'description', "Hodge star operator for 2-forms");

% Core DEC operators

specs.dec_gradient = struct(...
    'id', "dec_gradient", ...
    'name', "Gradient", ...
    'domain', "dec", ...
    'representation', "bct.DEC", ...
    'inputType', "0-form", ...
    'outputType', "1-form", ...
    'formDegree', 0, ...
    'parameters', struct(), ...
    'requires', ["d0"], ...
    'function', @bct.dec.gradient, ...
    'purity', "pure", ...
    'description', "Gradient of scalar field");

specs.dec_divergence = struct(...
    'id', "dec_divergence", ...
    'name', "Divergence", ...
    'domain', "dec", ...
    'representation', "bct.DEC", ...
    'inputType', "1-form", ...
    'outputType', "0-form", ...
    'formDegree', 1, ...
    'parameters', struct(), ...
    'requires', ["d0", "hd1"], ...
    'function', @bct.dec.divergence, ...
    'purity', "pure", ...
    'description', "Divergence of vector field");

specs.dec_curl = struct(...
    'id', "dec_curl", ...
    'name', "Curl", ...
    'domain', "dec", ...
    'representation', "bct.DEC", ...
    'inputType', "1-form", ...
    'outputType', "2-form", ...
    'formDegree', 1, ...
    'parameters', struct(), ...
    'requires', ["d1"], ...
    'function', @bct.dec.curl, ...
    'purity', "pure", ...
    'description', "Curl of vector field");

% Laplacian operators

specs.dec_laplacian0 = struct(...
    'id', "dec_laplacian0", ...
    'name', "0-form Laplacian", ...
    'domain', "dec", ...
    'representation', "bct.DEC", ...
    'inputType', "operator", ...
    'outputType', "operator", ...
    'formDegree', 0, ...
    'parameters', struct(), ...
    'requires', ["d0", "hd1"], ...
    'function', @bct.dec.laplacian0, ...
    'purity', "pure", ...
    'description', "Scalar Laplacian on vertices");

specs.dec_laplacian1 = struct(...
    'id', "dec_laplacian1", ...
    'name', "1-form Laplacian", ...
    'domain', "dec", ...
    'representation', "bct.DEC", ...
    'inputType', "operator", ...
    'outputType', "operator", ...
    'formDegree', 1, ...
    'parameters', struct(), ...
    'requires', ["d0", "d1", "hd0", "hd1", "hd2"], ...
    'function', @bct.dec.laplacian1, ...
    'purity', "pure", ...
    'description', "Vector Laplacian on edges");

specs.dec_laplacian2 = struct(...
    'id', "dec_laplacian2", ...
    'name', "2-form Laplacian", ...
    'domain', "dec", ...
    'representation', "bct.DEC", ...
    'inputType', "operator", ...
    'outputType', "operator", ...
    'formDegree', 2, ...
    'parameters', struct(), ...
    'requires', ["d1", "hd1", "hd2"], ...
    'function', @bct.dec.laplacian2, ...
    'purity', "pure", ...
    'description', "Density Laplacian on faces");

% Spectral solver

specs.dec_eigensolve = struct(...
    'id', "dec_eigensolve", ...
    'name', "DEC Eigensolve", ...
    'domain', "dec", ...
    'representation', "bct.DEC", ...
    'inputType', "operator", ...
    'outputType', "eigenpairs", ...
    'formDegree', [], ...
    'parameters', struct('formDegree', 'integer', 'k', 'integer'), ...
    'requires', ["laplacian", "hodge_star"], ...
    'function', @bct.dec.eigensolve, ...
    'purity', "pure", ...
    'description', "Compute eigenpairs for specified form degree");

end
