function defs = defs()
%BCT.REGISTRY.BRUSHES.DEFS  Authoritative brush definitions registry
%
%   defs = bct.registry.brushes.defs()
%
% Purpose:
%   Single source of truth for all brush specifications in BCT.
%   This is the canonical registry - all other brush functions must
%   delegate to this.
%
% Output:
%   defs - struct array (1×K) with required fields:
%          Id            (string): unique canonical identifier
%          Category      (string): "patch"|"trajectory"|"time"|"dynamic"
%          AxisKinds     (string array): ["spatial"|"spatiotemporal"]
%          ParamNames    (string array): parameter names
%          DefaultParams (function_handle): @(manifold)->struct
%          ParamRanges   (function_handle): @(manifold)->struct
%          Evaluate      (function_handle): @(manifold,params)->w
%
%          Optional fields:
%          Name          (string): display name
%          Tags          (string array): classification tags
%          Requires      (string array): representation requirements
%          OutputDims    (string): "spatial"|"spatiotemporal"
%          Description   (string): human-readable description
%
% Contract:
%   - Evaluate(manifold, params) is the canonical signature
%   - DefaultParams(manifold) returns struct with all ParamNames
%   - ParamRanges(manifold) returns validation structs
%   - Registry must be deterministic
%
% See also: bct.registry.brushes.schema, bct.registry.brushes.validate

    % Initialize empty struct array with proper field order
    defs = initializeEmpty();
    
    %% =========================================================
    % PATCH BRUSHES (Unordered spatial selections)
    %% =========================================================
    
    defs(end+1) = definePatchNearest();
    defs(end+1) = definePatchGaussian();
    defs(end+1) = definePatchSpectral();
    
    %% =========================================================
    % TRAJECTORY BRUSHES (Ordered spatial paths)
    %% =========================================================
    
    defs(end+1) = defineTrajectoryGeodesic();
    defs(end+1) = defineTrajectoryGaussian();
    defs(end+1) = defineTrajectorySpectral();
    
    %% =========================================================
    % TIME BRUSHES (Spatiotemporal patterns)
    %% =========================================================
    
    defs(end+1) = defineTimeHeat();
    defs(end+1) = defineTimeSpectral();
    
    % NOTE: Validation is NOT called here to avoid expensive operations
    % Call bct.registry.brushes.validate(defs) explicitly if needed
end

%% =========================================================
%% INITIALIZATION HELPER
%% =========================================================

function defs = initializeEmpty()
    % Create empty struct with proper field order
    defs = struct(...
        'Id', [], ...
        'Category', [], ...
        'AxisKinds', [], ...
        'ParamNames', [], ...
        'DefaultParams', [], ...
        'ParamRanges', [], ...
        'Evaluate', [], ...
        'Name', [], ...
        'Tags', [], ...
        'Requires', [], ...
        'OutputDims', [], ...
        'Description', [] ...
    );
    defs = defs([]);  % Make 0×1 empty
end

%% =========================================================
%% PATCH BRUSH DEFINITIONS
%% =========================================================

function spec = definePatchNearest()
    spec = struct(...
        'Id',           "patch_nearest", ...
        'Category',     "patch", ...
        'AxisKinds',    ["spatial"], ...
        'ParamNames',   ["seed", "distance", "metric"], ...
        'DefaultParams', @defaultParamsPatchNearest, ...
        'ParamRanges',  @paramRangesPatchNearest, ...
        'Evaluate',     @bct.brush.patch.nearest, ...
        'Name',         "Nearest-neighbor Patch", ...
        'Tags',         ["geometric", "binary", "distance-based"], ...
        'Requires',     ["Graph"], ...
        'OutputDims',   "spatial", ...
        'Description',  "Binary selection of vertices within distance threshold" ...
    );
end

function p = defaultParamsPatchNearest(manifold)
    charLength = computeCharacteristicLength(manifold);
    p = struct(...
        'seed',     round(manifold.numVertices() / 2), ...
        'distance', 0.05 * charLength, ...
        'metric',   "geometry" ...
    );
end

function r = paramRangesPatchNearest(manifold)
    charLength = computeCharacteristicLength(manifold);
    r = struct(...
        'seed',     struct('type', 'integer', 'range', [1, manifold.numVertices()]), ...
        'distance', struct('type', 'numeric', 'range', [0.001, 1.0] * charLength), ...
        'metric',   struct('type', 'string', 'values', ["geometry", "fem"]) ...
    );
end

function spec = definePatchGaussian()
    spec = struct(...
        'Id',           "patch_gaussian", ...
        'Category',     "patch", ...
        'AxisKinds',    ["spatial"], ...
        'ParamNames',   ["source", "sigma", "metric"], ...
        'DefaultParams', @defaultParamsPatchGaussian, ...
        'ParamRanges',  @paramRangesPatchGaussian, ...
        'Evaluate',     @bct.brush.patch.gaussian, ...
        'Name',         "Gaussian Patch", ...
        'Tags',         ["geometric", "smooth", "distance-based"], ...
        'Requires',     ["Graph"], ...
        'OutputDims',   "spatial", ...
        'Description',  "Gaussian-weighted spatial selection centered at source vertex" ...
    );
end

function p = defaultParamsPatchGaussian(manifold)
    charLength = computeCharacteristicLength(manifold);
    p = struct(...
        'source', round(manifold.numVertices() / 2), ...
        'sigma',  0.05 * charLength, ...
        'metric', "geometry" ...
    );
end

function r = paramRangesPatchGaussian(manifold)
    charLength = computeCharacteristicLength(manifold);
    r = struct(...
        'source', struct('type', 'integer', 'range', [1, manifold.numVertices()]), ...
        'sigma',  struct('type', 'numeric', 'range', [0.001, 1.0] * charLength), ...
        'metric', struct('type', 'string', 'values', ["geometry", "fem"]) ...
    );
end

function spec = definePatchSpectral()
    spec = struct(...
        'Id',           "patch_spectral", ...
        'Category',     "patch", ...
        'AxisKinds',    ["spatial"], ...
        'ParamNames',   ["source", "kernel", "sigma", "bandwidth"], ...
        'DefaultParams', @defaultParamsPatchSpectral, ...
        'ParamRanges',  @paramRangesPatchSpectral, ...
        'Evaluate',     @bct.brush.patch.spectral, ...
        'Name',         "Spectral Patch", ...
        'Tags',         ["spectral", "smooth", "eigenmode"], ...
        'Requires',     ["FEM", "Eigenpairs"], ...
        'OutputDims',   "spatial", ...
        'Description',  "Spectral-filtered selection using eigenmodes" ...
    );
end

function p = defaultParamsPatchSpectral(manifold)
    numVerts = manifold.numVertices();
    p = struct(...
        'source',    round(numVerts / 2), ...
        'kernel',    "heat", ...
        'sigma',     10, ...
        'bandwidth', min(100, numVerts) ...
    );
end

function r = paramRangesPatchSpectral(manifold)
    numVerts = manifold.numVertices();
    r = struct(...
        'source',    struct('type', 'integer', 'range', [1, numVerts]), ...
        'kernel',    struct('type', 'string', 'values', ["heat", "gaussian", "lowpass", "bandpass"]), ...
        'sigma',     struct('type', 'numeric', 'range', [0.1, 100]), ...
        'bandwidth', struct('type', 'integer', 'range', [10, numVerts]) ...
    );
end

%% =========================================================
%% TRAJECTORY BRUSH DEFINITIONS
%% =========================================================

function spec = defineTrajectoryGeodesic()
    spec = struct(...
        'Id',           "trajectory_geodesic", ...
        'Category',     "trajectory", ...
        'AxisKinds',    ["spatial"], ...
        'ParamNames',   ["source", "target", "metric", "width"], ...
        'DefaultParams', @defaultParamsTrajectoryGeodesic, ...
        'ParamRanges',  @paramRangesTrajectoryGeodesic, ...
        'Evaluate',     @bct.brush.trajectory.geodesic, ...
        'Name',         "Geodesic Trajectory", ...
        'Tags',         ["geometric", "path", "shortest"], ...
        'Requires',     ["Graph"], ...
        'OutputDims',   "spatial", ...
        'Description',  "Shortest path between source and target vertices" ...
    );
end

function p = defaultParamsTrajectoryGeodesic(manifold)
    numVerts = manifold.numVertices();
    p = struct(...
        'source', round(numVerts * 0.25), ...
        'target', round(numVerts * 0.75), ...
        'metric', "geometry", ...
        'width',  0 ...
    );
end

function r = paramRangesTrajectoryGeodesic(manifold)
    numVerts = manifold.numVertices();
    charLength = computeCharacteristicLength(manifold);
    r = struct(...
        'source', struct('type', 'integer', 'range', [1, numVerts]), ...
        'target', struct('type', 'integer', 'range', [1, numVerts]), ...
        'metric', struct('type', 'string', 'values', ["geometry", "fem"]), ...
        'width',  struct('type', 'numeric', 'range', [0, 0.5] * charLength) ...
    );
end

function spec = defineTrajectoryGaussian()
    spec = struct(...
        'Id',           "trajectory_gaussian", ...
        'Category',     "trajectory", ...
        'AxisKinds',    ["spatial"], ...
        'ParamNames',   ["source", "target", "metric", "sigma"], ...
        'DefaultParams', @defaultParamsTrajectoryGaussian, ...
        'ParamRanges',  @paramRangesTrajectoryGaussian, ...
        'Evaluate',     @bct.brush.trajectory.gaussian, ...
        'Name',         "Gaussian Trajectory", ...
        'Tags',         ["geometric", "smooth", "path"], ...
        'Requires',     ["Graph"], ...
        'OutputDims',   "spatial", ...
        'Description',  "Gaussian-weighted path between source and target" ...
    );
end

function p = defaultParamsTrajectoryGaussian(manifold)
    numVerts = manifold.numVertices();
    charLength = computeCharacteristicLength(manifold);
    p = struct(...
        'source', round(numVerts * 0.25), ...
        'target', round(numVerts * 0.75), ...
        'metric', "geometry", ...
        'sigma',  0.05 * charLength ...
    );
end

function r = paramRangesTrajectoryGaussian(manifold)
    numVerts = manifold.numVertices();
    charLength = computeCharacteristicLength(manifold);
    r = struct(...
        'source', struct('type', 'integer', 'range', [1, numVerts]), ...
        'target', struct('type', 'integer', 'range', [1, numVerts]), ...
        'metric', struct('type', 'string', 'values', ["geometry", "fem"]), ...
        'sigma',  struct('type', 'numeric', 'range', [0.001, 1.0] * charLength) ...
    );
end

function spec = defineTrajectorySpectral()
    spec = struct(...
        'Id',           "trajectory_spectral", ...
        'Category',     "trajectory", ...
        'AxisKinds',    ["spatial"], ...
        'ParamNames',   ["source", "target", "kernel", "metric"], ...
        'DefaultParams', @defaultParamsTrajectorySpectral, ...
        'ParamRanges',  @paramRangesTrajectorySpectral, ...
        'Evaluate',     @bct.brush.trajectory.spectral, ...
        'Name',         "Spectral Trajectory", ...
        'Tags',         ["spectral", "smooth", "path"], ...
        'Requires',     ["FEM", "Eigenpairs", "Graph"], ...
        'OutputDims',   "spatial", ...
        'Description',  "Spectral-filtered path between source and target" ...
    );
end

function p = defaultParamsTrajectorySpectral(manifold)
    numVerts = manifold.numVertices();
    p = struct(...
        'source', round(numVerts * 0.25), ...
        'target', round(numVerts * 0.75), ...
        'kernel', "gaussian", ...
        'metric', "geometry" ...
    );
end

function r = paramRangesTrajectorySpectral(manifold)
    numVerts = manifold.numVertices();
    r = struct(...
        'source', struct('type', 'integer', 'range', [1, numVerts]), ...
        'target', struct('type', 'integer', 'range', [1, numVerts]), ...
        'kernel', struct('type', 'string', 'values', ["gaussian", "heat", "bandpass"]), ...
        'metric', struct('type', 'string', 'values', ["geometry", "fem"]) ...
    );
end

%% =========================================================
%% TIME BRUSH DEFINITIONS
%% =========================================================

function spec = defineTimeHeat()
    spec = struct(...
        'Id',           "time_heat", ...
        'Category',     "time", ...
        'AxisKinds',    ["spatiotemporal"], ...
        'ParamNames',   ["source", "target", "tau_range", "metric"], ...
        'DefaultParams', @defaultParamsTimeHeat, ...
        'ParamRanges',  @paramRangesTimeHeat, ...
        'Evaluate',     @evaluateTimeHeat, ...
        'Name',         "Heat Diffusion", ...
        'Tags',         ["spectral", "evolution", "diffusion"], ...
        'Requires',     ["FEM", "Eigenpairs", "Graph"], ...
        'OutputDims',   "spatiotemporal", ...
        'Description',  "Heat diffusion along trajectory over time" ...
    );
end

function w = evaluateTimeHeat(manifold, params)
    % Wrapper to convert 2-arg signature to 3-arg signature
    % Time axis is generated internally based on tau_range
    time = struct('N', 50);  % Default 50 time steps
    w = bct.brush.time.heat(manifold, time, params);
end

function p = defaultParamsTimeHeat(manifold)
    numVerts = manifold.numVertices();
    p = struct(...
        'source',    round(numVerts * 0.25), ...
        'target',    round(numVerts * 0.75), ...
        'tau_range', [0.01, 0.5], ...
        'metric',    "geometry" ...
    );
end

function r = paramRangesTimeHeat(manifold)
    numVerts = manifold.numVertices();
    r = struct(...
        'source',    struct('type', 'integer', 'range', [1, numVerts]), ...
        'target',    struct('type', 'integer', 'range', [1, numVerts]), ...
        'tau_range', struct('type', 'numeric', 'range', [0.001, 2.0], 'numel', 2), ...
        'metric',    struct('type', 'string', 'values', ["geometry", "fem"]) ...
    );
end

function spec = defineTimeSpectral()
    spec = struct(...
        'Id',           "time_spectral", ...
        'Category',     "time", ...
        'AxisKinds',    ["spatiotemporal"], ...
        'ParamNames',   ["source", "kernel"], ...
        'DefaultParams', @defaultParamsTimeSpectral, ...
        'ParamRanges',  @paramRangesTimeSpectral, ...
        'Evaluate',     @evaluateTimeSpectral, ...
        'Name',         "Time-varying Spectral", ...
        'Tags',         ["spectral", "evolution"], ...
        'Requires',     ["FEM", "Eigenpairs"], ...
        'OutputDims',   "spatiotemporal", ...
        'Description',  "Time-varying spectral patch at each time step" ...
    );
end

function w = evaluateTimeSpectral(manifold, params)
    % Wrapper to convert 2-arg signature to 3-arg signature
    time = struct('N', 50);  % Default 50 time steps
    w = bct.brush.time.spectral(manifold, time, params);
end

function p = defaultParamsTimeSpectral(manifold)
    numVerts = manifold.numVertices();
    p = struct(...
        'source', round(numVerts / 2), ...
        'kernel', "heat" ...
    );
end

function r = paramRangesTimeSpectral(manifold)
    numVerts = manifold.numVertices();
    r = struct(...
        'source', struct('type', 'integer', 'range', [1, numVerts]), ...
        'kernel', struct('type', 'string', 'values', ["heat", "gaussian", "bandpass"]) ...
    );
end

%% =========================================================
%% UTILITY FUNCTIONS
%% =========================================================

function L = computeCharacteristicLength(manifold)
    %COMPUTECHARACTERISTICLENGTH  Estimate mesh characteristic length
    %
    % Computes characteristic length from bounding box diagonal
    
    V = manifold.Vertices;
    bbox = max(V) - min(V);
    L = norm(bbox);
end
