function defs = colormapTable()
% Central registry of all built-in colormaps

defs = [

    % === SCALAR COLORMAPS ===
    struct( ...
        'Name', "viridis", ...
        'Category', bct.color.enum.ColormapCategory.Scalar, ...
        'Domain', [0 1], ...
        'Generator', @(N) viridis(N), ...
        'IsDiscrete', false, ...
        'IsDiverging', false ...
    )

    struct( ...
        'Name', "parula", ...
        'Category', bct.color.enum.ColormapCategory.Scalar, ...
        'Domain', [0 1], ...
        'Generator', @(N) parula(N), ...
        'IsDiscrete', false, ...
        'IsDiverging', false ...
    )

    struct( ...
        'Name', "magma", ...
        'Category', bct.color.enum.ColormapCategory.Scalar, ...
        'Domain', [0 1], ...
        'Generator', @(N) magma(N), ...
        'IsDiscrete', false, ...
        'IsDiverging', false ...
    )

    struct( ...
        'Name', "inferno", ...
        'Category', bct.color.enum.ColormapCategory.Scalar, ...
        'Domain', [0 1], ...
        'Generator', @(N) inferno(N), ...
        'IsDiscrete', false, ...
        'IsDiverging', false ...
    )

    struct( ...
        'Name', "plasma", ...
        'Category', bct.color.enum.ColormapCategory.Scalar, ...
        'Domain', [0 1], ...
        'Generator', @(N) plasma(N), ...
        'IsDiscrete', false, ...
        'IsDiverging', false ...
    )

    struct( ...
        'Name', "turbo", ...
        'Category', bct.color.enum.ColormapCategory.Scalar, ...
        'Domain', [0 1], ...
        'Generator', @(N) turbo(N), ...
        'IsDiscrete', false, ...
        'IsDiverging', false ...
    )

    struct( ...
        'Name', "hot", ...
        'Category', bct.color.enum.ColormapCategory.Scalar, ...
        'Domain', [0 1], ...
        'Generator', @(N) hot(N), ...
        'IsDiscrete', false, ...
        'IsDiverging', false ...
    )

    struct( ...
        'Name', "gray", ...
        'Category', bct.color.enum.ColormapCategory.Scalar, ...
        'Domain', [0 1], ...
        'Generator', @(N) gray(N), ...
        'IsDiscrete', false, ...
        'IsDiverging', false ...
    )

    % === DIVERGING COLORMAPS ===
    struct( ...
        'Name', "redblue", ...
        'Category', bct.color.enum.ColormapCategory.Diverging, ...
        'Domain', [-1 1], ...
        'Generator', @(N) redblueColormap(N), ...
        'IsDiscrete', false, ...
        'IsDiverging', true ...
    )

    struct( ...
        'Name', "coolwarm", ...
        'Category', bct.color.enum.ColormapCategory.Diverging, ...
        'Domain', [-1 1], ...
        'Generator', @(N) coolwarmColormap(N), ...
        'IsDiscrete', false, ...
        'IsDiverging', true ...
    )

    % === BINARY ===
    struct( ...
        'Name', "binaryMask", ...
        'Category', bct.color.enum.ColormapCategory.Binary, ...
        'Domain', [0 1], ...
        'Generator', @(~) [0 0 0; 1 1 1], ...
        'IsDiscrete', true, ...
        'IsDiverging', false ...
    )

    % === CYCLIC ===
    struct( ...
        'Name', "phaseCyclic", ...
        'Category', bct.color.enum.ColormapCategory.Cyclic, ...
        'Domain', [-pi pi], ...
        'Generator', @(N) hsv2rgb([linspace(0,1,N)' ones(N,1) ones(N,1)]), ...
        'IsDiscrete', false, ...
        'IsDiverging', false ...
    )

    struct( ...
        'Name', "twilight", ...
        'Category', bct.color.enum.ColormapCategory.Cyclic, ...
        'Domain', [-pi pi], ...
        'Generator', @(N) twilightColormap(N), ...
        'IsDiscrete', false, ...
        'IsDiverging', false ...
    )

    % === CATEGORICAL ===
    struct( ...
        'Name', "lines", ...
        'Category', bct.color.enum.ColormapCategory.Categorical, ...
        'Domain', [1 12], ...
        'Generator', @(N) lines(min(N,12)), ...
        'IsDiscrete', true, ...
        'IsDiverging', false ...
    )

    struct( ...
        'Name', "tab10", ...
        'Category', bct.color.enum.ColormapCategory.Categorical, ...
        'Domain', [1 10], ...
        'Generator', @(N) tab10Colormap(N), ...
        'IsDiscrete', true, ...
        'IsDiverging', false ...
    )

    % === VECTOR RGB (2D mappings) ===
    struct( ...
        'Name', "vectorHSV", ...
        'Category', bct.color.enum.ColormapCategory.VectorRGB, ...
        'Domain', [-pi, pi; 0, 1], ...  % Row 1: phase range, Row 2: amplitude range
        'Generator', @(N) vectorHSVColormap(N), ...
        'IsDiscrete', false, ...
        'IsDiverging', false ...
    )
];
end


%% Helper colormap generators

function C = redblueColormap(N)
    % Red-Blue diverging colormap (symmetric)
    t = linspace(-1, 1, N)';
    C = zeros(N, 3);
    
    % Blue for negative
    neg = t < 0;
    C(neg, 3) = abs(t(neg));
    
    % Red for positive
    pos = t > 0;
    C(pos, 1) = t(pos);
    
    % White at center
    center = (t >= -0.1) & (t <= 0.1);
    blend = 1 - abs(t(center)) / 0.1;
    C(center, :) = repmat(blend, 1, 3);
end

function C = coolwarmColormap(N)
    % Cool-Warm diverging (better perceptual uniformity than redblue)
    t = linspace(0, 1, N)';
    
    % Interpolate between cool (blue-cyan) and warm (yellow-red)
    cool = [59 76 192] / 255;
    neutral = [221 221 221] / 255;
    warm = [180 4 38] / 255;
    
    C = zeros(N, 3);
    mid = ceil(N/2);
    
    % Cool half
    for i = 1:3
        C(1:mid, i) = linspace(cool(i), neutral(i), mid)';
        C(mid:end, i) = linspace(neutral(i), warm(i), N-mid+1)';
    end
end

function C = twilightColormap(N)
    % Twilight cyclic colormap (perceptually uniform, zero at ends)
    % Approximation of matplotlib's twilight
    t = linspace(0, 1, N)';
    
    % Create smooth cyclic transition
    h = mod(t * 360 + 180, 360) / 360;  % Start at purple, cycle through blue-cyan-green-yellow-pink
    s = 0.75 + 0.25 * sin(2*pi*t);      % Varying saturation
    v = 0.6 + 0.4 * sin(2*pi*t - pi/2); % Varying value
    
    C = hsv2rgb([h, s, v]);
end

function C = tab10Colormap(N)
    % Tableau 10 categorical palette
    base = [
        31, 119, 180;   % Blue
        255, 127, 14;   % Orange
        44, 160, 44;    % Green
        214, 39, 40;    % Red
        148, 103, 189;  % Purple
        140, 86, 75;    % Brown
        227, 119, 194;  % Pink
        127, 127, 127;  % Gray
        188, 189, 34;   % Olive
        23, 190, 207    % Cyan
    ] / 255;
    
    % Repeat colors if N > 10
    if N <= 10
        C = base(1:N, :);
    else
        C = repmat(base, ceil(N/10), 1);
        C = C(1:N, :);
    end
end

function C = vectorHSVColormap(N)
    % Generate example NxN color wheel for vector_hsv visualization
    % This is a 2D colormap showing phase (hue) and amplitude (value)
    
    if nargin < 1 || isempty(N)
        N = 64;
    end
    
    % Create 2D grid of phase and amplitude
    [theta, rho] = meshgrid(linspace(-pi, pi, N), linspace(0, 1, N));
    
    % Use bct.color.vector_hsv to generate the color wheel
    RGB = bct.color.vector_hsv(rho, theta);
    
    % Flatten to Nx3 for registry (though this is really NxNx3)
    C = reshape(RGB, [], 3);
end
