% File Exchange function
G = build_icosphere(4, 1, 'laplacianType', "cotangent");   % ~5k verts
%% 

clear waves   % avoid leftovers from previous runs


tmpl = struct('fHz',[],'cycles',[],'normal',[],'t0',[],'dur',[], ...
              'tukeyAlpha',[],'A',[],'phi0',0, ...
              'beltSigmaDeg',[],'spotCenter',[],'spotSigmaDeg',[]);
waves = repmat(tmpl,1,2);

waves(1) = struct('fHz',5,'cycles',16,'normal',[0;0;1], ...
                  't0',0.5,'dur',2,'tukeyAlpha',0.5,'A',7.5, ...
                  'phi0',0,'beltSigmaDeg',18,'spotCenter',[],'spotSigmaDeg',12);
waves(1) = struct('fHz',5,'cycles',16,'normal',[0;0;1], ...
    't0',0.5,'dur',2,'tukeyAlpha',0.5,'A',7.5, 'phi0',0, ...
    'beltSigmaDeg',10, ...            % was 18 → tighter ribbon (≈ 0.35·λ for λ≈22.5°)
    'spotCenter',[0.1;0.1;0.1], ...        % pick a point on the great circle (any unit xyz)
    'spotSigmaDeg',90);              % keep a modest cap (≈ 0.5·λ)

waves(2) = struct('fHz',20,'cycles',64,'normal',[0.3;0.7;0.64], ...
                  't0',2.5,'dur',1,'tukeyAlpha',0.5,'A',6.2, ...
                  'phi0',pi/4,'beltSigmaDeg',12,'spotCenter',[],'spotSigmaDeg',[]);
% 20 Hz: LOCAL traveler
% 20 Hz: LOCAL traveler

% waves(1) = struct('fHz',20,'cycles',3,'normal',[0.3;0.7;0.64], ...
%     't0',0.5,'dur',1,'tukeyAlpha',0.5,'A',6.2,'phi0',pi/4, ...
%     'beltSigmaDeg',23, 'spotCenter',[0;1;0], 'spotSigmaDeg',6);
% 
% % 5 Hz: GLOBAL traveler
% waves(2) = struct('fHz',5,'cycles',16,'normal',[0;0;1], ...
%     't0',2.5,'dur',1,'tukeyAlpha',0.6,'A',7.5,'phi0',0, ...
%     'beltSigmaDeg',45, 'spotCenter',[], 'spotSigmaDeg',56);

T=800; Fs=200;
[X,t,meta] = generateSphereWave(G.V, T, Fs, waves);
%% 


% select parameters
framerate = 24;
spinAz =3; spinEl = 0;

% choose trace indices (e.g. evenly sample 512 vertices)
numTraces = size(X,1);
traceIdx = round(linspace(1, size(G.V,1), numTraces));

% optional display settings for imagesc
colorLimits = 1.05*[-max(abs(X(:))) max(abs(X(:)))]; % symmetric CL
cmap = 'bone';

% call exporter with imagesc on the right (sphere left, imagesc right)
exportIcosphereVideo(G.V, G.F, X, t, 'icosphere_waves.mp4', framerate, ...
    'Save', 0, ...
    'Title', '', ...
    'View', [30 -15], ...
    'SpinAzimuthDegPerSec', spinAz, ...
    'SpinElevationDegPerSec', spinEl, ...
    'Lighting', 'flat', ...
    'ShowColorbar', true, ...
    'Colormap', cmap, ...
    'ColorLimits', colorLimits, ...
    'EdgeColor', 'none', ...
    'EdgeAlpha', 0.25, ...
    'ShowTraces', true, ...
    'NumTraces', numTraces, ...
    'TraceIndices', traceIdx, ...
    'SpaceTimeMode', 'image', ...
    'FigurePosition', [1.6377e+03 627 911.3333 723.3333]);

%% 



% call exporter with imagesc on the right (sphere left, imagesc right)
exportIcosphereVideo(G.V, G.F, X, t, 'icosphere_waves.mp4', framerate, ...
    'Save', 0, ...
    'Title', 'Traveling Waves', ...
    'View', [30 -15], ...
    'SpinAzimuthDegPerSec', spinAz, ...
    'SpinElevationDegPerSec', spinEl, ...
    'Lighting', 'flat', ...
    'ShowColorbar', true, ...
    'Colormap', cmap, ...
    'ColorLimits', colorLimits, ...
    'EdgeColor', 'k', ...
    'EdgeAlpha', 0.25, ...
    'ShowTraces', false, ...
    'TimeText', true, ...
    'TimeTextPos', [1 1 1], ...
    'FigurePosition', [1.6377e+03 757 911.3333 593.3333]);

%% 
% Your mesh

% Ground-truth joint spectrum on the sphere (no GSP)
S = fft_icospheretime(G, X, Fs, 'Lmax', 40, 'NFFT', T, 'Detrend', true);

% Build a 2D spectrum from S (degree × frequency)
K1 = floor(S.params.NFFT/2)+1;               % one-sided
Fk = S.Pell_f(:,1:K1);                       % magnitude-like already
ax_cell = { sqrt((0:S.params.Lmax)'.*(1+(0:S.params.Lmax)')) / G.R * (2*pi), ... % rad/m (k = 2π*cycles/m)
            S.f(1:K1) };                     % Hz
%% 

info = struct('spacings', [NaN, 1/Fs]);      % only time spacing needed here
figure(2)
clf
plot_spacetime_spectrum(Fk, ax_cell, info, ...
    'Units','frequency', 'SpatialDims',1, 'InputKind','magnitude', ...
    'TimePosOnly',true, 'LogMag',true, 'Colormap','bone', ...
    'Title','Sphere joint spectrum (degree-collapsed)');

