%% Demo: Using D3.js BaseScrubber Component from MATLAB
% This example demonstrates how to integrate the D3.js BaseScrubber 
% with MATLAB using the HTML UI Component for interactive signal interval selection.

%% Setup
clear; close all;
bioctree_start;

%% Create a simple HTML UI with BaseScrubber
fig = uifigure('Name', 'D3.js BaseScrubber Demo', 'Position', [100 100 800 600]);

% Create HTML UI Component
html = uihtml(fig, 'Position', [20 350 760 200]);

% Get the correct path to bct-ui.js
projectRoot = fileparts(fileparts(mfilename('fullpath'))); % Go up from examples/ to root
jsPath = fullfile(projectRoot, 'ui', 'tailwind', 'dist', 'bct-ui.js');
jsPath = strrep(jsPath, '\', '/'); % Convert to forward slashes

% HTML content with BaseScrubber
htmlContent = sprintf(['<!DOCTYPE html>' ...
    '<html>' ...
    '<head>' ...
    '    <meta charset="UTF-8">' ...
    '    <script src="file:///%s"></script>' ...
    '    <style>' ...
    '        body { margin: 20px; font-family: Arial, sans-serif; }' ...
    '        .scrubber-container { margin: 20px 0; }' ...
    '        .scrubber-label { font-weight: bold; margin-bottom: 10px; color: #374151; }' ...
    '    </style>' ...
    '</head>' ...
    '<body>' ...
    '    <div class="scrubber-container">' ...
    '        <div class="scrubber-label">Time Interval Selector (0-2 seconds)</div>' ...
    '        <div id="timeScrubber"></div>' ...
    '    </div>' ...
    '    <script>' ...
    '        // Wait for BCT to be available' ...
    '        if (typeof BCT === "undefined") {' ...
    '            document.body.innerHTML = "<div style=\"color:red;padding:20px;\">Error: BCT library not loaded. Path: %s</div>";' ...
    '        } else {' ...
    '            // Initialize BaseScrubber' ...
    '            const scrubber = new BCT.BaseScrubber("#timeScrubber", {' ...
    '                axisMin: 0,' ...
    '                axisMax: 2,' ...
    '                center: 1.0,' ...
    '                width: 0.4,' ...
    '                snapThreshold: 0.05,' ...
    '                tickFormatter: (d) => d.toFixed(2) + "s"' ...
    '            });' ...
    '' ...
    '            // Listen for scrubber changes and send to MATLAB' ...
    '            scrubber.state.subscribe("center", (center) => {' ...
    '                const width = scrubber.state.get("width");' ...
    '                const tMin = center - width/2;' ...
    '                const tMax = center + width/2;' ...
    '                if (window.setup && window.setup.DataChangedFcn) {' ...
    '                    window.setup.DataChangedFcn({' ...
    '                        type: "intervalChanged",' ...
    '                        center: center,' ...
    '                        width: width,' ...
    '                        tMin: tMin,' ...
    '                        tMax: tMax' ...
    '                    });' ...
    '                }' ...
    '            });' ...
    '' ...
    '            scrubber.state.subscribe("width", (width) => {' ...
    '                const center = scrubber.state.get("center");' ...
    '                const tMin = center - width/2;' ...
    '                const tMax = center + width/2;' ...
    '                if (window.setup && window.setup.DataChangedFcn) {' ...
    '                    window.setup.DataChangedFcn({' ...
    '                        type: "intervalChanged",' ...
    '                        center: center,' ...
    '                        width: width,' ...
    '                        tMin: tMin,' ...
    '                        tMax: tMax' ...
    '                    });' ...
    '                }' ...
    '            });' ...
    '        }' ...
    '    </script>' ...
    '</body>' ...
    '</html>'], ...
    jsPath, jsPath);

html.HTMLSource = htmlContent;

% Create text display for showing current values
valueText = uitextarea(fig, ...
    'Position', [20 250 760 80], ...
    'Value', 'Adjust the scrubber above to see values update here...', ...
    'Editable', 'off');

% Create axes for visualization
ax = uiaxes(fig, 'Position', [20 20 760 200]);
xlabel(ax, 'Time (s)');
ylabel(ax, 'Signal');
title(ax, 'Signal with Selected Interval');

%% Generate sample signal
t = linspace(0, 2, 1000);
signal = sin(2*pi*3*t) + 0.5*sin(2*pi*7*t) + 0.2*randn(size(t));

% Plot signal
hold(ax, 'on');
plot(ax, t, signal, 'b-', 'LineWidth', 1);

% Initialize interval visualization
intervalPatch = patch(ax, [0.8 1.2 1.2 0.8], ...
    [min(signal) min(signal) max(signal) max(signal)], ...
    'r', 'FaceAlpha', 0.2, 'EdgeColor', 'none');

hold(ax, 'off');
grid(ax, 'on');

%% Setup callback for scrubber changes
html.DataChangedFcn = @(src, event) updateVisualization(event.Data, valueText, intervalPatch, ax);

%% Callback function
function updateVisualization(data, valueText, intervalPatch, ax)
    % Extract values from scrubber
    center = data.center;
    width = data.width;
    tMin = data.tMin;
    tMax = data.tMax;
    
    % Update text display
    valueText.Value = {
        sprintf('Interval Center: %.3f s', center)
        sprintf('Interval Width:  %.3f s', width)
        sprintf('Time Range:      [%.3f, %.3f] s', tMin, tMax)
        ''
        'Use this interval for signal processing, filtering, or analysis...'
    };
    
    % Update visualization
    yLim = ax.YLim;
    intervalPatch.XData = [tMin tMax tMax tMin];
    intervalPatch.YData = [yLim(1) yLim(1) yLim(2) yLim(2)];
    
    % Optional: Update title with current selection
    title(ax, sprintf('Signal with Selected Interval [%.3f, %.3f] s', tMin, tMax));
end

%% Additional Example: Programmatically update scrubber from MATLAB
% You can also send data TO the scrubber from MATLAB

% Create button to set a specific interval
btn = uibutton(fig, 'Position', [20 570 150 22], ...
    'Text', 'Set Interval [0.5, 1.0]', ...
    'ButtonPushedFcn', @(~,~) setInterval(html, 0.75, 0.5));

function setInterval(html, newCenter, newWidth)
    % Send new values to the scrubber via JavaScript
    jsCommand = sprintf(['scrubber.state.set("center", %f);' ...
                         'scrubber.state.set("width", %f);'], ...
                         newCenter, newWidth);
    html.Data = struct('command', 'eval', 'code', jsCommand);
end

%% Notes:
% 1. The BaseScrubber automatically handles:
%    - Mouse dragging and interaction
%    - Snapping to grid points
%    - Smooth transitions
%    - Symmetric/asymmetric resizing
%
% 2. State updates are reactive - changes propagate automatically
%
% 3. You can use multiple scrubbers for different domains:
%    - Time domain: seconds
%    - Frequency domain: Hz
%    - Spatial domain: eigenvalues (lambda)
%
% 4. The scrubber integrates seamlessly with bct.Signal objects
%    for filtering and analysis operations
