%% Simple Test: Load D3.js BaseScrubber in MATLAB Figure
% Minimal script to verify D3.js component renders correctly

clear; close all;

%% Create figure with HTML component
fig = uifigure('Name', 'D3.js Scrubber Test', 'Position', [100 100 800 300]);

% Create HTML UI Component
html = uihtml(fig, 'Position', [20 20 760 260]);

%% Build absolute path to bct-ui.js
% Get project root (two levels up from examples/)
scriptPath = fileparts(mfilename('fullpath'));
projectRoot = pwd;
jsFilePath = fullfile(projectRoot, 'ui', 'tailwind', 'dist', 'bct-ui.js');

% Convert to forward slashes for file:// URL
jsFilePath = strrep(jsFilePath, '\', '/');

% Verify file exists
if ~isfile(jsFilePath)
    error('Cannot find bct-ui.js at: %s', jsFilePath);
else
    fprintf('Loading JavaScript from: %s\n', jsFilePath);
end

%% Create minimal HTML with scrubber
htmlContent = sprintf(['<!DOCTYPE html>' ...
    '<html>' ...
    '<head>' ...
    '    <meta charset="UTF-8">' ...
    '    <script src="file:///%s"></script>' ...
    '    <style>' ...
    '        * { box-sizing: border-box; }' ...
    '        body {' ...
    '            margin: 0;' ...
    '            padding: 20px;' ...
    '            font-family: Arial, sans-serif;' ...
    '            background-color: #f3f4f6;' ...
    '        }' ...
    '        h3 {' ...
    '            color: #1f2937;' ...
    '            margin: 0 0 20px 0;' ...
    '            font-size: 16px;' ...
    '        }' ...
    '        #scrubber {' ...
    '            background: white;' ...
    '            padding: 20px;' ...
    '            border-radius: 8px;' ...
    '            border: 1px solid #e5e7eb;' ...
    '            width: 100%%;' ...
    '            min-height: 150px;' ...
    '        }' ...
    '        #status {' ...
    '            margin-top: 15px;' ...
    '            padding: 10px;' ...
    '            background: #f0fdf4;' ...
    '            border: 1px solid #bbf7d0;' ...
    '            border-radius: 4px;' ...
    '            font-size: 12px;' ...
    '            color: #166534;' ...
    '            font-family: monospace;' ...
    '        }' ...
    '        .error {' ...
    '            background: #fef2f2 !important;' ...
    '            border-color: #fecaca !important;' ...
    '            color: #991b1b !important;' ...
    '        }' ...
    '        #debug {' ...
    '            margin-top: 10px;' ...
    '            padding: 10px;' ...
    '            background: #eff6ff;' ...
    '            border: 1px solid #bfdbfe;' ...
    '            border-radius: 4px;' ...
    '            font-size: 11px;' ...
    '            color: #1e40af;' ...
    '            font-family: monospace;' ...
    '            white-space: pre-wrap;' ...
    '        }' ...
    '    </style>' ...
    '</head>' ...
    '<body>' ...
    '    <h3>D3.js BaseScrubber Component Test</h3>' ...
    '    <div id="scrubber"></div>' ...
    '    <div id="status">Initializing...</div>' ...
    '    <div id="debug"></div>' ...
    '    <script>' ...
    '        const statusDiv = document.getElementById("status");' ...
    '        const debugDiv = document.getElementById("debug");' ...
    '        const scrubberDiv = document.getElementById("scrubber");' ...
    '        ' ...
    '        function updateStatus(msg, isError) {' ...
    '            statusDiv.textContent = msg;' ...
    '            if (isError) {' ...
    '                statusDiv.classList.add("error");' ...
    '            } else {' ...
    '                statusDiv.classList.remove("error");' ...
    '            }' ...
    '        }' ...
    '        ' ...
    '        function addDebug(msg) {' ...
    '            debugDiv.textContent += msg + "\\n";' ...
    '        }' ...
    '        ' ...
    '        // Log initial state' ...
    '        addDebug("Container width: " + scrubberDiv.offsetWidth + "px");' ...
    '        addDebug("Container height: " + scrubberDiv.offsetHeight + "px");' ...
    '        addDebug("BCT defined: " + (typeof BCT !== "undefined"));' ...
    '        addDebug("BCT.BaseScrubber: " + (typeof BCT !== "undefined" ? typeof BCT.BaseScrubber : "N/A"));' ...
    '        ' ...
    '        // Check if BCT library loaded' ...
    '        if (typeof BCT === "undefined") {' ...
    '            updateStatus("ERROR: BCT library not loaded", true);' ...
    '            addDebug("ERROR: BCT is undefined");' ...
    '        } else if (typeof BCT.BaseScrubber === "undefined") {' ...
    '            updateStatus("ERROR: BCT.BaseScrubber not found", true);' ...
    '            addDebug("ERROR: BCT.BaseScrubber is undefined");' ...
    '            addDebug("Available in BCT: " + Object.keys(BCT).join(", "));' ...
    '        } else {' ...
    '            updateStatus("BCT library loaded, creating scrubber...");' ...
    '            addDebug("Creating scrubber...");' ...
    '            ' ...
    '            // Create scrubber with delay' ...
    '            setTimeout(() => {' ...
    '                try {' ...
    '                    addDebug("Before new BaseScrubber()");' ...
    '                    const scrubber = new BCT.BaseScrubber("#scrubber", {' ...
    '                        axisMin: 0,' ...
    '                        axisMax: 1,' ...
    '                        center: 0.5,' ...
    '                        width: 0.2,' ...
    '                        tickFormatter: (d) => d.toFixed(2)' ...
    '                    });' ...
    '                    addDebug("After new BaseScrubber()");' ...
    '                    addDebug("SVG elements: " + scrubberDiv.querySelectorAll("svg").length);' ...
    '                    addDebug("SVG width: " + (scrubberDiv.querySelector("svg") ? scrubberDiv.querySelector("svg").getAttribute("width") : "N/A"));' ...
    '                    updateStatus("✓ Scrubber created! Try dragging the selection.");' ...
    '                    ' ...
    '                    // Subscribe to changes' ...
    '                    scrubber.state.subscribe("center", (val) => {' ...
    '                        const width = scrubber.state.get("width");' ...
    '                        updateStatus(`✓ Center: ${val.toFixed(3)}, Width: ${width.toFixed(3)}`);' ...
    '                    });' ...
    '                } catch(error) {' ...
    '                    updateStatus("ERROR: " + error.message, true);' ...
    '                    addDebug("ERROR: " + error.message);' ...
    '                    addDebug("Stack: " + error.stack);' ...
    '                }' ...
    '            }, 100);' ...
    '        }' ...
    '    </script>' ...
    '</body>' ...
    '</html>'], jsFilePath, jsFilePath);

%% Load HTML into component
html.HTMLSource = htmlContent;

fprintf('Figure created. Check if scrubber appears.\n');
fprintf('If you see a red error message, the JavaScript file failed to load.\n');
