function style = defaults(varargin)
%BCT.UI.MANIFOLD.DEFAULTS  Default rendering style spec for bct.ui.Manifold
%
%   style = bct.ui.manifold.defaults()
%   style = bct.ui.manifold.defaults(Name,Value,...)
%
% Name-Value (optional)
%   "Layout"   - struct of layout overrides
%   "Axes"     - struct of axes overrides
%   "Patch"    - struct of patch overrides
%   "Lights"   - struct of lighting overrides
%   "Overlays" - struct of overlay overrides (quiver/markers)
%
% Notes
%   - Pure function: returns a style spec; does not touch graphics.
%   - Intended for consumption by bct.ui.manifold.applyDefaults.

    % Canonical defaults (single source of truth)
    style = localBuiltin();

    if nargin > 0
        style = bct.ui.manifold.mergeStyle(style, varargin{:});
    end
end

function style = localBuiltin()
    style = struct();

    % Layout / container styling
    style.Layout = struct( ...
        "GridBackgroundColor", "k", ...
        "GridPadding", 0, ...
        "GridRowSpacing", 0, ...
        "GridColumnSpacing", 0);

    % Axes "canvas" defaults
    style.Axes = struct( ...
        "Color", "k", ...
        "Visible", "off", ...
        "Clipping", "off", ...
        "Projection", "orthographic", ...
        "AxisMode", "vis3d", ...
        "DisableInteractivity", true, ...
        "HideToolbar", true, ...
        "LockCamera", true);

    % Patch styling (do NOT set Vertices/Faces/FaceColor here)
    style.Patch = struct( ...
        "EdgeColor", "none", ...
        "FaceLighting", "gouraud", ...
        "PickableParts", "visible", ...
        "HitTest", "on", ...
        "AmbientStrength", 0.15, ...
        "DiffuseStrength", 0.70, ...
        "SpecularStrength", 0.05, ...
        "SpecularExponent", 35, ...
        "BackFaceLighting", "reverselit");

    % Lighting
    style.Lights = struct( ...
        "ClearExisting", true, ...
        "KeyType", "headlight", ...
        "FillType", "right", ...
        "FillColor", [0.15 0.15 0.15], ...
        "FillPositionScale", [1 -1 1], ...
        "ShadingModel", "gouraud");

    % Overlays
    style.Overlays = struct();
    style.Overlays.Quiver = struct( ...
        "Color", "w", ...
        "LineWidth", 1.5, ...
        "Visible", "off");

    style.Overlays.SeedMarker = struct( ...
        "Marker", "o", ...
        "Color", "r", ...
        "LineWidth", 2, ...
        "Visible", "off");

    style.Overlays.TargetMarker = struct( ...
        "Marker", "o", ...
        "Color", "y", ...
        "LineWidth", 2, ...
        "Visible", "off");
end
