function s = schema()
%SCHEMA Schema definition for bct.manifold.topology
%
% Syntax:
%   s = bct.manifold.topology.schema()
%
% Outputs:
%   s - Schema structure with fields:
%     .group      - Group metadata for HDF5/Zarr
%     .dimensions - Dimension scales
%     .datasets   - Dataset specifications
%
% Description:
%   Defines the structure for complete topological connectivity including
%   halfedge navigation, edges, and adjacency following HDF5/Zarr conventions.
%
% See also: bct.manifold.topology

% Initialize schema structure
s = struct();

%% Group metadata
s.group = struct();
s.group.name = 'topology';
s.group.path = 'topology';
s.group.schema = 'bct.manifold.topology@1.0.0';

% Group-level attributes
s.group.attributes = struct();
s.group.attributes.schema = 'bct.manifold.topology@1.0.0';
s.group.attributes.package = 'bct.manifold.topology';
s.group.attributes.description = 'Complete topological connectivity (halfedge structure, edges, adjacency)';
s.group.attributes.convention = 'CCW orientation: h12->h23->h31->h12';
s.group.attributes.boundary_convention = 'twin=0 for boundary halfedges';

%% Dimensions
s.dimensions = containers.Map();

% numVertices
s.dimensions('numVertices') = struct(...
    'name', 'numVertices', ...
    'description', 'Number of vertices in the mesh', ...
    'length', [], ...
    'labels', [], ...
    'scale_path', '', ...
    'index_base', 1, ...
    'axis_type', 'index');

% numFaces
s.dimensions('numFaces') = struct(...
    'name', 'numFaces', ...
    'description', 'Number of faces in the mesh', ...
    'length', [], ...
    'labels', [], ...
    'scale_path', '', ...
    'index_base', 1, ...
    'axis_type', 'index');

% numHalfedges
s.dimensions('numHalfedges') = struct(...
    'name', 'numHalfedges', ...
    'description', 'Number of halfedges (3 * numFaces for triangular mesh)', ...
    'length', [], ...
    'labels', [], ...
    'scale_path', '', ...
    'index_base', 1, ...
    'axis_type', 'index');

% numEdges
s.dimensions('numEdges') = struct(...
    'name', 'numEdges', ...
    'description', 'Number of undirected edges', ...
    'length', [], ...
    'labels', [], ...
    'scale_path', '', ...
    'index_base', 1, ...
    'axis_type', 'index');

% faceVertices
s.dimensions('faceVertices') = struct(...
    'name', 'faceVertices', ...
    'description', 'Three vertices per triangular face', ...
    'length', 3, ...
    'labels', {{'v1', 'v2', 'v3'}}, ...
    'scale_path', '', ...
    'index_base', 1, ...
    'axis_type', 'label');

% edgeVertices
s.dimensions('edgeVertices') = struct(...
    'name', 'edgeVertices', ...
    'description', 'Two vertices per edge (sorted)', ...
    'length', 2, ...
    'labels', {{'v_min', 'v_max'}}, ...
    'scale_path', '', ...
    'index_base', 1, ...
    'axis_type', 'label');

%% Datasets
s.datasets = containers.Map();

% Dataset: tailVertex (tail vertices)
s.datasets('tailVertex') = struct(...
    'name', 'tailVertex', ...
    'path', 'topology/tailVertex', ...
    'shape', 'numHalfedges', ...
    'dims', {{'numHalfedges'}}, ...
    'dtype', struct('matlab', 'uint32', 'hdf5', 'H5T_NATIVE_UINT32', 'zarr', '<u4'), ...
    'attributes', struct('description', 'Tail vertex index of each halfedge', 'index_base', 1, 'computedBy', 'bct.manifold.topology.vertices'), ...
    'required', true);

% Dataset: headVertex (head vertices)
s.datasets('headVertex') = struct(...
    'name', 'headVertex', ...
    'path', 'topology/headVertex', ...
    'shape', 'numHalfedges', ...
    'dims', {{'numHalfedges'}}, ...
    'dtype', struct('matlab', 'uint32', 'hdf5', 'H5T_NATIVE_UINT32', 'zarr', '<u4'), ...
    'attributes', struct('description', 'Head vertex index of each halfedge', 'index_base', 1, 'computedBy', 'bct.manifold.topology.vertices'), ...
    'required', true);

% Dataset: face
s.datasets('face') = struct(...
    'name', 'face', ...
    'path', 'topology/face', ...
    'shape', 'numHalfedges', ...
    'dims', {{'numHalfedges'}}, ...
    'dtype', struct('matlab', 'uint32', 'hdf5', 'H5T_NATIVE_UINT32', 'zarr', '<u4'), ...
    'attributes', struct('description', 'Incident face index for each halfedge', 'index_base', 1, 'computedBy', 'bct.manifold.topology.faces'), ...
    'required', true);

% Dataset: next
s.datasets('next') = struct(...
    'name', 'next', ...
    'path', 'topology/next', ...
    'shape', 'numHalfedges', ...
    'dims', {{'numHalfedges'}}, ...
    'dtype', struct('matlab', 'uint32', 'hdf5', 'H5T_NATIVE_UINT32', 'zarr', '<u4'), ...
    'attributes', struct('description', 'Next halfedge around face (CCW)', 'index_base', 1, 'computedBy', 'bct.manifold.topology.circulation'), ...
    'required', true);

% Dataset: prev
s.datasets('prev') = struct(...
    'name', 'prev', ...
    'path', 'topology/prev', ...
    'shape', 'numHalfedges', ...
    'dims', {{'numHalfedges'}}, ...
    'dtype', struct('matlab', 'uint32', 'hdf5', 'H5T_NATIVE_UINT32', 'zarr', '<u4'), ...
    'attributes', struct('description', 'Previous halfedge around face (CCW)', 'index_base', 1, 'computedBy', 'bct.manifold.topology.circulation'), ...
    'required', true);

% Dataset: twin
s.datasets('twin') = struct(...
    'name', 'twin', ...
    'path', 'topology/twin', ...
    'shape', 'numHalfedges', ...
    'dims', {{'numHalfedges'}}, ...
    'dtype', struct('matlab', 'uint32', 'hdf5', 'H5T_NATIVE_UINT32', 'zarr', '<u4'), ...
    'attributes', struct('description', 'Opposite halfedge across undirected edge (0 if boundary)', 'index_base', 1, 'boundary_value', 0, 'computedBy', 'bct.manifold.topology.twins'), ...
    'required', true);

% Dataset: edge
s.datasets('edge') = struct(...
    'name', 'edge', ...
    'path', 'topology/edge', ...
    'shape', 'numHalfedges', ...
    'dims', {{'numHalfedges'}}, ...
    'dtype', struct('matlab', 'uint32', 'hdf5', 'H5T_NATIVE_UINT32', 'zarr', '<u4'), ...
    'attributes', struct('description', 'Undirected edge index for each halfedge', 'index_base', 1, 'computedBy', 'bct.manifold.topology.edgeIndices'), ...
    'required', true);

% Dataset: isBoundary
s.datasets('isBoundary') = struct(...
    'name', 'isBoundary', ...
    'path', 'topology/isBoundary', ...
    'shape', 'numHalfedges', ...
    'dims', {{'numHalfedges'}}, ...
    'dtype', struct('matlab', 'logical', 'hdf5', 'H5T_NATIVE_UINT8', 'zarr', '|b1'), ...
    'attributes', struct('description', 'Boundary flag (true if twin=0)', 'computedBy', 'derived'), ...
    'required', true);

% Dataset: edgeList (undirected edge list)
s.datasets('edgeList') = struct(...
    'name', 'edgeList', ...
    'path', 'topology/edgeList', ...
    'shape', 'numEdges × edgeVertices', ...
    'dims', {{'numEdges', 'edgeVertices'}}, ...
    'dtype', struct('matlab', 'uint32', 'hdf5', 'H5T_NATIVE_UINT32', 'zarr', '<u4'), ...
    'attributes', struct('description', 'Undirected edge list (sorted vertex indices)', 'index_base', 1, 'sorted', true, 'computedBy', 'bct.manifold.topology.edges'), ...
    'required', true);

% Dataset: faceHalfedges (face halfedges)
s.datasets('faceHalfedges') = struct(...
    'name', 'faceHalfedges', ...
    'path', 'topology/faceHalfedges', ...
    'shape', 'numFaces × faceVertices', ...
    'dims', {{'numFaces', 'faceVertices'}}, ...
    'dtype', struct('matlab', 'uint32', 'hdf5', 'H5T_NATIVE_UINT32', 'zarr', '<u4'), ...
    'attributes', struct('description', 'Halfedge indices per face [h12 h23 h31]', 'index_base', 1, 'convention', 'h12: v1->v2, h23: v2->v3, h31: v3->v1', 'computedBy', 'bct.manifold.topology.faceHalfedges'), ...
    'required', true);

% Dataset: faceNeighbors
s.datasets('faceNeighbors') = struct(...
    'name', 'faceNeighbors', ...
    'path', 'topology/faceNeighbors', ...
    'shape', 'numFaces × faceVertices', ...
    'dims', {{'numFaces', 'faceVertices'}}, ...
    'dtype', struct('matlab', 'int32', 'hdf5', 'H5T_NATIVE_INT32', 'zarr', '<i4'), ...
    'attributes', struct('description', 'Adjacent face indices (-1 for boundary)', 'index_base', 1, 'boundary_value', -1, 'computedBy', 'bct.manifold.topology.neighbors'), ...
    'required', true);

% Dataset: neighborEdge
s.datasets('neighborEdge') = struct(...
    'name', 'neighborEdge', ...
    'path', 'topology/neighborEdge', ...
    'shape', 'numFaces × faceVertices', ...
    'dims', {{'numFaces', 'faceVertices'}}, ...
    'dtype', struct('matlab', 'uint8', 'hdf5', 'H5T_NATIVE_UINT8', 'zarr', '|u1'), ...
    'attributes', struct('description', 'Local edge index (1..3) in neighbor face', 'index_base', 1, 'range', [1, 3], 'computedBy', 'bct.manifold.topology.neighbors'), ...
    'required', true);

% Dataset: adjacency (sparse adjacency matrix stored as COO format)
s.datasets('adjacency') = struct(...
    'name', 'adjacency', ...
    'path', 'topology/adjacency', ...
    'shape', 'numVertices × numVertices', ...
    'dims', {{'numVertices', 'numVertices'}}, ...
    'dtype', struct('matlab', 'logical', 'hdf5', 'H5T_NATIVE_UINT8', 'zarr', '|b1'), ...
    'attributes', struct('description', 'Sparse binary adjacency matrix', 'format', 'CSR', 'symmetric', true, 'computedBy', 'bct.manifold.topology.adjacency'), ...
    'required', true);

end
