function s = schema()
%SCHEMA Schema definition for bct.manifold.topology (delegates to canonical)
%
% Syntax:
%   s = bct.manifold.topology.schema()
%
% Outputs:
%   s - Schema structure with fields:
%     .canonical  - Reference to authoritative bct.schema.topology
%     .validate   - Validation function (delegates to canonical)
%     .make       - Creation function (delegates to canonical)
%
% Description:
%   This schema delegates to the canonical bct.schema.topology as the
%   authoritative source for topology structure validation. The canonical
%   schema defines the structure for edges, adjacency, and optional
%   halfedge connectivity with datasets using .value and .attributes.
%   
%   This delegation pattern ensures:
%     - Single source of truth (bct.schema.topology)
%     - Consistent validation across BCT
%     - Unified dataset/group patterns
%   
%   Future serialization metadata (HDF5/Zarr) will be added by bct.file
%   package using the canonical schema as the authority.
%
% Examples:
%   % Get canonical schema
%   s = bct.manifold.topology.schema();
%   canonical = s.canonical();
%
%   % Validate topology structure
%   topo = bct.manifold.topology(M);
%   isValid = s.validate(topo);
%
%   % Create schema-compliant structure
%   topo = s.make(M);
%
% See also: bct.schema.topology, bct.manifold.topology

% Initialize schema structure
s = struct();

%% Canonical Schema (Authoritative Source)
% All structural validation delegates to bct.schema.topology
s.canonical = @() bct.schema.topology();

%% Validation (Delegate to Canonical)
s.validate = @(topo, varargin) bct.schema.topology.validate(topo, varargin{:});

%% Creation (Delegate to Canonical)
s.make = @(M, varargin) bct.schema.topology.make(M, varargin{:});

%% Halfedge Structure Documentation
% The canonical schema covers edges and adjacency (required datasets).
% For applications needing full halfedge structure, the following
% additional datasets can be computed by bct.manifold.topology.halfedge():
%
%   - tailVertex [nH×1]: tail vertex of each halfedge
%   - headVertex [nH×1]: head vertex of each halfedge
%   - face [nH×1]: incident face for each halfedge
%   - next [nH×1]: next halfedge in CCW face circulation
%   - prev [nH×1]: previous halfedge in CCW face circulation
%   - twin [nH×1]: opposite halfedge (0 for boundary)
%   - edge [nH×1]: undirected edge index
%   - isBoundary [nH×1]: boundary flag
%
% These are optional extensions not enforced by the canonical schema.

end

% numVertices
s.dimensions('numVertices') = struct(...
    'name', 'numVertices', ...
    'description', 'Number of vertices in the mesh', ...
    'length', [], ...
    'labels', [], ...
    'scale_path', '', ...
    'index_base', 1, ...
    'axis_type', 'index');

% numFaces
s.dimensions('numFaces') = struct(...
    'name', 'numFaces', ...
    'description', 'Number of faces in the mesh', ...
    'length', [], ...
    'labels', [], ...
    'scale_path', '', ...
    'index_base', 1, ...
    'axis_type', 'index');

% numHalfedges
s.dimensions('numHalfedges') = struct(...
    'name', 'numHalfedges', ...
    'description', 'Number of halfedges (3 * numFaces for triangular mesh)', ...
    'length', [], ...
    'labels', [], ...
    'scale_path', '', ...
    'index_base', 1, ...
    'axis_type', 'index');

% numEdges
s.dimensions('numEdges') = struct(...
    'name', 'numEdges', ...
    'description', 'Number of undirected edges', ...
    'length', [], ...
    'labels', [], ...
    'scale_path', '', ...
    'index_base', 1, ...
    'axis_type', 'index');

% faceVertices
s.dimensions('faceVertices') = struct(...
    'name', 'faceVertices', ...
    'description', 'Three vertices per triangular face', ...
    'length', 3, ...
    'labels', {{'v1', 'v2', 'v3'}}, ...
    'scale_path', '', ...
    'index_base', 1, ...
    'axis_type', 'label');

% edgeVertices
s.dimensions('edgeVertices') = struct(...
    'name', 'edgeVertices', ...
    'description', 'Two vertices per edge (sorted)', ...
    'length', 2, ...
    'labels', {{'v_min', 'v_max'}}, ...
    'scale_path', '', ...
    'index_base', 1, ...
    'axis_type', 'label');

%% Datasets
s.datasets = containers.Map();

% Dataset: tailVertex (tail vertices)
s.datasets('tailVertex') = struct(...
    'name', 'tailVertex', ...
    'path', 'topology/tailVertex', ...
    'shape', 'numHalfedges', ...
    'dims', {{'numHalfedges'}}, ...
    'dtype', struct('matlab', 'uint32', 'hdf5', 'H5T_NATIVE_UINT32', 'zarr', '<u4'), ...
    'attributes', struct('description', 'Tail vertex index of each halfedge', 'index_base', 1, 'computedBy', 'bct.manifold.topology.vertices'), ...
    'required', true);

% Dataset: headVertex (head vertices)
s.datasets('headVertex') = struct(...
    'name', 'headVertex', ...
    'path', 'topology/headVertex', ...
    'shape', 'numHalfedges', ...
    'dims', {{'numHalfedges'}}, ...
    'dtype', struct('matlab', 'uint32', 'hdf5', 'H5T_NATIVE_UINT32', 'zarr', '<u4'), ...
    'attributes', struct('description', 'Head vertex index of each halfedge', 'index_base', 1, 'computedBy', 'bct.manifold.topology.vertices'), ...
    'required', true);

% Dataset: face
s.datasets('face') = struct(...
    'name', 'face', ...
    'path', 'topology/face', ...
    'shape', 'numHalfedges', ...
    'dims', {{'numHalfedges'}}, ...
    'dtype', struct('matlab', 'uint32', 'hdf5', 'H5T_NATIVE_UINT32', 'zarr', '<u4'), ...
    'attributes', struct('description', 'Incident face index for each halfedge', 'index_base', 1, 'computedBy', 'bct.manifold.topology.faces'), ...
    'required', true);

% Dataset: next
s.datasets('next') = struct(...
    'name', 'next', ...
    'path', 'topology/next', ...
    'shape', 'numHalfedges', ...
    'dims', {{'numHalfedges'}}, ...
    'dtype', struct('matlab', 'uint32', 'hdf5', 'H5T_NATIVE_UINT32', 'zarr', '<u4'), ...
    'attributes', struct('description', 'Next halfedge around face (CCW)', 'index_base', 1, 'computedBy', 'bct.manifold.topology.circulation'), ...
    'required', true);

% Dataset: prev
s.datasets('prev') = struct(...
    'name', 'prev', ...
    'path', 'topology/prev', ...
    'shape', 'numHalfedges', ...
    'dims', {{'numHalfedges'}}, ...
    'dtype', struct('matlab', 'uint32', 'hdf5', 'H5T_NATIVE_UINT32', 'zarr', '<u4'), ...
    'attributes', struct('description', 'Previous halfedge around face (CCW)', 'index_base', 1, 'computedBy', 'bct.manifold.topology.circulation'), ...
    'required', true);

% Dataset: twin
s.datasets('twin') = struct(...
    'name', 'twin', ...
    'path', 'topology/twin', ...
    'shape', 'numHalfedges', ...
    'dims', {{'numHalfedges'}}, ...
    'dtype', struct('matlab', 'uint32', 'hdf5', 'H5T_NATIVE_UINT32', 'zarr', '<u4'), ...
    'attributes', struct('description', 'Opposite halfedge across undirected edge (0 if boundary)', 'index_base', 1, 'boundary_value', 0, 'computedBy', 'bct.manifold.topology.twins'), ...
    'required', true);

% Dataset: edge
s.datasets('edge') = struct(...
    'name', 'edge', ...
    'path', 'topology/edge', ...
    'shape', 'numHalfedges', ...
    'dims', {{'numHalfedges'}}, ...
    'dtype', struct('matlab', 'uint32', 'hdf5', 'H5T_NATIVE_UINT32', 'zarr', '<u4'), ...
    'attributes', struct('description', 'Undirected edge index for each halfedge', 'index_base', 1, 'computedBy', 'bct.manifold.topology.edgeIndices'), ...
    'required', true);

% Dataset: isBoundary
s.datasets('isBoundary') = struct(...
    'name', 'isBoundary', ...
    'path', 'topology/isBoundary', ...
    'shape', 'numHalfedges', ...
    'dims', {{'numHalfedges'}}, ...
    'dtype', struct('matlab', 'logical', 'hdf5', 'H5T_NATIVE_UINT8', 'zarr', '|b1'), ...
    'attributes', struct('description', 'Boundary flag (true if twin=0)', 'computedBy', 'derived'), ...
    'required', true);

% Dataset: edgeList (undirected edge list)
s.datasets('edgeList') = struct(...
    'name', 'edgeList', ...
    'path', 'topology/edgeList', ...
    'shape', 'numEdges × edgeVertices', ...
    'dims', {{'numEdges', 'edgeVertices'}}, ...
    'dtype', struct('matlab', 'uint32', 'hdf5', 'H5T_NATIVE_UINT32', 'zarr', '<u4'), ...
    'attributes', struct('description', 'Undirected edge list (sorted vertex indices)', 'index_base', 1, 'sorted', true, 'computedBy', 'bct.manifold.topology.edges'), ...
    'required', true);

% Dataset: faceHalfedges (face halfedges)
s.datasets('faceHalfedges') = struct(...
    'name', 'faceHalfedges', ...
    'path', 'topology/faceHalfedges', ...
    'shape', 'numFaces × faceVertices', ...
    'dims', {{'numFaces', 'faceVertices'}}, ...
    'dtype', struct('matlab', 'uint32', 'hdf5', 'H5T_NATIVE_UINT32', 'zarr', '<u4'), ...
    'attributes', struct('description', 'Halfedge indices per face [h12 h23 h31]', 'index_base', 1, 'convention', 'h12: v1->v2, h23: v2->v3, h31: v3->v1', 'computedBy', 'bct.manifold.topology.faceHalfedges'), ...
    'required', true);

% Dataset: faceNeighbors
s.datasets('faceNeighbors') = struct(...
    'name', 'faceNeighbors', ...
    'path', 'topology/faceNeighbors', ...
    'shape', 'numFaces × faceVertices', ...
    'dims', {{'numFaces', 'faceVertices'}}, ...
    'dtype', struct('matlab', 'int32', 'hdf5', 'H5T_NATIVE_INT32', 'zarr', '<i4'), ...
    'attributes', struct('description', 'Adjacent face indices (-1 for boundary)', 'index_base', 1, 'boundary_value', -1, 'computedBy', 'bct.manifold.topology.neighbors'), ...
    'required', true);

% Dataset: neighborEdge
s.datasets('neighborEdge') = struct(...
    'name', 'neighborEdge', ...
    'path', 'topology/neighborEdge', ...
    'shape', 'numFaces × faceVertices', ...
    'dims', {{'numFaces', 'faceVertices'}}, ...
    'dtype', struct('matlab', 'uint8', 'hdf5', 'H5T_NATIVE_UINT8', 'zarr', '|u1'), ...
    'attributes', struct('description', 'Local edge index (1..3) in neighbor face', 'index_base', 1, 'range', [1, 3], 'computedBy', 'bct.manifold.topology.neighbors'), ...
    'required', true);

% Dataset: adjacency (sparse adjacency matrix stored as COO format)
s.datasets('adjacency') = struct(...
    'name', 'adjacency', ...
    'path', 'topology/adjacency', ...
    'shape', 'numVertices × numVertices', ...
    'dims', {{'numVertices', 'numVertices'}}, ...
    'dtype', struct('matlab', 'logical', 'hdf5', 'H5T_NATIVE_UINT8', 'zarr', '|b1'), ...
    'attributes', struct('description', 'Sparse binary adjacency matrix', 'format', 'CSR', 'symmetric', true, 'computedBy', 'bct.manifold.topology.adjacency'), ...
    'required', true);

end
