function s = spec(quantity, unit)
%SPEC Lookup table for common physical quantities and units
%
% Syntax:
%   s = bct.field.metric.spec(quantity, unit)
%
% Inputs:
%   quantity - String specifying physical quantity
%   unit     - String specifying unit
%
% Outputs:
%   s - Structure with fields:
%       .siUnit     - Canonical SI unit
%       .dim        - Base dimension exponents
%       .scaleToSI  - Scale factor for conversion
%       .offsetToSI - Offset for conversion (affine)
%
% Description:
%   Centralized lookup table for common physical quantities and their
%   unit conversions. Provides SI unit mapping and conversion parameters.
%
%   Supported quantities:
%   - temperature: K, degC, degF
%   - zscore: 1 (dimensionless)
%   - currentDensity: A/m^2
%   - voltage: V
%   - electricField: V/m
%   - magneticField: T
%
% Examples:
%   % Temperature in Celsius
%   s = bct.field.metric.spec("temperature", "degC");
%   % s.siUnit = "K", s.offsetToSI = 273.15
%
%   % Dimensionless z-score
%   s = bct.field.metric.spec("zscore", "1");
%
% See also: bct.field.metric.declare, bct.field.metric.validate

arguments
    quantity (1,1) string
    unit (1,1) string
end

% Key for lookup
key = quantity + ":" + unit;

% Build spec map
specMap = getSpecMap();

if specMap.isKey(key)
    s = specMap(key);
else
    error('bct:field:metric:UnknownSpec', ...
        'No spec found for quantity="%s", unit="%s"', quantity, unit);
end

end

%% Helper function to build spec map
function specMap = getSpecMap()
    
    specMap = containers.Map('KeyType', 'char', 'ValueType', 'any');
    
    % ========== Temperature ==========
    % Kelvin (SI)
    specMap('temperature:K') = struct( ...
        'siUnit', "K", ...
        'dim', struct('L',0,'M',0,'T',0,'I',0,'Theta',1), ...
        'scaleToSI', 1.0, ...
        'offsetToSI', 0.0);
    
    % Celsius (affine)
    specMap('temperature:degC') = struct( ...
        'siUnit', "K", ...
        'dim', struct('L',0,'M',0,'T',0,'I',0,'Theta',1), ...
        'scaleToSI', 1.0, ...
        'offsetToSI', 273.15);
    
    % Fahrenheit (affine)
    specMap('temperature:degF') = struct( ...
        'siUnit', "K", ...
        'dim', struct('L',0,'M',0,'T',0,'I',0,'Theta',1), ...
        'scaleToSI', 5/9, ...
        'offsetToSI', 459.67 * 5/9);  % (F + 459.67) * 5/9 = K
    
    % ========== Dimensionless ==========
    % Z-score
    specMap('zscore:1') = struct( ...
        'siUnit', "1", ...
        'dim', struct('L',0,'M',0,'T',0,'I',0,'Theta',0), ...
        'scaleToSI', 1.0, ...
        'offsetToSI', 0.0);
    
    % Generic dimensionless
    specMap('dimensionless:1') = struct( ...
        'siUnit', "1", ...
        'dim', struct('L',0,'M',0,'T',0,'I',0,'Theta',0), ...
        'scaleToSI', 1.0, ...
        'offsetToSI', 0.0);
    
    % ========== Current Density ==========
    % A/m^2 (SI)
    specMap('currentDensity:A/m^2') = struct( ...
        'siUnit', "A/m^2", ...
        'dim', struct('L',-2,'M',0,'T',0,'I',1,'Theta',0), ...
        'scaleToSI', 1.0, ...
        'offsetToSI', 0.0);
    
    % μA/mm^2 (common in neuroscience)
    specMap('currentDensity:uA/mm^2') = struct( ...
        'siUnit', "A/m^2", ...
        'dim', struct('L',-2,'M',0,'T',0,'I',1,'Theta',0), ...
        'scaleToSI', 1e-6 / 1e-6, ...  % 1e-6 A / (1e-3 m)^2 = 1.0
        'offsetToSI', 0.0);
    
    % ========== Voltage ==========
    % Volt (SI)
    specMap('voltage:V') = struct( ...
        'siUnit', "V", ...
        'dim', struct('L',2,'M',1,'T',-3,'I',-1,'Theta',0), ...
        'scaleToSI', 1.0, ...
        'offsetToSI', 0.0);
    
    % Millivolt
    specMap('voltage:mV') = struct( ...
        'siUnit', "V", ...
        'dim', struct('L',2,'M',1,'T',-3,'I',-1,'Theta',0), ...
        'scaleToSI', 1e-3, ...
        'offsetToSI', 0.0);
    
    % Microvolt
    specMap('voltage:uV') = struct( ...
        'siUnit', "V", ...
        'dim', struct('L',2,'M',1,'T',-3,'I',-1,'Theta',0), ...
        'scaleToSI', 1e-6, ...
        'offsetToSI', 0.0);
    
    % ========== Electric Field ==========
    % V/m (SI)
    specMap('electricField:V/m') = struct( ...
        'siUnit', "V/m", ...
        'dim', struct('L',1,'M',1,'T',-3,'I',-1,'Theta',0), ...
        'scaleToSI', 1.0, ...
        'offsetToSI', 0.0);
    
    % mV/mm
    specMap('electricField:mV/mm') = struct( ...
        'siUnit', "V/m", ...
        'dim', struct('L',1,'M',1,'T',-3,'I',-1,'Theta',0), ...
        'scaleToSI', 1e-3 / 1e-3, ...  % mV/mm = V/m
        'offsetToSI', 0.0);
    
    % ========== Magnetic Field ==========
    % Tesla (SI)
    specMap('magneticField:T') = struct( ...
        'siUnit', "T", ...
        'dim', struct('L',0,'M',1,'T',-2,'I',-1,'Theta',0), ...
        'scaleToSI', 1.0, ...
        'offsetToSI', 0.0);
    
    % Femtotesla (common in MEG)
    specMap('magneticField:fT') = struct( ...
        'siUnit', "T", ...
        'dim', struct('L',0,'M',1,'T',-2,'I',-1,'Theta',0), ...
        'scaleToSI', 1e-15, ...
        'offsetToSI', 0.0);
    
    % Picotesla
    specMap('magneticField:pT') = struct( ...
        'siUnit', "T", ...
        'dim', struct('L',0,'M',1,'T',-2,'I',-1,'Theta',0), ...
        'scaleToSI', 1e-12, ...
        'offsetToSI', 0.0);
    
end
