% Script to update bct.data.index to support both mesh and field entries
%
% This adds FieldType, FieldSupport, FieldValueType, FieldPath, FieldMeshId
% fields to all entries (empty strings for mesh entries)

indexFile = fullfile(fileparts(fileparts(mfilename('fullpath'))), ...
    'toolbox', '+bct', '+data', 'index.m');

% Read the file
content = fileread(indexFile);

% Step 1: Update the catalog initialization to include field fields
initPattern = 'catalog = struct\( \.\.\.\n    ''Id'', \{\}, \.\.\.\n    ''Dataset'', \{\}, \.\.\.\n    ''Hemi'', \{\}, \.\.\.\n    ''Surface'', \{\}, \.\.\.\n    ''Path'', \{\}, \.\.\.\n    ''Default'', \{\}, \.\.\.\n    ''Tags'', \{\} \.\.\.\n\);';

newInit = ['catalog = struct( ...\n', ...
    '    ''Id'', {}, ...\n', ...
    '    ''Dataset'', {}, ...\n', ...
    '    ''Hemi'', {}, ...\n', ...
    '    ''Surface'', {}, ...\n', ...
    '    ''Path'', {}, ...\n', ...
    '    ''Default'', {}, ...\n', ...
    '    ''Tags'', {}, ...\n', ...
    '    ''FieldType'', {}, ...\n', ...
    '    ''FieldSupport'', {}, ...\n', ...
    '    ''FieldValueType'', {}, ...\n', ...
    '    ''FieldPath'', {}, ...\n', ...
    '    ''FieldMeshId'', {} ...\n', ...
    ');'];

content = regexprep(content, initPattern, newInit);

% Step 2: Add field fields after each Tags field for mesh entries
% Pattern: '...Tags', [...]) followed by newline and );
% We want to add the field fields before the );

meshPattern = '(''Tags'',\s*\[[^\]]+\])\s*\.\.\.\s*\n\);';
meshReplacement = ['$1, ...\n', ...
    '    ''FieldType'', """", ...\n', ...
    '    ''FieldSupport'', """", ...\n', ...
    '    ''FieldValueType'', """", ...\n', ...
    '    ''FieldPath'', """", ...\n', ...
    '    ''FieldMeshId'', """" ...\n', ...
    ');'];

content = regexprep(content, meshPattern, meshReplacement);

% Write back
fid = fopen(indexFile, 'w');
if fid == -1
    error('Could not open file for writing: %s', indexFile);
end
fprintf(fid, '%s', content);
fclose(fid);

fprintf('Successfully updated %s\n', indexFile);
fprintf('Added FieldType, FieldSupport, FieldValueType, FieldPath, FieldMeshId fields\n');
