function catalog = index()
%BCT.DATA.INDEX Authoritative manifest of bundled mesh assets
%
% Syntax:
%   catalog = bct.data.index()
%
% Outputs:
%   catalog - Struct array with fields:
%             .Id       - Canonical ID string (e.g., "fsaverage6_hemi-lh_surf-pial")
%             .Dataset  - Dataset name (e.g., "fsaverage6")
%             .Hemi     - Hemisphere: "lh" | "rh" | "both" | "none"
%             .Surface  - Surface type: "pial" | "white" | "inflated" | "sphere"
%             .Path     - Relative path under +bct/+data/assets/
%             .Default  - Logical flag for default asset
%             .Tags     - String array of descriptive tags (optional)
%
% Description:
%   Returns the authoritative catalog of all bundled mesh assets.
%   This manifest is used by bct.data.load, bct.data.list, and bct.data.info
%   to provide robust, discoverable access to test/demo data.
%
% See also: bct.data.load, bct.data.list, bct.data.info

% Initialize empty catalog
catalog = struct( ...
    'Id', {}, ...
    'Dataset', {}, ...
    'Hemi', {}, ...
    'Surface', {}, ...
    'Path', {}, ...
    'Default', {}, ...
    'Tags', {} ...
);

%% ========================================================================
% FSAVERAGE6 SURFACES
%% ========================================================================

% Left hemisphere - Pial
catalog(end+1) = struct( ...
    'Id', "fsaverage6_hemi-lh_surf-pial", ...
    'Dataset', "fsaverage6", ...
    'Hemi', "lh", ...
    'Surface', "pial", ...
    'Path', "fsaverage6/surf/fsaverage6_hemi-lh_surf-pial.mat", ...
    'Default', true, ...
    'Tags', ["cortical", "lh", "pial", "freesurfer", "standard"] ...
);

% Right hemisphere - Pial
catalog(end+1) = struct( ...
    'Id', "fsaverage6_hemi-rh_surf-pial", ...
    'Dataset', "fsaverage6", ...
    'Hemi', "rh", ...
    'Surface', "pial", ...
    'Path', "fsaverage6/surf/fsaverage6_hemi-rh_surf-pial.mat", ...
    'Default', false, ...
    'Tags', ["cortical", "rh", "pial", "freesurfer", "standard"] ...
);

%% ========================================================================
% FUTURE ASSETS (uncomment as added)
%% ========================================================================

% Left hemisphere - White matter
% catalog(end+1) = struct( ...
%     'Id', "fsaverage6_hemi-lh_surf-white", ...
%     'Dataset', "fsaverage6", ...
%     'Hemi', "lh", ...
%     'Surface', "white", ...
%     'Path', "fsaverage6/surf/fsaverage6_hemi-lh_surf-white.mat", ...
%     'Default', false, ...
%     'Tags', ["cortical", "lh", "white", "freesurfer"] ...
% );

% Right hemisphere - White matter
% catalog(end+1) = struct( ...
%     'Id', "fsaverage6_hemi-rh_surf-white", ...
%     'Dataset', "fsaverage6", ...
%     'Hemi', "rh", ...
%     'Surface', "white", ...
%     'Path', "fsaverage6/surf/fsaverage6_hemi-rh_surf-white.mat", ...
%     'Default', false, ...
%     'Tags', ["cortical", "rh", "white", "freesurfer"] ...
% );

% Left hemisphere - Inflated
% catalog(end+1) = struct( ...
%     'Id', "fsaverage6_hemi-lh_surf-inflated", ...
%     'Dataset', "fsaverage6", ...
%     'Hemi', "lh", ...
%     'Surface', "inflated", ...
%     'Path', "fsaverage6/surf/fsaverage6_hemi-lh_surf-inflated.mat", ...
%     'Default', false, ...
%     'Tags', ["cortical", "lh", "inflated", "freesurfer", "visualization"] ...
% );

% Right hemisphere - Inflated
% catalog(end+1) = struct( ...
%     'Id', "fsaverage6_hemi-rh_surf-inflated", ...
%     'Dataset', "fsaverage6", ...
%     'Hemi', "rh", ...
%     'Surface', "inflated", ...
%     'Path', "fsaverage6/surf/fsaverage6_hemi-rh_surf-inflated.mat", ...
%     'Default', false, ...
%     'Tags', ["cortical", "rh", "inflated", "freesurfer", "visualization"] ...
% );

end
