function catalog = index()
%BCT.DATA.INDEX Authoritative manifest of bundled mesh assets
%
% Syntax:
%   catalog = bct.data.index()
%
% Outputs:
%   catalog - Struct array with fields:
%             .Id       - Canonical ID string (e.g., "fsaverage6_hemi-lh_surf-pial")
%             .Dataset  - Dataset name (e.g., "fsaverage6")
%             .Hemi     - Hemisphere: "lh" | "rh" | "both" | "none"
%             .Surface  - Surface type: "pial" | "white" | "inflated" | "sphere"
%             .Path     - Relative path under +bct/+data/assets/
%             .Default  - Logical flag for default asset
%             .Tags     - String array of descriptive tags (optional)
%
% Description:
%   Returns the authoritative catalog of all bundled mesh assets.
%   This manifest is used by bct.data.load, bct.data.list, and bct.data.info
%   to provide robust, discoverable access to test/demo data.
%
% See also: bct.data.load, bct.data.list, bct.data.info

% Initialize empty catalog
catalog = struct( ...
    'Id', {}, ...
    'Dataset', {}, ...
    'Hemi', {}, ...
    'Surface', {}, ...
    'Path', {}, ...
    'Default', {}, ...
    'Tags', {}, ...
    'FieldType', {}, ...
    'FieldSupport', {}, ...
    'FieldValueType', {}, ...
    'FieldPath', {}, ...
    'FieldMeshId', {} ...
);

%% ========================================================================
% FSAVERAGE6 SURFACES
%% ========================================================================

% Left hemisphere - Pial
catalog(end+1) = struct( ...
    'Id', "fsaverage6_hemi-lh_surf-pial", ...
    'Dataset', "fsaverage6", ...
    'Hemi', "lh", ...
    'Surface', "pial", ...
    'Path', "fsaverage6/surf/fsaverage6_hemi-lh_surf-pial.mat", ...
    'Default', true, ...
    'Tags', ["cortical", "lh", "pial", "freesurfer", "standard"], ...
    'FieldType', "", ...
    'FieldSupport', "", ...
    'FieldValueType', "", ...
    'FieldPath', "", ...
    'FieldMeshId', "" ...
);

% Right hemisphere - Pial
catalog(end+1) = struct( ...
    'Id', "fsaverage6_hemi-rh_surf-pial", ...
    'Dataset', "fsaverage6", ...
    'Hemi', "rh", ...
    'Surface', "pial", ...
    'Path', "fsaverage6/surf/fsaverage6_hemi-rh_surf-pial.mat", ...
    'Default', false, ...
    'Tags', ["cortical", "rh", "pial", "freesurfer", "standard"], ...
    'FieldType', "", ...
    'FieldSupport', "", ...
    'FieldValueType', "", ...
    'FieldPath', "", ...
    'FieldMeshId', "" ...
);

%% ========================================================================
% BRAINSTORM SURFACES (@default_subject)
%% ========================================================================

% Cortex - Pial (low resolution)
catalog(end+1) = struct( ...
    'Id', "brainstorm_default_cortex_pial_low", ...
    'Dataset', "brainstorm", ...
    'Hemi', "both", ...
    'Surface', "pial", ...
    'Path', "brainstorm/anat/@default_subject/tess_cortex_pial_low.mat", ...
    'Default', false, ...
    'Tags', ["cortical", "both", "pial", "brainstorm", "low"], ...
    'FieldType', "", ...
    'FieldSupport', "", ...
    'FieldValueType', "", ...
    'FieldPath', "", ...
    'FieldMeshId', "" ...
);

% Cortex - Pial (high resolution)
catalog(end+1) = struct( ...
    'Id', "brainstorm_default_cortex_pial_high", ...
    'Dataset', "brainstorm", ...
    'Hemi', "both", ...
    'Surface', "pial", ...
    'Path', "brainstorm/anat/@default_subject/tess_cortex_pial_high.mat", ...
    'Default', false, ...
    'Tags', ["cortical", "both", "pial", "brainstorm", "high"], ...
    'FieldType', "", ...
    'FieldSupport', "", ...
    'FieldValueType', "", ...
    'FieldPath', "", ...
    'FieldMeshId', "" ...
);

% Cortex - Pial + Cerebellum (low resolution)
catalog(end+1) = struct( ...
    'Id', "brainstorm_default_cortex_pialcereb_low", ...
    'Dataset', "brainstorm", ...
    'Hemi', "both", ...
    'Surface', "pial", ...
    'Path', "brainstorm/anat/@default_subject/tess_cortex_pialcereb_low.mat", ...
    'Default', false, ...
    'Tags', ["cortical", "cerebellum", "both", "pial", "brainstorm", "low"], ...
    'FieldType', "", ...
    'FieldSupport', "", ...
    'FieldValueType', "", ...
    'FieldPath', "", ...
    'FieldMeshId', "" ...
);

% Head surface
catalog(end+1) = struct( ...
    'Id', "brainstorm_default_head", ...
    'Dataset', "brainstorm", ...
    'Hemi', "none", ...
    'Surface', "head", ...
    'Path', "brainstorm/anat/@default_subject/tess_head.mat", ...
    'Default', false, ...
    'Tags', ["head", "brainstorm", "envelope"], ...
    'FieldType', "", ...
    'FieldSupport', "", ...
    'FieldValueType', "", ...
    'FieldPath', "", ...
    'FieldMeshId', "" ...
);

% Inner skull
catalog(end+1) = struct( ...
    'Id', "brainstorm_default_innerskull", ...
    'Dataset', "brainstorm", ...
    'Hemi', "none", ...
    'Surface', "innerskull", ...
    'Path', "brainstorm/anat/@default_subject/tess_innerskull.mat", ...
    'Default', false, ...
    'Tags', ["skull", "brainstorm", "envelope", "inner"], ...
    'FieldType', "", ...
    'FieldSupport', "", ...
    'FieldValueType', "", ...
    'FieldPath', "", ...
    'FieldMeshId', "" ...
);

% Outer skull
catalog(end+1) = struct( ...
    'Id', "brainstorm_default_outerskull", ...
    'Dataset', "brainstorm", ...
    'Hemi', "none", ...
    'Surface', "outerskull", ...
    'Path', "brainstorm/anat/@default_subject/tess_outerskull.mat", ...
    'Default', false, ...
    'Tags', ["skull", "brainstorm", "envelope", "outer"], ...
    'FieldType', "", ...
    'FieldSupport', "", ...
    'FieldValueType', "", ...
    'FieldPath', "", ...
    'FieldMeshId', "" ...
);

%% ========================================================================
% BRAINSTORM SURFACES (sub-0002)
%% ========================================================================

% Cortex - Pial (low resolution)
catalog(end+1) = struct( ...
    'Id', "brainstorm_sub0002_cortex_pial_low", ...
    'Dataset', "brainstorm", ...
    'Hemi', "both", ...
    'Surface', "pial", ...
    'Path', "brainstorm/anat/sub-0002/tess_cortex_pial_low.mat", ...
    'Default', false, ...
    'Tags', ["cortical", "both", "pial", "brainstorm", "low", "sub-0002"], ...
    'FieldType', "", ...
    'FieldSupport', "", ...
    'FieldValueType', "", ...
    'FieldPath', "", ...
    'FieldMeshId', "" ...
);

% Cortex - Pial (high resolution)
catalog(end+1) = struct( ...
    'Id', "brainstorm_sub0002_cortex_pial_high", ...
    'Dataset', "brainstorm", ...
    'Hemi', "both", ...
    'Surface', "pial", ...
    'Path', "brainstorm/anat/sub-0002/tess_cortex_pial_high.mat", ...
    'Default', false, ...
    'Tags', ["cortical", "both", "pial", "brainstorm", "high", "sub-0002"], ...
    'FieldType', "", ...
    'FieldSupport', "", ...
    'FieldValueType', "", ...
    'FieldPath', "", ...
    'FieldMeshId', "" ...
);

% Cortex - White matter (low resolution)
catalog(end+1) = struct( ...
    'Id', "brainstorm_sub0002_cortex_white_low", ...
    'Dataset', "brainstorm", ...
    'Hemi', "both", ...
    'Surface', "white", ...
    'Path', "brainstorm/anat/sub-0002/tess_cortex_white_low.mat", ...
    'Default', false, ...
    'Tags', ["cortical", "both", "white", "brainstorm", "low", "sub-0002"], ...
    'FieldType', "", ...
    'FieldSupport', "", ...
    'FieldValueType', "", ...
    'FieldPath', "", ...
    'FieldMeshId', "" ...
);

% Cortex - White matter (high resolution)
catalog(end+1) = struct( ...
    'Id', "brainstorm_sub0002_cortex_white_high", ...
    'Dataset', "brainstorm", ...
    'Hemi', "both", ...
    'Surface', "white", ...
    'Path', "brainstorm/anat/sub-0002/tess_cortex_white_high.mat", ...
    'Default', false, ...
    'Tags', ["cortical", "both", "white", "brainstorm", "high", "sub-0002"], ...
    'FieldType', "", ...
    'FieldSupport', "", ...
    'FieldValueType', "", ...
    'FieldPath', "", ...
    'FieldMeshId', "" ...
);

% Cortex - Mid surface (low resolution)
catalog(end+1) = struct( ...
    'Id', "brainstorm_sub0002_cortex_mid_low", ...
    'Dataset', "brainstorm", ...
    'Hemi', "both", ...
    'Surface', "mid", ...
    'Path', "brainstorm/anat/sub-0002/tess_cortex_mid_low.mat", ...
    'Default', false, ...
    'Tags', ["cortical", "both", "mid", "brainstorm", "low", "sub-0002"], ...
    'FieldType', "", ...
    'FieldSupport', "", ...
    'FieldValueType', "", ...
    'FieldPath', "", ...
    'FieldMeshId', "" ...
);

% Cortex - Mid surface (high resolution)
catalog(end+1) = struct( ...
    'Id', "brainstorm_sub0002_cortex_mid_high", ...
    'Dataset', "brainstorm", ...
    'Hemi', "both", ...
    'Surface', "mid", ...
    'Path', "brainstorm/anat/sub-0002/tess_cortex_mid_high.mat", ...
    'Default', false, ...
    'Tags', ["cortical", "both", "mid", "brainstorm", "high", "sub-0002"], ...
    'FieldType', "", ...
    'FieldSupport', "", ...
    'FieldValueType', "", ...
    'FieldPath', "", ...
    'FieldMeshId', "" ...
);

% Cortex - Pial + Cerebellum (low resolution)
catalog(end+1) = struct( ...
    'Id', "brainstorm_sub0002_cortex_pialcereb_low", ...
    'Dataset', "brainstorm", ...
    'Hemi', "both", ...
    'Surface', "pial", ...
    'Path', "brainstorm/anat/sub-0002/tess_cortex_pialcereb_low.mat", ...
    'Default', false, ...
    'Tags', ["cortical", "cerebellum", "both", "pial", "brainstorm", "low", "sub-0002"], ...
    'FieldType', "", ...
    'FieldSupport', "", ...
    'FieldValueType', "", ...
    'FieldPath', "", ...
    'FieldMeshId', "" ...
);

% Head surface mask
catalog(end+1) = struct( ...
    'Id', "brainstorm_sub0002_head_mask", ...
    'Dataset', "brainstorm", ...
    'Hemi', "none", ...
    'Surface', "head", ...
    'Path', "brainstorm/anat/sub-0002/tess_head_mask.mat", ...
    'Default', false, ...
    'Tags', ["head", "brainstorm", "envelope", "sub-0002"], ...
    'FieldType', "", ...
    'FieldSupport', "", ...
    'FieldValueType', "", ...
    'FieldPath', "", ...
    'FieldMeshId', "" ...
);

%% ========================================================================
% FIELD TEST DATA
%% ========================================================================

% Test scalar vertex field
catalog(end+1) = struct( ...
    'Id', "test_scalarField_vertex", ...
    'Dataset', "test", ...
    'Hemi', "", ...
    'Surface', "", ...
    'Path', "", ...
    'Default', true, ...
    'Tags', ["field", "scalar", "vertex", "test"], ...
    'FieldType', "field", ...
    'FieldSupport', "vertex", ...
    'FieldValueType', "scalar", ...
    'FieldPath', "scalarField.mat", ...
    'FieldMeshId', "" ...
);

%% ========================================================================
% FUTURE ASSETS (uncomment as added)
%% ========================================================================

% Left hemisphere - White matter
% catalog(end+1) = struct( ...
%     'Id', "fsaverage6_hemi-lh_surf-white", ...
%     'Dataset', "fsaverage6", ...
%     'Hemi', "lh", ...
%     'Surface', "white", ...
%     'Path', "fsaverage6/surf/fsaverage6_hemi-lh_surf-white.mat", ...
%     'Default', false, ...
%     'Tags', ["cortical", "lh", "white", "freesurfer"] ...
% );

% Right hemisphere - White matter
% catalog(end+1) = struct( ...
%     'Id', "fsaverage6_hemi-rh_surf-white", ...
%     'Dataset', "fsaverage6", ...
%     'Hemi', "rh", ...
%     'Surface', "white", ...
%     'Path', "fsaverage6/surf/fsaverage6_hemi-rh_surf-white.mat", ...
%     'Default', false, ...
%     'Tags', ["cortical", "rh", "white", "freesurfer"] ...
% );

% Left hemisphere - Inflated
% catalog(end+1) = struct( ...
%     'Id', "fsaverage6_hemi-lh_surf-inflated", ...
%     'Dataset', "fsaverage6", ...
%     'Hemi', "lh", ...
%     'Surface', "inflated", ...
%     'Path', "fsaverage6/surf/fsaverage6_hemi-lh_surf-inflated.mat", ...
%     'Default', false, ...
%     'Tags', ["cortical", "lh", "inflated", "freesurfer", "visualization"] ...
% );

% Right hemisphere - Inflated
% catalog(end+1) = struct( ...
%     'Id', "fsaverage6_hemi-rh_surf-inflated", ...
%     'Dataset', "fsaverage6", ...
%     'Hemi', "rh", ...
%     'Surface', "inflated", ...
%     'Path', "fsaverage6/surf/fsaverage6_hemi-rh_surf-inflated.mat", ...
%     'Default', false, ...
%     'Tags', ["cortical", "rh", "inflated", "freesurfer", "visualization"] ...
% );

end


