function spec = manifold()
%MANIFOLD Return declarative schema for bct.Manifold with geometry and metadata.
%
%   spec = bct.manifold.schema.manifold() returns a two-section schema
%   specification for validating and normalizing Manifold data structures.
%
%   Schema Sections:
%     spec.mesh - Core geometry (Vertices, Faces, Edges) - required
%     spec.meta - Metadata and rendering descriptors - optional
%
%   Mesh Section (Required):
%     - Vertices [N×3 double]: 3D vertex positions
%     - Faces [F×3 uint32]: Triangle vertex indices (1-based)
%     - Edges [E×2 uint32]: Unique edge indices (1-based)
%
%   Meta Section (Optional):
%     Rendering/Interoperability:
%       - IndexBase: 0 (JavaScript/Python) or 1 (MATLAB)
%       - FaceWinding: "CCW" (counter-clockwise) or "CW" (clockwise)
%       - NormalConvention: "right-hand-rule" or "left-hand-rule"
%       - CoordinateSystem: "RAS", "LPS", or "unknown"
%       - Units: Physical units (e.g., 'mm', 'm')
%     
%     Provenance (descriptive only):
%       - ID: Unique identifier (UUID)
%       - Metric: Struct with unit, scale, rescaled flag
%       - Source: Data origin (file path, URL)
%       - CreatedAt, CreatedBy, BctVersion, GitCommit
%
%   The mesh section enforces strict validation for geometric correctness.
%   The meta section provides rendering hints and provenance without
%   blocking object construction if fields are missing.
%
% Examples:
%   % Get schema
%   spec = bct.manifold.schema.manifold();
%   
%   % Validate mesh geometry only
%   data = struct('Vertices', V, 'Faces', F, 'Edges', E);
%   bct.manifold.schema.validate(spec, data);
%   
%   % Normalize with metadata
%   data.FaceWinding = 'ccw';
%   data.CoordinateSystem = 'ras';
%   data = bct.manifold.schema.normalize(spec, data);
%
% See also: bct.manifold.schema.validate, bct.manifold.schema.normalize

% Schema metadata
spec.name = "bct.Manifold(core)";
spec.version = "1.1";
spec.description = "Triangulated 2-manifold with vertices, faces, edges, and metadata.";

%% =================================================================
%% MESH SECTION: Core Geometry (Required)
%% =================================================================
spec.mesh = struct();
spec.mesh.name = "Mesh Geometry";
spec.mesh.description = "Required geometric data: vertices, faces, edges";
spec.mesh.fields = struct();

%--- Vertices: [N×3 double] floating-point coordinates ---
spec.mesh.fields.Vertices = struct( ...
    "required", true, ...
    "kind", "float", ...
    "allowedClasses", ["double", "single"], ...
    "ndims", 2, ...
    "ncols", 3, ...
    "description", "3D vertex positions [N×3]", ...
    "normalize", @(V) double(V) ...
);

%--- Faces: [F×3 uint32] triangle vertex indices (1-based) ---
spec.mesh.fields.Faces = struct( ...
    "required", true, ...
    "kind", "index", ...
    "allowedClasses", ["uint32", "uint16", "int32", "int64", "double", "single"], ...
    "ndims", 2, ...
    "ncols", 3, ...
    "indexBase", 1, ...
    "description", "Triangle face indices [F×3], 1-based", ...
    "normalize", @(F) bct.manifold.schema.rules.normalizeIndexArray(F, "Faces") ...
);

%--- Edges: [E×2 uint32] edge vertex indices (1-based, canonical) ---
spec.mesh.fields.Edges = struct( ...
    "required", true, ...
    "kind", "index", ...
    "allowedClasses", ["uint32", "uint16", "int32", "int64", "double", "single"], ...
    "ndims", 2, ...
    "ncols", 2, ...
    "indexBase", 1, ...
    "description", "Unique edge indices [E×2], 1-based", ...
    "normalize", @(E) bct.manifold.schema.rules.normalizeIndexArray(E, "Edges") ...
);

% Cross-field validation for mesh geometry
spec.mesh.crossValidate = @crossValidateMesh;

%% =================================================================
%% META SECTION: Metadata and Descriptors (Optional)
%% =================================================================
spec.meta = struct();
spec.meta.name = "Metadata and Rendering Descriptors";
spec.meta.description = "Optional metadata for provenance, rendering, and interoperability";
spec.meta.fields = struct();

%--- ID: Unique identifier (UUID string) ---
spec.meta.fields.ID = struct( ...
    "required", false, ...
    "kind", "string", ...
    "allowedClasses", ["string", "char"], ...
    "description", "Unique identifier for this manifold instance (UUID)", ...
    "normalize", @(x) string(x) ...
);

%--- Name: Semantic identifier (e.g., filename without extension) ---
spec.meta.fields.Name = struct( ...
    "required", false, ...
    "kind", "string", ...
    "allowedClasses", ["string", "char"], ...
    "description", "Semantic identifier for quick identification (e.g., filename without extension)", ...
    "normalize", @(x) string(x) ...
);

%--- Metric: Struct with unit and scale information ---
spec.meta.fields.Metric = struct( ...
    "required", false, ...
    "kind", "struct", ...
    "allowedClasses", ["struct"], ...
    "description", "Metric information: unit (e.g., 'mm'), scale, rescaled flag", ...
    "normalize", @(x) x ...
);

%--- IndexBase: Integer base for array indexing ---
spec.meta.fields.IndexBase = struct( ...
    "required", false, ...
    "kind", "integer", ...
    "allowedClasses", ["double", "int32", "uint32"], ...
    "description", "Index base convention: 1 (MATLAB) or 0 (JavaScript/Python)", ...
    "default", 1, ...
    "allowedValues", [0, 1], ...
    "normalize", @(x) double(x) ...
);

%--- FaceWinding: Winding order for front-facing triangles ---
spec.meta.fields.FaceWinding = struct( ...
    "required", false, ...
    "kind", "string", ...
    "allowedClasses", ["string", "char"], ...
    "description", "Triangle winding order: 'CCW' (counter-clockwise) or 'CW' (clockwise)", ...
    "default", "CCW", ...
    "allowedValues", ["CCW", "CW"], ...
    "normalize", @(x) string(upper(x)) ...
);

%--- NormalConvention: Normal vector orientation relative to winding ---
spec.meta.fields.NormalConvention = struct( ...
    "required", false, ...
    "kind", "string", ...
    "allowedClasses", ["string", "char"], ...
    "description", "Normal convention: 'right-hand-rule' (CCW→outward normal)", ...
    "default", "right-hand-rule", ...
    "allowedValues", ["right-hand-rule", "left-hand-rule"], ...
    "normalize", @(x) string(lower(x)) ...
);

%--- CoordinateSystem: Spatial coordinate system convention ---
spec.meta.fields.CoordinateSystem = struct( ...
    "required", false, ...
    "kind", "string", ...
    "allowedClasses", ["string", "char"], ...
    "description", "Coordinate system: 'RAS' (Right-Anterior-Superior), 'LPS', or 'unknown'", ...
    "default", "unknown", ...
    "allowedValues", ["RAS", "LPS", "unknown"], ...
    "normalize", @(x) string(upper(x)) ...
);

%--- Units: Physical units (unified with Metric.unit) ---
spec.meta.fields.Units = struct( ...
    "required", false, ...
    "kind", "string", ...
    "allowedClasses", ["string", "char"], ...
    "description", "Physical units (e.g., 'mm', 'm', 'cm'). Prefer Metric.unit.", ...
    "normalize", @(x) string(lower(x)) ...
);

% Provenance fields (descriptive only, not validated)
spec.meta.fields.Source = struct( ...
    "required", false, ...
    "kind", "string", ...
    "allowedClasses", ["string", "char"], ...
    "description", "Data source (file path, URL, or description)", ...
    "normalize", @(x) string(x) ...
);

spec.meta.fields.CreatedAt = struct( ...
    "required", false, ...
    "kind", "datetime", ...
    "allowedClasses", ["datetime", "string", "char"], ...
    "description", "Timestamp when manifold was created", ...
    "normalize", @normalizeTimestamp ...
);

spec.meta.fields.CreatedBy = struct( ...
    "required", false, ...
    "kind", "string", ...
    "allowedClasses", ["string", "char"], ...
    "description", "User or process that created the manifold", ...
    "normalize", @(x) string(x) ...
);

spec.meta.fields.BctVersion = struct( ...
    "required", false, ...
    "kind", "string", ...
    "allowedClasses", ["string", "char"], ...
    "description", "Version of bct toolbox used to create manifold", ...
    "normalize", @(x) string(x) ...
);

spec.meta.fields.GitCommit = struct( ...
    "required", false, ...
    "kind", "string", ...
    "allowedClasses", ["string", "char"], ...
    "description", "Git commit hash of bct toolbox", ...
    "normalize", @(x) string(x) ...
);

% Cross-field validation for metadata
spec.meta.crossValidate = @crossValidateMetadata;

end

%% =================================================================
%% NORMALIZATION HELPERS
%% =================================================================

function dt = normalizeTimestamp(x)
    %NORMALIZETIMESTAMP Convert various timestamp formats to datetime
    if isdatetime(x)
        dt = x;
    elseif ischar(x) || isstring(x)
        try
            % Try ISO 8601 format first
            dt = datetime(x, 'InputFormat', 'yyyy-MM-dd''T''HH:mm:ss');
        catch
            % Fall back to default MATLAB parsing
            dt = datetime(x);
        end
    else
        error('CreatedAt must be datetime, string, or char.');
    end
end

%% =================================================================
%% CROSS-VALIDATION: Mesh Geometry
%% =================================================================

function crossValidateMesh(S)
    %CROSSVALIDATEMESH Validate relationships between geometric fields
    %
    % Checks:
    %   - Face/edge indices are within valid range [1..N]
    %   - Vertices contain no NaN/Inf values
    %   - No degenerate faces (repeated vertex indices)
    %   - No degenerate edges (identical endpoints)
    %   - Reasonable topology (E ≈ 1.5*F for closed surfaces)

    V = S.Vertices;
    F = S.Faces;
    E = S.Edges;
    
    nV = size(V, 1);
    nF = size(F, 1);
    nE = size(E, 1);
    
    % Validate vertices are finite
    if ~all(isfinite(V(:)))
        error('Vertices contains non-finite values (NaN or Inf).');
    end
    
    % Validate non-empty arrays
    if nV == 0
        error('Vertices array is empty.');
    end
    if nF == 0
        error('Faces array is empty.');
    end
    
    % Validate face indices are in range [1..nV]
    if any(F(:) < 1) || any(F(:) > nV)
        minIdx = min(F(:));
        maxIdx = max(F(:));
        error('Face indices must be in range [1..%d]. Got range [%d..%d].', ...
            nV, minIdx, maxIdx);
    end
    
    % Validate edge indices are in range [1..nV]
    if nE > 0 && (any(E(:) < 1) || any(E(:) > nV))
        minIdx = min(E(:));
        maxIdx = max(E(:));
        error('Edge indices must be in range [1..%d]. Got range [%d..%d].', ...
            nV, minIdx, maxIdx);
    end
    
    % Validate no degenerate faces (repeated vertex indices)
    degenerateFaces = any(F(:,1) == F(:,2) | F(:,2) == F(:,3) | F(:,3) == F(:,1), 2);
    if any(degenerateFaces)
        degIdx = find(degenerateFaces, 5);
        error('Found %d degenerate faces (repeated vertex indices). Sample indices: %s', ...
            sum(degenerateFaces), mat2str(degIdx'));
    end
    
    % Validate edge endpoints are distinct
    if nE > 0
        degenerateEdges = E(:,1) == E(:,2);
        if any(degenerateEdges)
            degIdx = find(degenerateEdges, 5);
            error('Found %d degenerate edges (identical endpoints). Sample indices: %s', ...
                sum(degenerateEdges), mat2str(degIdx'));
        end
    end
    
    % Warn for large meshes
    if nV > 1e8
        warning('bct:schema:largeMesh', ...
            'Mesh has %d vertices. Consider chunking for efficiency.', nV);
    end
    
    % Check edge-face relationship (closed surface: E ≈ 1.5*F)
    edgeFaceRatio = nE / nF;
    if edgeFaceRatio < 1.4 || edgeFaceRatio > 1.6
        warning('bct:schema:unusualTopology', ...
            'Edge-to-face ratio %.2f is unusual for closed surface (expected ≈1.5).', ...
            edgeFaceRatio);
    end
end

%% =================================================================
%% CROSS-VALIDATION: Metadata
%% =================================================================

function crossValidateMetadata(S)
    %CROSSVALIDATEMETADATA Validate metadata consistency
    %
    % Checks:
    %   - Metric.unit exists and is a string
    %   - Units/Metric.unit consistency
    %   - FaceWinding/NormalConvention consistency
    %   - IndexBase is 0 or 1
    
    % Validate Metric structure if present
    if isfield(S, 'Metric')
        M = S.Metric;
        
        % Metric must have 'unit' field
        if ~isfield(M, 'unit')
            error('Metric struct must contain "unit" field.');
        end
        
        % Validate unit is a string
        if ~(ischar(M.unit) || isstring(M.unit))
            error('Metric.unit must be a string or char.');
        end
        
        % Check for Units/Metric.unit conflict
        if isfield(S, 'Units') && isfield(M, 'unit')
            if ~strcmp(S.Units, M.unit)
                warning('bct:schema:unitMismatch', ...
                    'Units field "%s" conflicts with Metric.unit "%s". Using Metric.unit.', ...
                    S.Units, M.unit);
            end
        end
    end
    
    % Validate FaceWinding and NormalConvention are consistent
    if isfield(S, 'FaceWinding') && isfield(S, 'NormalConvention')
        winding = string(S.FaceWinding);
        convention = string(S.NormalConvention);
        
        % Standard: CCW + right-hand-rule → outward normals
        if winding == "CCW" && convention ~= "right-hand-rule"
            warning('bct:schema:normalConvention', ...
                'CCW winding typically uses right-hand-rule convention.');
        elseif winding == "CW" && convention ~= "left-hand-rule"
            warning('bct:schema:normalConvention', ...
                'CW winding typically uses left-hand-rule convention.');
        end
    end
    
    % Validate IndexBase is 0 or 1
    if isfield(S, 'IndexBase')
        if ~ismember(S.IndexBase, [0, 1])
            error('IndexBase must be 0 (JavaScript/Python) or 1 (MATLAB).');
        end
    end
end
