function M = bct_schema_manifold()
% M = bct_schema_manifold()
% Returns a struct describing the /manifold group and its nested datasets.

    % ---- group attributes ----
    M.path       = "/manifold";
    M.attributes = struct('hemi',"string", 'surface',"string");

    % ---- datasets (array of structs) ----
    M.datasets = [
        ds("/manifold/vertex",          ["N",3],   "float32", ...
           attrs=struct('units',"mm",'space',"RAS"), ...
           h5ds=struct('0',"/scales/axes/N"), ...
           h5p =struct('chunk',[ "~4096", 3 ], 'deflate',3))

        ds("/manifold/face",            ["F",3],   "uint32", ...
           attrs=struct('winding',"CCW",'index_base',"int32"), ...
           h5ds=struct('0',"/scales/axes/F"))

        ds("/manifold/normals_vertex",  ["N",3],   "float32", ...
           attrs=struct('units',"unit-vector"), ...
           h5ds=struct('0',"/scales/axes/N"), ...
           h5p =struct('chunk',[ "~4096", 3 ], 'deflate',3))

        ds("/manifold/normals_face",    ["F",3],   "float32", ...
           attrs=struct('units',"unit-vector"), ...
           h5ds=struct('0',"/scales/axes/F"))

        ds("/manifold/vertex_curvature",["N"],     "float32", ...
           attrs=struct('units',"1/mm",'description',"string",'collection',"properties",'domain',"vertex"), ...
           h5ds=struct('0',"/scales/axes/N"), ...
           h5p =struct('chunk',[ "~16384" ], 'deflate',4))

        ds("/manifold/adj_indptr",      ["nnz_rows"], "int64", ...
           attrs=struct('csr_shape',["int64","int64"],'symmetric',"uint8",'collection',"graph"), ...
           h5p =struct('chunk',[ "~32768" ], 'deflate',4))

        ds("/manifold/adj_indices",     ["nnz"],      "int32", ...
           attrs=struct('index_base',"int32",'collection',"graph"), ...
           h5p =struct('chunk',[ "~65536" ], 'deflate',4))

        ds("/manifold/adj_data",        ["nnz"],      "float32", ...
           attrs=struct('meaning',"edge weight",'collection',"graph"), ...
           h5p =struct('chunk',[ "~65536" ], 'deflate',4))

        ds("/manifold/degree",          ["N"],        "float32", ...
           attrs=struct('collection',"graph"), ...
           h5ds=struct('0',"/scales/axes/N"), ...
           h5p =struct('chunk',[ "~16384" ], 'deflate',3))

        ds("/manifold/lap_indptr",      ["nnz_rows"], "int64", ...
           attrs=struct('csr_shape',["int64","int64"],'collection',"graph"), ...
           h5p =struct('chunk',[ "~32768" ], 'deflate',4))

        ds("/manifold/lap_indices",     ["nnz"],      "int32", ...
           attrs=struct('collection',"graph"), ...
           h5p =struct('chunk',[ "~65536" ], 'deflate',4))

        ds("/manifold/lap_data",        ["nnz"],      "float32", ...
           attrs=struct('lap_type',"combinatorial",'collection',"graph"), ...
           h5p =struct('chunk',[ "~65536" ], 'deflate',4))

        ds("/manifold/eig_vals",        ["K"],        "float64", ...
           attrs=struct('collection',"graph"), ...
           h5ds=struct('0',"/scales/axes/K"), ...
           h5p =struct('chunk',[ "~8192" ], 'deflate',3))

        ds("/manifold/eig_vecs",        ["N","K"],    "float32", ...
           attrs=struct('orthonormal',"uint8",'collection',"graph"), ...
           h5ds=struct('0',"/scales/axes/N",'1',"/scales/axes/K"), ...
           h5p =struct('chunk',[ "~4096","~32" ], 'deflate',4))
    ];
end

% ---------- helper ----------
function D = ds(path, shape, dtype, varargin)
    p = inputParser; p.KeepUnmatched = true;
    addParameter(p,'attrs',struct(),@isstruct);
    addParameter(p,'h5ds',struct(),@isstruct);   % dimension scales by dim index
    addParameter(p,'h5p', struct(),@isstruct);   % I/O hints
    parse(p,varargin{:});
    D = struct( ...
        'path',        string(path), ...
        'shape',       string(shape(:)).', ...
        'dtype',       string(dtype), ...
        'attributes',  p.Results.attrs, ...
        'h5ds_scales', p.Results.h5ds, ...
        'h5p',         p.Results.h5p );
end
