function S = bct_schema_core()
% Returns a MATLAB struct describing the flattened bct.h5 schema.
% No incremental appends to avoid "dissimilar structures" errors.

    % -------- Root sections ----------
    S.file_attributes = struct( ...
        'required', {["bct_version","uuid","created_utc","generator","space"]}, ...
        'optional', {["endian","libver","description"]}, ...
        'notes',    "All stored as root attributes ('/')." ...
    );

    S.subject = struct( ...
        'required', "id", ...
        'free_form', true, ...
        'notes', "Store subject.id as root attribute 'id'. Any other subject attributes are additional root attributes." ...
    );

    S.cohort = struct( ...
        'storage', ["root_attribute_json","/cohort (vlen_utf8)"], ...
        'item_fields', ["href","uuid","subject_id","relation","tags","notes"] ...
    );

    % -------- Axis scales (H5DS) --------
    S.scales.axes = [ ...
        ax("/scales/axes/S","int64","stack",               struct('labels',{{"trial1","trial2"}})); ...
        ax("/scales/axes/C","int16","components",          struct('labels',{{"scalar"}})); ...
        ax("/scales/axes/N","int64","vertex_index",        struct()); ...
        ax("/scales/axes/T","int64","time",                struct('units',"sample",'sampling_rate_hz',NaN,'t0_sec',0)); ...
        ax("/scales/axes/F","int64","face_index",          struct()); ...
        ax("/scales/axes/K","int64","spatial_mode_index",  struct('laplacian',"combinatorial")); ...
        ax("/scales/axes/E","int64","event_row_index",     struct()) ...
    ];

    % -------- Groups (build in one shot) --------
    g_signal = grp("/signal", ...
        string.empty(0,1), ...
        [ ds("/signal/data", ["S","C","N","T"], "float32", ...
             'scales', ["/scales/axes/S","/scales/axes/C","/scales/axes/N","/scales/axes/T"], ...
             'attrs',  struct('dtype_primary',"float32",'component_semantic',"scalar"), ...
             'h5p',    struct('chunk',[1,"C",2048,1000],'deflate',4,'shuffle',true)) ...
        ] ...
    );

    g_manifold = grp("/manifold", ...
        ["hemi","surface"], ...
        [ ...
          ds("/manifold/vertex",  ["N",3], "float32", 'scales', "/scales/axes/N", ...
             'attrs', struct('units',"mm",'space',"RAS"), 'h5p', struct('chunk',[4096,3],'deflate',3)); ...
          ds("/manifold/face",    ["F",3], "uint32",  'scales', "/scales/axes/F", ...
             'attrs', struct('winding',"CCW",'index_base',int32(0))); ...
          ds("/manifold/normals_vertex", ["N",3], "float32", 'scales', "/scales/axes/N", ...
             'attrs', struct('units',"unit-vector"), 'h5p', struct('chunk',[4096,3],'deflate',3)); ...
          ds("/manifold/normals_face",   ["F",3], "float32", 'scales', "/scales/axes/F", ...
             'attrs', struct('units',"unit-vector")); ...
          ds("/manifold/vertex_curvature",["N"],  "float32", 'scales', "/scales/axes/N", ...
             'attrs', struct('units',"1/mm",'collection',"properties",'domain',"vertex"), 'h5p', struct('chunk',[16384],'deflate',4)); ...
          % CSR graph
          ds("/manifold/adj_indptr", ["nnz_rows"], "int64", ...
             'attrs', struct('csr_shape',["N","N"],'symmetric',uint8(1),'collection',"graph"), 'h5p', struct('chunk',[32768],'deflate',4)); ...
          ds("/manifold/adj_indices",["nnz"],      "int32", ...
             'attrs', struct('index_base',int32(0),'collection',"graph"), 'h5p', struct('chunk',[65536],'deflate',4)); ...
          ds("/manifold/adj_data",   ["nnz"],      "float32", ...
             'attrs', struct('meaning',"edge weight",'collection',"graph"), 'h5p', struct('chunk',[65536],'deflate',4)); ...
          ds("/manifold/degree",     ["N"],        "float32", 'scales', "/scales/axes/N", ...
             'attrs', struct('collection',"graph"), 'h5p', struct('chunk',[16384],'deflate',3)); ...
          % Laplacian CSR
          ds("/manifold/lap_indptr", ["nnz_rows"], "int64", ...
             'attrs', struct('csr_shape',["N","N"],'collection',"graph"), 'h5p', struct('chunk',[32768],'deflate',4)); ...
          ds("/manifold/lap_indices",["nnz"],      "int32", ...
             'attrs', struct('collection',"graph"), 'h5p', struct('chunk',[65536],'deflate',4)); ...
          ds("/manifold/lap_data",   ["nnz"],      "float32", ...
             'attrs', struct('lap_type',"combinatorial",'collection',"graph"), 'h5p', struct('chunk',[65536],'deflate',4)); ...
          % eigenpairs
          ds("/manifold/eig_vals",   ["K"],        "float64", 'scales', "/scales/axes/K", ...
             'attrs', struct('collection',"graph"), 'h5p', struct('chunk',[8192],'deflate',3)); ...
          ds("/manifold/eig_vecs",   ["N","K"],    "float32", 'scales', ["/scales/axes/N","/scales/axes/K"], ...
             'attrs', struct('orthonormal',uint8(0),'collection',"graph"), 'h5p', struct('chunk',[4096,32],'deflate',4)) ...
        ] ...
    );

    g_events = grp("/events", ...
        string.empty(0,1), ...
        [ ...
          ds("/events/id",            ["E"], "uint64", 'scales', "/scales/axes/E"); ...
          ds("/events/s_idx",         ["E"], "int32",  'scales', "/scales/axes/E"); ...
          ds("/events/c_idx",         ["E"], "int16",  'scales', "/scales/axes/E"); ...
          ds("/events/t_index",       ["E"], "int64",  'scales', "/scales/axes/E"); ...
          ds("/events/created_utc",   ["E"], "float64",'scales', "/scales/axes/E"); ...
          ds("/events/t_sec",         ["E"], "float64",'scales', "/scales/axes/E"); ...
          % enums
          ds("/events/space_repr",    ["E"], "enum<u8:{vertex,face_bary,xyz}>",        'scales', "/scales/axes/E"); ...
          ds("/events/spat_kind",     ["E"], "enum<u8:{none,lap_k,diff_tau,parcel}>",  'scales', "/scales/axes/E"); ...
          ds("/events/temp_kind",     ["E"], "enum<u8:{none,freq_hz,band,wav_scale}>", 'scales', "/scales/axes/E"); ...
          % spatial
          ds("/events/v_index",       ["E"], "int64",  'scales', "/scales/axes/E"); ...
          ds("/events/f_index",       ["E"], "int64",  'scales', "/scales/axes/E"); ...
          ds("/events/bc",            ["E",3], "float32", 'scales', "/scales/axes/E"); ...
          ds("/events/xyz",           ["E",3], "float32", 'scales', "/scales/axes/E"); ...
          % scales context
          ds("/events/spat_k",        ["E"], "int64",  'scales', "/scales/axes/E"); ...
          ds("/events/spat_tau",      ["E"], "float32",'scales', "/scales/axes/E"); ...
          ds("/events/spat_parcel",   ["E"], "int32",  'scales', "/scales/axes/E"); ...
          ds("/events/freq_hz",       ["E"], "float32",'scales', "/scales/axes/E"); ...
          ds("/events/band_id",       ["E"], "int16",  'scales', "/scales/axes/E"); ...
          ds("/events/wav_scale",     ["E"], "float32",'scales', "/scales/axes/E"); ...
          % annotations
          ds("/events/quality",       ["E"], "float32",'scales', "/scales/axes/E"); ...
          ds("/events/provenance_id", ["E"], "uint64",'scales', "/scales/axes/E"); ...
          ds("/events/label",         ["E"], "vlen_utf8",'scales', "/scales/axes/E"); ...
          % region refs
          ds("/events/signal_ref",    ["E"], "ref_dset_region", 'scales', "/scales/axes/E", ...
             'attrs', struct('target',"/signal/data")); ...
          ds("/events/mesh_ref",      ["E"], "ref_dset_region", 'scales', "/scales/axes/E", ...
             'attrs', struct('target',"/manifold/vertex")) ...
        ] ...
    );

    g_scales     = grp("/scales",        string.empty(0,1), []);
    g_scales_ax  = grp("/scales/axes",   string.empty(0,1), []); % datasets are S.scales.axes above (metadata only)
    g_scales_t   = grp("/scales/time",   ["note"], []);
    g_scales_sp  = grp("/scales/space",  ["note"], []);

    % One-shot concatenation keeps field layout consistent:
    S.groups = [g_signal; g_manifold; g_events; g_scales; g_scales_ax; g_scales_t; g_scales_sp];

    % -------- Constraints / indexes --------
    S.constraints = struct( ...
        'faces_ccw', true, ...
        'face_indices_in_range', true, ...
        'csr_shapes_match', true, ...
        'labels_utf8', true, ...
        'booleans_as_uint8', true, ...
        'dimension_scales_present', true, ...
        'subject_id_required', true ...
    );

    S.index.datasets = mapDatasets(S.groups, S.scales.axes);
    S.index.groups   = string({S.groups.path}).';
end

% ----------------- helpers -----------------

function G = grp(path, attrs, datasets)
    if ~isstring(attrs), attrs = string(attrs); end
    if isempty(datasets), datasets = struct([]); end
    G = struct('path', string(path), 'attributes', attrs(:), 'datasets', datasets);
end

function D = ds(path, shape, dtype, varargin)
    % ds(path, shapeTokens, dtype, 'scales', <many forms>, 'attrs', struct(), 'h5p', struct())
    p = inputParser; p.KeepUnmatched = true;
    addParameter(p, 'scales', {}, @(x) true);
    addParameter(p, 'attrs', struct(), @isstruct);
    addParameter(p, 'h5p',   struct(), @isstruct);
    parse(p, varargin{:});

    scs = normalize_scales(p.Results.scales);

    D = struct('path', string(path), ...
               'shape', string(shape(:)).', ...
               'dtype', string(dtype), ...
               'scales', scs, ...
               'attributes', p.Results.attrs, ...
               'h5p', p.Results.h5p);
end

function scs = normalize_scales(sc)
    if isempty(sc)
        scs = string.empty(0,1); return
    end
    if isstring(sc)
        scs = sc(:); return
    end
    if ischar(sc)
        scs = string(sc); return
    end
    if iscell(sc)
        if isscalar(sc) && (isstring(sc{1}) || ischar(sc{1}))
            scs = string(sc{1}); scs = scs(:); return
        end
        tmp = strings(0,1);
        for k = 1:numel(sc)
            if isstring(sc{k})
                tmp = [tmp; sc{k}(:)]; %#ok<AGROW>
            elseif ischar(sc{k})
                tmp = [tmp; string(sc{k})]; %#ok<AGROW>
            else
                error('normalize_scales:UnsupportedType','Bad scales element at %d: %s', k, class(sc{k}));
            end
        end
        scs = tmp(:); return
    end
    error('normalize_scales:UnsupportedType','Unsupported scales type: %s', class(sc));
end

function A = ax(path, dtype, semantic, attrs)
    if nargin < 4, attrs = struct(); end
    A = struct('path', string(path), 'dtype', string(dtype), 'semantic', string(semantic), 'attributes', attrs);
end

function M = mapDatasets(groups, axes)
    % Initialize with the target field layout
    all = struct('path', {}, 'shape', {}, 'dtype', {}, 'scales', {}, 'attributes', {}, 'h5p', {});

    % Collect group datasets (normalize to row vector)
    for i = 1:numel(groups)
        ds = groups(i).datasets;
        if ~isempty(ds)
            if size(ds,1) > 1 && size(ds,2) == 1
                ds = ds.';           % column -> row
            end
            all = [all, ds];         %#ok<AGROW>
        end
    end

    % Optionally treat axes as datasets too (also as a row)
    if ~isempty(axes)
        axRows = repmat(struct('path',"", 'shape',"[]", 'dtype',"", ...
                               'scales',string.empty(0,1), 'attributes',struct(), 'h5p',struct()), 1, numel(axes));
        for k = 1:numel(axes)
            axRows(k).path       = axes(k).path;
            axRows(k).dtype      = axes(k).dtype;
            axRows(k).attributes = axes(k).attributes;
        end
        all = [all, axRows];         %#ok<AGROW>
    end

    % Build simple index
    if isempty(all)
        M.paths = strings(0,1);
        M.table = all;
    else
        M.paths = string({all.path}).';
        M.table = all;
    end
end

