classdef Signal < handle
    %SIGNAL Signal data defined on any BCT domain
    %
    %   The Signal class represents data defined on any BCT domain (Manifold, Time,
    %   Lambda, Omega, or Joint). Signal dimensions must match the domain structure.
    %
    %   Properties:
    %       Data     - Signal values matching domain dimensions
    %       Domain   - Reference to bct.Domain object (Manifold, Time, Lambda, Omega, Joint)
    %       Label    - String label/name for the signal
    %       Mask     - bct.filters.Filter object (optional) - generative mask for signal
    %       IsVector - Logical flag indicating if signal is vector-valued (3-component)
    %
    %   Signal Generation via Masks:
    %       Signals can be generated by evaluating Filter objects (masks) on domain axes.
    %       This replaces the old createDelta() approach with a unified Filter/Kernel system.
    %       
    %       Workflow:
    %         1. Create Filter (mask): mask = bct.filters.Filter(domain, kernel, params)
    %         2. Generate signal: sig = bct.Signal.fromMask(mask, 'normalize', mode)
    %         3. Update mask params: mask.center = new_value
    %         4. Regenerate: sig.setMask(mask, 'normalize', mode)
    %       
    %       Benefits:
    %         - Supports all kernels (delta, gaussian, heat, bandpass, etc.)
    %         - Dynamic updates for interactive applications
    %         - Integration with bct.ui.KernelEditor for GUI control
    %         - Flexible normalization (none, energy, peak)
    %
    %   Dimension Validation:
    %       - Manifold/Lambda: Data must be [N×1] or [N×3] (scalar or vector)
    %       - Time/Omega: Data must be [T×1]
    %       - Joint: Data must match Joint.N → [M×N] or [M×N×3]
    %
    %   Signal Types by Domain:
    %       Manifold/Lambda:
    %         Scalar:  [N×1]   - One value per vertex/eigenmode
    %         Vector:  [N×3]   - 3D vector per vertex/eigenmode
    %       
    %       Time/Omega:
    %         Scalar:  [T×1]   - Time series or frequency spectrum
    %       
    %       Joint (e.g., Manifold_Time):
    %         Scalar:  [N×T]   - Spatiotemporal field
    %         Vector:  [N×T×3] - Spatiotemporal vector field
    %
    %   Example - Generate signal via mask (delta impulse):
    %       B = bct.bct.fromMesh(V, F);
    %       B.Time = bct.Time(0:0.01:1, 100);
    %       
    %       % Create delta mask at t=0.5s
    %       mask = bct.filters.Filter(B.Time, 'delta', 'x0', 0.5);
    %       sig = bct.Signal.fromMask(mask, 'normalize', 'energy');
    %       
    %       % Update mask and regenerate
    %       mask.x0 = 0.7;  % Move impulse
    %       sig.setMask(mask, 'normalize', 'energy');
    %
    %   Example - Generate signal via mask (Gaussian):
    %       B.Lambda = B.Manifold.dual;
    %       mask = bct.filters.Filter(B.Lambda, 'gaussian', 'center', 50, 'sigma', 10);
    %       sig = bct.Signal.fromMask(mask, 'normalize', 'peak');
    %
    %   Example - Direct construction:
    %       % Signal on Manifold domain
    %       s1 = bct.Signal(B.Manifold, rand(B.Manifold.N, 1), 'spatial');
    %
    %       % Signal on Time domain
    %       s2 = bct.Signal(B.Time, rand(B.Time.N, 1), 'timeseries');
    %
    %       % Signal on Joint Manifold_Time domain
    %       sz = B.Joint.size();
    %       s3 = bct.Signal(B.Joint, rand(sz(1), sz(2)), 'spatiotemporal');
    %
    %       % Vector signal on Joint domain
    %       s4 = bct.Signal(B.Joint, rand(sz(1), sz(2), 3), 'vector_field');
    %
    %   See also: bct.Domain, bct.filters.Filter, bct.ui.KernelEditor,
    %             bct.Manifold, bct.Time, bct.Lambda, bct.Omega, bct.Joint
    
    properties
        Data           % Signal values matching domain dimensions
        Domain         % bct.Domain object (Manifold, Time, Lambda, Omega, or Joint)
        Label string = ""  % Signal name/label
        Mask           % bct.filters.Filter object (optional) defined on same domain as Signal
    end
    
    properties (Dependent)
        IsVector       % True if signal is vector-valued (3-component)
    end
    
    % Legacy properties for backward compatibility
    properties (Dependent, Hidden)
        Manifold       % Deprecated: use Domain instead
        Time           % Deprecated: use Domain instead
        N              % Deprecated: domain-specific
        T              % Deprecated: domain-specific
        IsStatic       % Deprecated: domain-specific
        IsDynamic      % Deprecated: domain-specific
    end
    
    methods (Static)
        function sig = fromMask(mask_filter, varargin)
            %FROMMASK Create Signal by evaluating a Filter (mask) on domain axis
            %
            %   sig = Signal.fromMask(mask_filter) creates signal from filter evaluation
            %   sig = Signal.fromMask(mask_filter, 'normalize', true) creates unit-energy signal
            %
            % This is the modern approach to signal generation using the Filter/Kernel system.
            % The mask filter is evaluated on the domain's axis to generate signal data.
            %
            % Common use case: Delta signal (impulse)
            %   mask = bct.filters.Filter(B.Time, 'delta', 'x0', 0.5);
            %   sig = bct.Signal.fromMask(mask);
            %
            % Inputs:
            %   mask_filter - bct.filters.Filter object (defines kernel and domain)
            %
            % Name-Value Parameters:
            %   'normalize' - Normalization mode (default: 'none')
            %                 'none'   - No normalization
            %                 'energy' - Unit energy: s = K / norm(K)
            %                 'peak'   - Peak = 1: s = K / max(abs(K))
            %   'label'     - Custom label (default: auto-generated from filter)
            %
            % Outputs:
            %   sig - bct.Signal object with Data = evaluated mask kernel
            %
            % Examples:
            %   % Delta impulse at t=0.5s (unit energy)
            %   mask = bct.filters.Filter(B.Time, 'delta', 'x0', 0.5);
            %   sig = bct.Signal.fromMask(mask, 'normalize', 'energy');
            %   
            %   % Gaussian bump on Lambda domain
            %   mask = bct.filters.Filter(B.Lambda, 'gaussian', 'center', 50, 'sigma', 10);
            %   sig = bct.Signal.fromMask(mask);
            %   
            %   % Joint domain delta
            %   joint = B.createJoint('Manifold', 'Time');
            %   % For joint domains, use gabor or other 2D kernels as impulse approximation
            %   mask = bct.filters.Filter(joint, 'gabor', 'center_x', 50, 'center_y', 25, ...);
            %   sig = bct.Signal.fromMask(mask);
            %
            % See also: bct.filters.Filter, bct.filters.kernels.delta
            
            % Validate input
            if ~isa(mask_filter, 'bct.filters.Filter')
                error('Signal:InvalidInput', ...
                    'First argument must be a bct.filters.Filter object');
            end
            
            % Parse optional parameters
            p = inputParser;
            addParameter(p, 'normalize', 'none', @(x) ischar(x) || isstring(x));
            addParameter(p, 'label', '', @(x) ischar(x) || isstring(x));
            parse(p, varargin{:});
            
            normalize_mode = lower(string(p.Results.normalize));
            custom_label = string(p.Results.label);
            
            % Evaluate mask on domain axis
            K = mask_filter.evaluate();
            
            % Apply normalization
            switch normalize_mode
                case 'none'
                    data = K;
                case 'energy'
                    % Unit energy: s = K / ||K||_2
                    norm_val = norm(K(:));
                    if norm_val > 0
                        data = K / norm_val;
                    else
                        warning('Signal:ZeroNorm', 'Kernel has zero norm, cannot normalize');
                        data = K;
                    end
                case 'peak'
                    % Peak = 1: s = K / max(|K|)
                    max_val = max(abs(K(:)));
                    if max_val > 0
                        data = K / max_val;
                    else
                        warning('Signal:ZeroPeak', 'Kernel has zero peak, cannot normalize');
                        data = K;
                    end
                otherwise
                    error('Signal:InvalidNormalization', ...
                        'normalize must be ''none'', ''energy'', or ''peak''');
            end
            
            % Generate label
            if isempty(custom_label)
                if normalize_mode == "none"
                    label = sprintf('Signal_from_%s', mask_filter.Label);
                else
                    label = sprintf('Signal_from_%s_norm_%s', mask_filter.Label, normalize_mode);
                end
            else
                label = custom_label;
            end
            
            % Create Signal object with mask reference
            sig = bct.Signal(mask_filter.Domain, data, label);
            sig.Mask = mask_filter;  % Store reference to generating mask
        end
    end
    
    methods
        function obj = Signal(domain_obj, data, label)
            %SIGNAL Construct a Signal object
            %
            %   obj = Signal(domain, data) creates a Signal on the specified domain
            %   obj = Signal(domain, data, label) also sets a label
            %
            %   Inputs:
            %       domain - bct.Domain object (Manifold, Time, Lambda, Omega, or Joint)
            %       data   - Signal values matching domain dimensions
            %       label  - Optional string label
            %
            %   Data dimension requirements by domain type:
            %       Manifold/Lambda: [N×1] scalar or [N×3] vector
            %       Time/Omega:      [T×1] scalar
            %       Joint:           [M×N] scalar or [M×N×3] vector
            %
            %   Examples:
            %       % Manifold signal
            %       s = bct.Signal(B.Manifold, rand(B.Manifold.N, 1), 'spatial');
            %
            %       % Joint Manifold_Time signal
            %       dims = B.Joint.N;
            %       s = bct.Signal(B.Joint, rand(sz(1), sz(2)), 'spatiotemporal');
            
            if nargin > 0
                % Validate domain
                if ~isa(domain_obj, 'bct.Domain')
                    error('Signal:InvalidDomain', ...
                        'First argument must be a bct.Domain object (Manifold, Time, Lambda, Omega, or Joint)');
                end
                obj.Domain = domain_obj;
                
                % Validate and set data
                obj.validateAndSetData(data);
                
                % Set label if provided
                if nargin >= 3
                    obj.Label = string(label);
                end
            end
        end
        
        function validateAndSetData(obj, data)
            %VALIDATEANDSETDATA Validate data dimensions against domain
            
            if isempty(obj.Domain)
                error('Signal:NoDomain', 'Domain must be set before data');
            end
            
            sz = size(data);
            
            % Validation logic depends on domain type
            if isa(obj.Domain, 'bct.Joint')
                % Joint domain: data must be [M×N] or [M×N×3]
                joint_dims = obj.Domain.N;  % [M, N]
                M = joint_dims(1);
                N = joint_dims(2);
                
                if ismatrix(data)
                    % [M×N] scalar signal on joint domain
                    if sz(1) ~= M || sz(2) ~= N
                        error('Signal:DimensionMismatch', ...
                            'Data dimensions [%d×%d] must match Joint.N [%d×%d]', ...
                            sz(1), sz(2), M, N);
                    end
                elseif ndims(data) == 3
                    % [M×N×3] vector signal on joint domain
                    if sz(1) ~= M || sz(2) ~= N || sz(3) ~= 3
                        error('Signal:DimensionMismatch', ...
                            'Vector data must be [%d×%d×3], got [%d×%d×%d]', ...
                            M, N, sz(1), sz(2), sz(3));
                    end
                else
                    error('Signal:InvalidDimensions', ...
                        'Joint domain signal must be 2D [M×N] or 3D [M×N×3]');
                end
                
            elseif isa(obj.Domain, 'bct.Manifold') || isa(obj.Domain, 'bct.Lambda')
                % Spatial/Spectral domain: data must be [N×1] or [N×3]
                N_dim = obj.Domain.N;
                if N_dim == 0
                    error('Signal:InvalidDomain', 'Domain.N must be > 0');
                end
                
                if ~ismatrix(data)
                    error('Signal:InvalidDimensions', ...
                        'Manifold/Lambda signal must be 2D: [N×1] scalar or [N×3] vector');
                end
                
                if sz(1) ~= N_dim
                    error('Signal:DimensionMismatch', ...
                        'First dimension of data (%d) must match Domain.N (%d)', ...
                        sz(1), N_dim);
                end
                
                if sz(2) ~= 1 && sz(2) ~= 3
                    error('Signal:InvalidDimensions', ...
                        'Manifold/Lambda signal must be [N×1] scalar or [N×3] vector, got [%d×%d]', ...
                        sz(1), sz(2));
                end
                
            elseif isa(obj.Domain, 'bct.Time') || isa(obj.Domain, 'bct.Omega')
                % Temporal/Frequency domain: data must be [T×1]
                T_dim = obj.Domain.N;
                if T_dim == 0
                    error('Signal:InvalidDomain', 'Domain.N must be > 0');
                end
                
                if ~iscolumn(data)
                    error('Signal:InvalidDimensions', ...
                        'Time/Omega signal must be column vector [T×1], got [%d×%d]', ...
                        sz(1), sz(2));
                end
                
                if sz(1) ~= T_dim
                    error('Signal:DimensionMismatch', ...
                        'Data length (%d) must match Domain.N (%d)', ...
                        sz(1), T_dim);
                end
                
            else
                error('Signal:UnsupportedDomain', ...
                    'Unsupported domain type: %s', class(obj.Domain));
            end
            
            % Data is valid, set it
            obj.Data = data;
        end
        
        %% Dependent property getters
        function val = get.IsVector(obj)
            %GET.ISVECTOR Check if signal is vector-valued (3-component)
            sz = size(obj.Data);
            
            if isa(obj.Domain, 'bct.Joint')
                % Joint: [M×N×3] is vector
                val = (ndims(obj.Data) == 3) && (sz(3) == 3);
            elseif isa(obj.Domain, 'bct.Manifold') || isa(obj.Domain, 'bct.Lambda')
                % Spatial/Spectral: [N×3] is vector
                val = ismatrix(obj.Data) && (sz(2) == 3);
            elseif isa(obj.Domain, 'bct.Time') || isa(obj.Domain, 'bct.Omega')
                % Temporal: cannot be vector
                val = false;
            else
                val = false;
            end
        end
        
        function m = get.Manifold(obj)
            %GET.MANIFOLD Backward compatibility: return Manifold domain if applicable
            if isa(obj.Domain, 'bct.Manifold')
                m = obj.Domain;
            elseif isa(obj.Domain, 'bct.Joint') && isa(obj.Domain.A, 'bct.Manifold')
                m = obj.Domain.A;
            else
                m = [];
            end
        end
        
        function t = get.Time(obj)
            %GET.TIME Backward compatibility: return Time domain if applicable
            if isa(obj.Domain, 'bct.Time')
                t = obj.Domain;
            elseif isa(obj.Domain, 'bct.Joint') && isa(obj.Domain.B, 'bct.Time')
                t = obj.Domain.B;
            else
                t = [];
            end
        end
        
        function val = get.N(obj)
            %GET.N Get number of spatial points (deprecated, domain-specific)
            if isa(obj.Domain, 'bct.Manifold') || isa(obj.Domain, 'bct.Lambda')
                val = obj.Domain.N;
            elseif isa(obj.Domain, 'bct.Joint')
                % For Joint, return total elements (M*N)
                sz = obj.Domain.N;
                val = sz(1) * sz(2);
            else
                val = size(obj.Data, 1);
            end
        end
        
        function val = get.T(obj)
            %GET.T Get number of time points (deprecated, domain-specific)
            if isa(obj.Domain, 'bct.Time') || isa(obj.Domain, 'bct.Omega')
                val = obj.Domain.N;
            elseif isa(obj.Domain, 'bct.Joint') && (isa(obj.Domain.B, 'bct.Time') || isa(obj.Domain.B, 'bct.Omega'))
                val = obj.Domain.B.N;
            else
                val = 0;  % No time dimension
            end
        end
        
        function val = get.IsStatic(obj)
            %GET.ISSTATIC Check if signal is static (deprecated)
            % Static if domain has no time component
            if isa(obj.Domain, 'bct.Time') || isa(obj.Domain, 'bct.Omega')
                val = false;
            elseif isa(obj.Domain, 'bct.Joint')
                val = ~(isa(obj.Domain.B, 'bct.Time') || isa(obj.Domain.B, 'bct.Omega'));
            else
                val = true;  % Manifold/Lambda only = static
            end
        end
        
        function val = get.IsDynamic(obj)
            %GET.ISDYNAMIC Check if signal has time dimension (deprecated)
            val = ~obj.IsStatic;
        end
        
        %% Mask Management
        function setMask(obj, mask_filter, varargin)
            %SETMASK Set or update the mask filter and regenerate signal data
            %
            %   obj.setMask(mask_filter) sets mask and evaluates it on domain
            %   obj.setMask(mask_filter, 'normalize', 'energy') also normalizes
            %
            % This allows dynamic mask updates for interactive applications.
            % When the mask changes (e.g., via KernelEditor), call this to update signal.
            %
            % Inputs:
            %   mask_filter - bct.filters.Filter object (must match obj.Domain)
            %
            % Name-Value Parameters:
            %   'normalize' - 'none', 'energy', or 'peak' (default: 'none')
            %   'update_label' - Update signal label (default: false)
            %
            % Example:
            %   sig = bct.Signal(B.Time, zeros(B.Time.N, 1), 'impulse');
            %   mask = bct.filters.Filter(B.Time, 'delta', 'x0', 0.5);
            %   sig.setMask(mask, 'normalize', 'energy');
            %   
            %   % Later update mask parameters
            %   mask.x0 = 0.7;  % Move impulse
            %   sig.setMask(mask, 'normalize', 'energy');  % Regenerate
            %
            % See also: evaluateMask, bct.ui.KernelEditor
            
            % Validate mask
            if ~isa(mask_filter, 'bct.filters.Filter')
                error('Signal:InvalidMask', 'mask_filter must be a bct.filters.Filter object');
            end
            
            % Validate domain compatibility
            if mask_filter.Domain ~= obj.Domain
                error('Signal:DomainMismatch', ...
                    'Mask domain (%s) must match Signal domain (%s)', ...
                    class(mask_filter.Domain), class(obj.Domain));
            end
            
            % Parse options
            p = inputParser;
            addParameter(p, 'normalize', 'none', @(x) ischar(x) || isstring(x));
            addParameter(p, 'update_label', false, @islogical);
            parse(p, varargin{:});
            
            normalize_mode = lower(string(p.Results.normalize));
            update_label = p.Results.update_label;
            
            % Store mask
            obj.Mask = mask_filter;
            
            % Evaluate mask to generate data
            obj.Data = obj.evaluateMask('normalize', normalize_mode);
            
            % Update label if requested
            if update_label
                if normalize_mode == "none"
                    obj.Label = sprintf('Signal_from_%s', mask_filter.Label);
                else
                    obj.Label = sprintf('Signal_from_%s_norm_%s', mask_filter.Label, normalize_mode);
                end
            end
        end
        
        function data_out = evaluateMask(obj, varargin)
            %EVALUATEMASK Evaluate current mask on domain axis with optional normalization
            %
            %   data = obj.evaluateMask() evaluates mask without normalization
            %   data = obj.evaluateMask('normalize', 'energy') returns unit-energy signal
            %
            % This is useful when mask parameters have changed and you want to
            % regenerate the signal data.
            %
            % Name-Value Parameters:
            %   'normalize' - 'none', 'energy', or 'peak' (default: 'none')
            %
            % Returns:
            %   data_out - Evaluated and optionally normalized kernel values
            %
            % Example:
            %   % Create signal with mask
            %   mask = bct.filters.Filter(B.Time, 'gaussian', 'center', 0.5, 'sigma', 0.1);
            %   sig = bct.Signal.fromMask(mask);
            %   
            %   % Later, update mask parameters
            %   mask.center = 0.7;
            %   mask.sigma = 0.05;
            %   
            %   % Regenerate signal data
            %   sig.Data = sig.evaluateMask('normalize', 'energy');
            %
            % See also: setMask
            
            if isempty(obj.Mask)
                error('Signal:NoMask', 'Signal has no mask defined. Use setMask() first.');
            end
            
            % Parse options
            p = inputParser;
            addParameter(p, 'normalize', 'none', @(x) ischar(x) || isstring(x));
            parse(p, varargin{:});
            
            normalize_mode = lower(string(p.Results.normalize));
            
            % Evaluate mask kernel
            K = obj.Mask.evaluate();
            
            % Apply normalization
            switch normalize_mode
                case 'none'
                    data_out = K;
                case 'energy'
                    % Unit energy: s = K / ||K||_2
                    norm_val = norm(K(:));
                    if norm_val > 0
                        data_out = K / norm_val;
                    else
                        warning('Signal:ZeroNorm', 'Mask has zero norm, cannot normalize');
                        data_out = K;
                    end
                case 'peak'
                    % Peak = 1: s = K / max(|K|)
                    max_val = max(abs(K(:)));
                    if max_val > 0
                        data_out = K / max_val;
                    else
                        warning('Signal:ZeroPeak', 'Mask has zero peak, cannot normalize');
                        data_out = K;
                    end
                otherwise
                    error('Signal:InvalidNormalization', ...
                        'normalize must be ''none'', ''energy'', or ''peak''');
            end
        end
        
        %% Utility methods
        function s = summary(obj)
            %SUMMARY Get text summary of signal properties
            s = sprintf('Signal: "%s"\n', obj.Label);
            s = [s sprintf('  Type: %s %s\n', ...
                ternary(obj.IsVector, 'Vector', 'Scalar'), ...
                ternary(obj.IsStatic, 'static', 'dynamic'))];
            s = [s sprintf('  Dimensions: [%s]\n', ...
                num2str(size(obj.Data)))];
            s = [s sprintf('  N = %d spatial points\n', obj.N)];
            if obj.IsDynamic
                s = [s sprintf('  T = %d time points\n', obj.T)];
                if ~isempty(obj.Time)
                    % Handle both old and new Time classes
                    if isprop(obj.Time, 'N')  % New bct.Time
                        duration = (obj.Time.N - 1) / obj.Time.fs;
                        s = [s sprintf('  Duration = %.4f s at %.2f Hz\n', duration, obj.Time.fs)];
                    else  % Old bct.manifold.Time
                        s = [s sprintf('  Duration = %.4f s at %.2f Hz\n', ...
                            obj.Time.get_duration(), obj.Time.fs)];
                    end
                end
            end
        end
        
        function disp(obj)
            %DISP Display signal information
            fprintf('%s', obj.summary());
        end
        
        function x = get_spatial_snapshot(obj, t)
            %GET_SPATIAL_SNAPSHOT Extract spatial data at time index t
            %
            %   x = obj.get_spatial_snapshot(t) returns spatial signal at time t
            %
            %   For static signals, returns the data (ignores t)
            %   For dynamic signals, returns data(:,t) or data(:,t,:)
            
            if obj.IsStatic
                x = obj.Data;
            else
                if nargin < 2 || isempty(t)
                    error('Signal:TimeIndexRequired', ...
                        'Time index required for dynamic signals');
                end
                if t < 1 || t > obj.T
                    error('Signal:InvalidTimeIndex', ...
                        'Time index must be between 1 and %d', obj.T);
                end
                
                if obj.IsVector
                    x = squeeze(obj.Data(:, t, :));  % [N×3]
                else
                    x = obj.Data(:, t);  % [N×1]
                end
            end
        end
        
        function ts = get_temporal_trace(obj, node_idx)
            %GET_TEMPORAL_TRACE Extract time series at spatial node(s)
            %
            %   ts = obj.get_temporal_trace(node_idx) returns time series
            %   at specified node index/indices
            %
            %   Returns [T×1] for scalar or [T×3] for vector signals
            
            if obj.IsStatic
                error('Signal:NoTimeDimension', ...
                    'Signal is static (no temporal dimension)');
            end
            
            if nargin < 2 || isempty(node_idx)
                error('Signal:NodeIndexRequired', 'Node index required');
            end
            
            if any(node_idx < 1) || any(node_idx > obj.N)
                error('Signal:InvalidNodeIndex', ...
                    'Node index must be between 1 and %d', obj.N);
            end
            
            if obj.IsVector
                ts = squeeze(obj.Data(node_idx, :, :));  % [T×3] or [length(node_idx)×T×3]
            else
                ts = obj.Data(node_idx, :)';  % [T×1] or [T×length(node_idx)]
            end
        end
        
        function sig_out = applyFilter(obj, filter_obj, domain_src, domain_dst)
            %APPLYFILTER Apply filter and transform signal between domains
            %
            %   sig_out = obj.applyFilter(filter, domain_src, domain_dst)
            %
            % Applies a filter in the transform domain and synthesizes result.
            % This is the modern replacement for the old Synthesize/Generate methods.
            %
            % Workflow:
            %   1. Transform signal from source domain (domain_src)
            %   2. Multiply by filter response (filter.evaluate())
            %   3. Inverse transform to destination domain (domain_dst)
            %
            % Inputs:
            %   filter_obj - bct.filters.Filter object (evaluated on transform domain)
            %   domain_src - Source domain (must have .transform property)
            %   domain_dst - Destination domain (dual of source)
            %
            % Example:
            %   % Create impulse in Manifold
            %   delta = bct.Signal.createDelta(B.Manifold, 50);
            %   
            %   % Create spectral filter (Lambda domain)
            %   filt = designer.spatial('heat_wavenumber', 'tau', 0.1);
            %   
            %   % Apply filter: Manifold → Lambda (filter) → Manifold
            %   filtered = delta.applyFilter(filt, B.Manifold, B.Lambda);
            %
            % See also: createDelta, bct.filters.Filter.evaluate
            
            if ~isa(filter_obj, 'bct.filters.Filter')
                error('Signal:InvalidFilter', ...
                    'filter_obj must be a bct.filters.Filter object');
            end
            
            if isempty(domain_src.transform)
                error('Signal:NoTransform', ...
                    'Source domain %s has no transform initialized', domain_src.name);
            end
            
            % Forward transform: domain_src → its dual
            coeffs = domain_src.transform.forward(obj.Data);
            
            % Evaluate filter on transform domain
            H = filter_obj.evaluate();
            
            % Apply filter (element-wise multiplication)
            if isvector(coeffs) && isvector(H)
                filtered_coeffs = coeffs(:) .* H(:);
            else
                filtered_coeffs = coeffs .* H;
            end
            
            % Inverse transform: dual → domain_dst
            if isempty(domain_dst.transform)
                error('Signal:NoTransform', ...
                    'Destination domain %s has no transform initialized', domain_dst.name);
            end
            
            data_out = domain_dst.transform.inverse(filtered_coeffs);
            
            % Create output signal
            label_out = sprintf('%s_filtered_by_%s', obj.Label, filter_obj.Label);
            sig_out = bct.Signal(obj.Manifold, data_out, label_out, obj.Time);
        end
    end
end

function result = ternary(condition, true_val, false_val)
    %TERNARY Ternary operator helper
    if condition
        result = true_val;
    else
        result = false_val;
    end
end
