function specs = defs()
%DEFS Return flat dictionary of operator specifications
%
% Syntax:
%   specs = bct.registry.operators.defs()
%
% Returns:
%   specs - dictionary (string → struct) of operator specifications
%
% Keys follow hierarchical naming: "operation.domain"
% Examples: "gradient.dec", "gradient.fem", "divergence.dec"
%
% Each spec struct contains:
%   id             - Hierarchical identifier (string)
%   name           - Human-friendly label
%   domain         - Domain classification ("dec", "fem", "graph")
%   representation - Required representation type
%   inputType      - Input data type
%   outputType     - Output data type
%   formDegree     - DEC form degree (if applicable)
%   parameters     - Parameter schema
%   requires       - Capability tokens (string array)
%   dependency     - External toolbox dependency struct
%   function       - Unbound function/method handle
%   purity         - "pure" | "impure"
%   description    - Brief description
%
% See also: bct.runtime.operators.dictionary

% Initialize dictionary
specs = dictionary(string.empty, struct.empty);

% Load legacy operator specs (raw array interfaces)
specsLegacy = loadLegacySpecs();

% Load Field-native operator specs
specsField = bct.registry.operators.defsField();

% Merge dictionaries (Field-native takes precedence)
allKeys = keys(specsLegacy);
for i = 1:length(allKeys)
    specs(allKeys(i)) = specsLegacy(allKeys(i));
end

fieldKeys = keys(specsField);
for i = 1:length(fieldKeys)
    specs(fieldKeys(i)) = specsField(fieldKeys(i));
end

end

function specs = loadLegacySpecs()
%LOADLEGACYSPECS Load legacy raw-array operator specifications
% These remain for backward compatibility but should migrate to Field-native

% Initialize dictionary
specs = dictionary(string.empty, struct.empty);

% =========================================================================
% DEC OPERATORS (DiscreteExteriorCalculus from DECLab)
% =========================================================================

decDependency = struct(...
    'provider', "DECLab", ...
    'kind', "matlabpath", ...
    'requiredSymbols', ["DiscreteExteriorCalculus"], ...
    'rootHint', "external/DECLab", ...
    'notes', "");

% Gradient (0-forms → 1-forms)
specs("gradient.dec") = struct(...
    'id', "gradient.dec", ...
    'name', "DEC Gradient", ...
    'domain', "dec", ...
    'representation', "DiscreteExteriorCalculus", ...
    'inputType', "0-form", ...
    'outputType', "vector_field", ...
    'formDegree', 0, ...
    'parameters', struct(), ...
    'requires', ["d0"], ...
    'dependency', decDependency, ...
    'function', @DiscreteExteriorCalculus.gradient, ...
    'purity', "pure", ...
    'description', "Compute gradient of scalar field on vertices");

% Divergence (1-forms → 0-forms)
specs("divergence.dec") = struct(...
    'id', "divergence.dec", ...
    'name', "DEC Divergence", ...
    'domain', "dec", ...
    'representation', "DiscreteExteriorCalculus", ...
    'inputType', "vector_field", ...
    'outputType', "0-form", ...
    'formDegree', 1, ...
    'parameters', struct(), ...
    'requires', ["d0", "hd1"], ...
    'dependency', decDependency, ...
    'function', @DiscreteExteriorCalculus.divergence, ...
    'purity', "pure", ...
    'description', "Compute divergence of vector field");

% Curl (1-forms → 2-forms)
specs("curl.dec") = struct(...
    'id', "curl.dec", ...
    'name', "DEC Curl", ...
    'domain', "dec", ...
    'representation', "DiscreteExteriorCalculus", ...
    'inputType', "vector_field", ...
    'outputType', "2-form", ...
    'formDegree', 1, ...
    'parameters', struct(), ...
    'requires', ["d1"], ...
    'dependency', decDependency, ...
    'function', @DiscreteExteriorCalculus.curl, ...
    'purity', "pure", ...
    'description', "Compute curl of vector field");

% Laplacian (scalar on vertices)
specs("laplacian.dec") = struct(...
    'id', "laplacian.dec", ...
    'name', "DEC Laplacian", ...
    'domain', "dec", ...
    'representation', "DiscreteExteriorCalculus", ...
    'inputType', "operator", ...
    'outputType', "operator", ...
    'formDegree', 0, ...
    'parameters', struct(), ...
    'requires', [], ...
    'dependency', decDependency, ...
    'function', @DiscreteExteriorCalculus.laplacian, ...
    'purity', "pure", ...
    'description', "Scalar Laplacian operator on vertices");

% Helmholtz-Hodge Decomposition
specs("hhd.dec") = struct(...
    'id', "hhd.dec", ...
    'name', "DEC Helmholtz-Hodge Decomposition", ...
    'domain', "dec", ...
    'representation', "DiscreteExteriorCalculus", ...
    'inputType', "vector_field", ...
    'outputType', "struct", ...
    'formDegree', 1, ...
    'parameters', struct(), ...
    'requires', [], ...
    'dependency', decDependency, ...
    'function', @DiscreteExteriorCalculus.helmholtzHodgeDecomposition, ...
    'purity', "pure", ...
    'description', "Decompose vector field into curl-free and divergence-free components");

% =========================================================================
% FEM OPERATORS (gptoolbox wrappers)
% =========================================================================

femDependency = struct(...
    'provider', "gptoolbox", ...
    'kind', "matlabpath", ...
    'requiredSymbols', ["grad", "div"], ...
    'rootHint', "external/gptoolbox/mesh", ...
    'notes', "");

% FEM Gradient
specs("gradient.fem") = struct(...
    'id', "gradient.fem", ...
    'name', "FEM Gradient", ...
    'domain', "fem", ...
    'representation', "Manifold", ...
    'inputType', "scalar_field", ...
    'outputType', "vector_field", ...
    'formDegree', [], ...
    'parameters', struct(), ...
    'requires', [], ...
    'dependency', femDependency, ...
    'function', @bct.runtime.operators.femGradient, ...
    'purity', "pure", ...
    'description', "Compute gradient using FEM");

% FEM Divergence
specs("divergence.fem") = struct(...
    'id', "divergence.fem", ...
    'name', "FEM Divergence", ...
    'domain', "fem", ...
    'representation', "Manifold", ...
    'inputType', "vector_field", ...
    'outputType', "scalar_field", ...
    'formDegree', [], ...
    'parameters', struct(), ...
    'requires', [], ...
    'dependency', femDependency, ...
    'function', @bct.runtime.operators.femDivergence, ...
    'purity', "pure", ...
    'description', "Compute divergence using FEM");

end % End of loadLegacySpecs() function
