function specs = defsField()
%DEFSFIELD Field-native operator specifications
%
% Returns operator specs with Field signatures for input/output.
% These are the "Phase 1" operators that accept and return Fields.
%
% Syntax:
%   specs = bct.registry.operators.defsField()
%
% Returns:
%   specs - dictionary (string → struct) with Field-native operator specs
%
% Each spec includes:
%   input/inputs  - Field signature struct(s) for inputs
%   output        - Field signature struct for output
%   acceptsRaw    - Whether raw arrays are accepted (legacy support)
%   meshPolicy    - "matchContext" (default) | "ignore" | "allowMismatch"
%   framePolicy   - "none" | "requiredForTangent2" | "requiresInputFrame" | "producesFrame"
%   metaPolicy    - "inherit" | "inheritAndAugment" | "new"
%   implementation - Function handle expecting (ctx, rawInputs...)
%
% See also: bct.registry.operators.defs, bct.fields.schema

specs = dictionary(string.empty, struct.empty);

% Helper to create Field signatures
fieldSig = @bct.registry.operators.fieldSignature;

% =========================================================================
% DEC OPERATORS (Field-native)
% =========================================================================

decDependency = struct(...
    'provider', "DECLab", ...
    'kind', "matlabpath", ...
    'requiredSymbols', ["DiscreteExteriorCalculus"], ...
    'rootHint', "external/DECLab", ...
    'notes', "");

% Gradient: vertex scalar → face vector3
specs("gradient.dec.field") = struct(...
    'id', "gradient.dec.field", ...
    'name', "DEC Gradient (Field)", ...
    'domain', "dec", ...
    'representation', "DiscreteExteriorCalculus", ...
    'input', fieldSig('support', 'vertex', 'valueType', 'scalar', 'time', 'preserve'), ...
    'output', fieldSig('support', 'face', 'valueType', 'vector3', 'time', 'preserve'), ...
    'acceptsRaw', false, ...
    'meshPolicy', "matchContext", ...
    'metaPolicy', "inheritAndAugment", ...
    'parameters', struct(), ...
    'requires', ["d0"], ...
    'dependency', decDependency, ...
    'implementation', @impl_gradient_dec_field, ...
    'purity', "pure", ...
    'description', "Compute gradient of scalar field on vertices (Field-native)");

% Divergence: face vector3 → vertex scalar
specs("divergence.dec.field") = struct(...
    'id', "divergence.dec.field", ...
    'name', "DEC Divergence (Field)", ...
    'domain', "dec", ...
    'representation', "DiscreteExteriorCalculus", ...
    'input', fieldSig('support', 'face', 'valueType', 'vector3', 'time', 'preserve'), ...
    'output', fieldSig('support', 'vertex', 'valueType', 'scalar', 'time', 'preserve'), ...
    'acceptsRaw', false, ...
    'meshPolicy', "matchContext", ...
    'metaPolicy', "inheritAndAugment", ...
    'parameters', struct(), ...
    'requires', ["d0", "hd1"], ...
    'dependency', decDependency, ...
    'implementation', @impl_divergence_dec_field, ...
    'purity', "pure", ...
    'description', "Compute divergence of vector field (Field-native)");

% Laplacian: vertex scalar → vertex scalar
specs("laplacian.dec.field") = struct(...
    'id', "laplacian.dec.field", ...
    'name', "DEC Laplacian (Field)", ...
    'domain', "dec", ...
    'representation', "DiscreteExteriorCalculus", ...
    'input', fieldSig('support', 'vertex', 'valueType', 'scalar', 'time', 'preserve'), ...
    'output', fieldSig('support', 'vertex', 'valueType', 'scalar', 'time', 'preserve'), ...
    'acceptsRaw', false, ...
    'meshPolicy', "matchContext", ...
    'metaPolicy', "inheritAndAugment", ...
    'parameters', struct(), ...
    'requires', ["L0"], ...
    'dependency', decDependency, ...
    'implementation', @impl_laplacian_dec_field, ...
    'purity', "pure", ...
    'description', "Compute Laplacian of scalar field (Field-native)");

% Curl: face vector3 → scalar (magnitude) or 2-form
specs("curl.dec.field") = struct(...
    'id', "curl.dec.field", ...
    'name', "DEC Curl (Field)", ...
    'domain', "dec", ...
    'representation', "DiscreteExteriorCalculus", ...
    'input', fieldSig('support', 'face', 'valueType', 'vector3', 'time', 'preserve'), ...
    'output', fieldSig('support', 'face', 'valueType', 'scalar', 'time', 'preserve'), ...
    'acceptsRaw', false, ...
    'meshPolicy', "matchContext", ...
    'metaPolicy', "inheritAndAugment", ...
    'parameters', struct(), ...
    'requires', ["d1"], ...
    'dependency', decDependency, ...
    'implementation', @impl_curl_dec_field, ...
    'purity', "pure", ...
    'description', "Compute curl magnitude of vector field (Field-native)");

end

% =========================================================================
% IMPLEMENTATIONS (delegate to existing DEC methods)
% =========================================================================

function Y = impl_gradient_dec_field(ctx, X)
%IMPL_GRADIENT_DEC_FIELD Gradient implementation for Field wrapper
    dec = ctx.DEC;
    
    % Handle time-varying case
    if ndims(X) == 2 && size(X, 2) > 1
        % Time-varying: [nV×T]
        nT = size(X, 2);
        % Get number of faces from gradient output
        Y_sample = dec.gradient(X(:, 1));
        nF = size(Y_sample, 1);
        Y = zeros(nF, 3, nT);
        Y(:, :, 1) = Y_sample;
        for t = 2:nT
            Y(:, :, t) = dec.gradient(X(:, t));
        end
    else
        % Static: [nV×1]
        Y = dec.gradient(X);
    end
end

function Y = impl_divergence_dec_field(ctx, V)
%IMPL_DIVERGENCE_DEC_FIELD Divergence implementation for Field wrapper
    dec = ctx.DEC;
    
    % Handle time-varying case
    if ndims(V) == 3
        % Time-varying: [nF×3×T]
        nT = size(V, 3);
        % Get number of vertices from divergence output
        Y_sample = dec.divergence(V(:, :, 1));
        nV = length(Y_sample);
        Y = zeros(nV, nT);
        Y(:, 1) = Y_sample;
        for t = 2:nT
            Y(:, t) = dec.divergence(V(:, :, t));
        end
    else
        % Static: [nF×3]
        Y = dec.divergence(V);
    end
end

function Y = impl_laplacian_dec_field(ctx, X)
%IMPL_LAPLACIAN_DEC_FIELD Laplacian implementation for Field wrapper
    dec = ctx.DEC;
    
    % Use DEC's laplacian method (grad-div composition)
    % Handle time-varying case
    if size(X, 2) > 1
        % Time-varying: [nV×T]
        nT = size(X, 2);
        Y_sample = dec.divergence(dec.gradient(X(:, 1)));
        nV = length(Y_sample);
        Y = zeros(nV, nT);
        Y(:, 1) = Y_sample;
        for t = 2:nT
            % Laplacian via div(grad(X))
            gradX = dec.gradient(X(:, t));
            Y(:, t) = dec.divergence(gradX);
        end
    else
        % Static: [nV×1]
        gradX = dec.gradient(X);
        Y = dec.divergence(gradX);
    end
end

function Y = impl_curl_dec_field(ctx, V)
%IMPL_CURL_DEC_FIELD Curl implementation for Field wrapper
    dec = ctx.DEC;
    
    % Handle time-varying case
    if ndims(V) == 3
        curlVec_sample = dec.curl(V(:, :, 1));
        nF = size(curlVec_sample, 1);
        Y = zeros(nF, nT);
        % Return magnitude (scalar per face)
        Y(:, 1) = sqrt(sum(curlVec_sample.^2, 2));
        for t = 2:nT
            curlVec = dec.curl(V(:, :, t));
            curlVec = dec.curl(V(:, :, t));
            % Return magnitude (scalar per face)
            Y(:, t) = sqrt(sum(curlVec.^2, 2));
        end
    else
        % Static: [nF×3]
        curlVec = dec.curl(V);
        Y = sqrt(sum(curlVec.^2, 2));
    end
end
