function specs = defs()
%DEFS Return flat dictionary of operator specifications from bct.manifold.operator
%
% Syntax:
%   specs = bct.registry.operators.defs()
%
% Returns:
%   specs - dictionary (string → struct) of operator specifications
%
% All operators come from the bct.manifold.operator package:
%   - mass, stiffness, laplacebeltrami       - Mass, stiffness, Laplace-Beltrami operators
%   - d0, d1, dd0, dd1                       - Exterior derivatives (primal and dual)
%   - hd0, hd1, hd2, hdd0, hdd1, hdd2        - Hodge stars and inverses
%   - gradient                                - Gradient (vertex → face tangent vectors)
%   - divergence.primal, divergence.dual     - Divergence (two routes)
%   - curl.primal, curl.dual                 - Curl (two routes)
%   - hodgelaplacian.0, .1, .2               - Hodge Laplacian (0/1/2-forms)
%
% Each spec struct contains:
%   id             - Operator identifier (string)
%   name           - Human-friendly label
%   backend        - Backend package ("bct.manifold.operator")
%   inputSupport   - "vertex" | "edge" | "face"
%   outputSupport  - "vertex" | "edge" | "face"
%   inputType      - Input semantic type
%   outputType     - Output semantic type
%   parameters     - Parameter schema struct
%   isMatrix       - true if operator returns a matrix
%   isLinear       - true if operator is linear
%   purity         - "pure" (all manifold operators are pure)
%   description    - Brief description
%   function       - Unbound function handle to bct.manifold.operator.*
%
% See also: bct.manifold.operator, bct.runtime.operators.dictionary

% Initialize dictionary
specs = dictionary(string.empty, struct.empty);

% Build specs from bct.manifold.operator functions
specs = addMatrixOperators(specs);
specs = addPrimitiveOperators(specs);
specs = addCompositionOperators(specs);

end

%% ========================================================================
%  Helper Functions
% =========================================================================

function specs = addMatrixOperators(specs)
%ADDMATRIXOPERATORS Add matrix operator specifications (mass, stiffness, laplacebeltrami)

% Mass matrix
specs("mass") = struct(...
    'id', "mass", ...
    'name', "Mass Matrix", ...
    'backend', "bct.manifold.operator", ...
    'inputSupport', "vertex", ...
    'outputSupport', "vertex", ...
    'inputType', "scalar", ...
    'outputType', "scalar", ...
    'parameters', struct(...
        'variant', ["voronoi", "barycentric", "full"]), ...
    'isMatrix', true, ...
    'isLinear', true, ...
    'purity', "pure", ...
    'description', "Mass matrix with area weighting", ...
    'function', @bct.manifold.operator.mass);

specs("stiffness") = struct(...
    'id', "stiffness", ...
    'name', "Stiffness Matrix", ...
    'backend', "bct.manifold.operator", ...
    'inputSupport', "vertex", ...
    'outputSupport', "vertex", ...
    'inputType', "scalar", ...
    'outputType', "scalar", ...
    'parameters', struct('variant', 'cotan', 'sign', 'positive', 'symmetrize', true), ...
    'isMatrix', true, ...
    'isLinear', true, ...
    'purity', "pure", ...
    'description', "Stiffness matrix (cotangent Laplacian)", ...
    'function', @bct.manifold.operator.stiffness);

specs("laplacebeltrami") = struct(...
    'id', "laplacebeltrami", ...
    'name', "Laplace-Beltrami Operator", ...
    'backend', "bct.manifold.operator", ...
    'inputSupport', "vertex", ...
    'outputSupport', "vertex", ...
    'inputType', "scalar", ...
    'outputType', "scalar", ...
    'parameters', struct('method', 'fem', 'form', 'generalized'), ...
    'isMatrix', true, ...
    'isLinear', true, ...
    'purity', "pure", ...
    'description', "Laplace-Beltrami operator (generalized eigenvalue form)", ...
    'function', @bct.manifold.operator.laplacebeltrami);

end

function specs = addPrimitiveOperators(specs)
%ADDPRIMITIVEOPERATORS Add primitive DEC operators (d0, d1, hd0, etc.)

% All primitive operators returned by bct.manifold.operator.dec
% Exposed individually with flat naming (no "dec." prefix)

primitiveOps = {
    % Exterior derivatives
    'd0',    'Exterior Derivative (d0)', 'vertex', 'edge', 'Exterior derivative (0-form → 1-form)'
    'd1',    'Exterior Derivative (d1)', 'edge', 'face', 'Exterior derivative (1-form → 2-form)'
    'dd0',   'Dual Exterior Derivative (dd0)', 'face', 'edge', 'Dual exterior derivative (2-form → 1-form)'
    'dd1',   'Dual Exterior Derivative (dd1)', 'edge', 'vertex', 'Dual exterior derivative (1-form → 0-form)'
    
    % Hodge stars
    'hd0', 'Hodge Star (0-form)', 'vertex', 'vertex', 'Hodge star: primal 0-form → dual 2-form'
    'hd1', 'Hodge Star (1-form)', 'edge', 'edge', 'Hodge star: primal 1-form → dual 1-form'
    'hd2', 'Hodge Star (2-form)', 'face', 'face', 'Hodge star: primal 2-form → dual 0-form'
    'hdd0', 'Inverse Hodge Star (0-form)', 'vertex', 'vertex', 'Inverse Hodge: dual 2-form → primal 0-form'
    'hdd1', 'Inverse Hodge Star (1-form)', 'edge', 'edge', 'Inverse Hodge: dual 1-form → primal 1-form'
    'hdd2', 'Inverse Hodge Star (2-form)', 'face', 'face', 'Inverse Hodge: dual 0-form → primal 2-form'
    };

% Create primitive operator specs with flat IDs
for i = 1:size(primitiveOps, 1)
    opId = primitiveOps{i, 1};
    specs(opId) = struct(...
        'id', opId, ...
        'name', primitiveOps{i, 2}, ...
        'backend', "bct.manifold.operator.dec", ...
        'inputSupport', primitiveOps{i, 3}, ...
        'outputSupport', primitiveOps{i, 4}, ...
        'inputType', "k-form", ...
        'outputType', "k-form", ...
        'parameters', struct(), ...
        'isMatrix', true, ...
        'isLinear', true, ...
        'purity', "pure", ...
        'description', primitiveOps{i, 5}, ...
        'function', @(M) bct.manifold.operator.dec(M));
end

end

function specs = addCompositionOperators(specs)
%ADDCOMPOSITIONOPERATORS Add composition operators (gradient, divergence, curl, hodgelaplacian)

% Gradient: vertex → face (tangent vectors)
specs("gradient") = struct(...
    'id', "gradient", ...
    'name', "Gradient", ...
    'backend', "bct.manifold.operator", ...
    'inputSupport', "vertex", ...
    'outputSupport', "face", ...
    'inputType', "scalar", ...
    'outputType', "tangent_vector", ...
    'parameters', struct(), ...
    'isMatrix', true, ...
    'isLinear', true, ...
    'purity', "pure", ...
    'description', "Gradient operator: scalar field → tangent vector field (composition: sharpPD * d0)", ...
    'function', @bct.manifold.operator.gradient);

% Divergence (primal route): edge → vertex
specs("divergence.primal") = struct(...
    'id', "divergence.primal", ...
    'name', "Divergence (Primal)", ...
    'backend', "bct.manifold.operator", ...
    'inputSupport', "edge", ...
    'outputSupport', "vertex", ...
    'inputType', "1-form", ...
    'outputType', "scalar", ...
    'parameters', struct('route', 'primal'), ...
    'isMatrix', true, ...
    'isLinear', true, ...
    'purity', "pure", ...
    'description', "Divergence primal route: edge 1-form → vertex scalar (composition: hdd2 * dd1 * hd1)", ...
    'function', @(M) bct.manifold.operator.divergence(M, 'route', 'primal'));

% Divergence (dual route): edge → face
specs("divergence.dual") = struct(...
    'id', "divergence.dual", ...
    'name', "Divergence (Dual)", ...
    'backend', "bct.manifold.operator", ...
    'inputSupport', "edge", ...
    'outputSupport', "face", ...
    'inputType', "1-form", ...
    'outputType', "scalar", ...
    'parameters', struct('route', 'dual'), ...
    'isMatrix', true, ...
    'isLinear', true, ...
    'purity', "pure", ...
    'description', "Divergence dual route: edge 1-form → face scalar (composition: hd2 * d1 * hdd1)", ...
    'function', @(M) bct.manifold.operator.divergence(M, 'route', 'dual'));

% Curl (primal route): edge → face
specs("curl.primal") = struct(...
    'id', "curl.primal", ...
    'name', "Curl (Primal)", ...
    'backend', "bct.manifold.operator", ...
    'inputSupport', "edge", ...
    'outputSupport', "face", ...
    'inputType', "1-form", ...
    'outputType', "scalar", ...
    'parameters', struct('route', 'primal'), ...
    'isMatrix', true, ...
    'isLinear', true, ...
    'purity', "pure", ...
    'description', "Curl primal route: edge 1-form → face scalar (composition: hd2 * d1)", ...
    'function', @(M) bct.manifold.operator.curl(M, 'route', 'primal'));

% Curl (dual route): edge → vertex
specs("curl.dual") = struct(...
    'id', "curl.dual", ...
    'name', "Curl (Dual)", ...
    'backend', "bct.manifold.operator", ...
    'inputSupport', "edge", ...
    'outputSupport', "vertex", ...
    'inputType', "1-form", ...
    'outputType', "scalar", ...
    'parameters', struct('route', 'dual'), ...
    'isMatrix', true, ...
    'isLinear', true, ...
    'purity', "pure", ...
    'description', "Curl dual route: edge 1-form → vertex scalar (composition: hdd2 * dd1)", ...
    'function', @(M) bct.manifold.operator.curl(M, 'route', 'dual'));

% Hodge Laplacian 0-form: vertex → vertex
specs("hodgelaplacian.0") = struct(...
    'id', "hodgelaplacian.0", ...
    'name', "Hodge Laplacian (0-form)", ...
    'backend', "bct.manifold.operator", ...
    'inputSupport', "vertex", ...
    'outputSupport', "vertex", ...
    'inputType', "scalar", ...
    'outputType', "scalar", ...
    'parameters', struct('kform', 0, 'normalize', true), ...
    'isMatrix', true, ...
    'isLinear', true, ...
    'purity', "pure", ...
    'description', "Hodge Laplacian 0-form: vertex scalar → vertex scalar (composition: hdd2 * dd1 * hd1 * d0)", ...
    'function', @(M) bct.manifold.operator.hodgelaplacian(M, 'kform', 0));

% Hodge Laplacian 1-form: edge → edge
specs("hodgelaplacian.1") = struct(...
    'id', "hodgelaplacian.1", ...
    'name', "Hodge Laplacian (1-form)", ...
    'backend', "bct.manifold.operator", ...
    'inputSupport', "edge", ...
    'outputSupport', "edge", ...
    'inputType', "1-form", ...
    'outputType', "1-form", ...
    'parameters', struct('kform', 1), ...
    'isMatrix', true, ...
    'isLinear', true, ...
    'purity', "pure", ...
    'description', "Hodge Laplacian 1-form: edge 1-form → edge 1-form (composition: hd1*d0*hdd2*dd1 + dd0*hd2*d1*hdd1)", ...
    'function', @(M) bct.manifold.operator.hodgelaplacian(M, 'kform', 1));

% Hodge Laplacian 2-form: face → face
specs("hodgelaplacian.2") = struct(...
    'id', "hodgelaplacian.2", ...
    'name', "Hodge Laplacian (2-form)", ...
    'backend', "bct.manifold.operator", ...
    'inputSupport', "face", ...
    'outputSupport', "face", ...
    'inputType', "scalar", ...
    'outputType', "scalar", ...
    'parameters', struct('kform', 2), ...
    'isMatrix', true, ...
    'isLinear', true, ...
    'purity', "pure", ...
    'description', "Hodge Laplacian 2-form: face scalar → face scalar (composition: d1 * hdd1 * dd0 * hd2)", ...
    'function', @(M) bct.manifold.operator.hodgelaplacian(M, 'kform', 2));

end
