function demo_tailwind_sidebar()
    %DEMO_TAILWIND_SIDEBAR Quick demo of Tailwind Sidebar in a MATLAB figure
    %
    %   This demo creates a standalone figure with the Tailwind Sidebar
    %   component using the new portable UI structure.
    
    % Get paths - use new portable structure (no package)
    thisFile = mfilename('fullpath');
    tailwindPath = fileparts(thisFile);  % ui/tailwind
    uiPath = fileparts(tailwindPath);     % ui
    distPath = fullfile(tailwindPath, 'dist');
    componentsPath = fullfile(tailwindPath, 'components');
    
    % Verify files exist
    cssFile = fullfile(distPath, 'bct-ui.css');
    jsFile = fullfile(distPath, 'bct-ui.js');
    sidebarJsFile = fullfile(componentsPath, 'sidebar.js');
    
    if ~isfile(cssFile)
        error('CSS file not found: %s\nRun: cd toolbox/+bct/+ui/tailwind && npm run build', cssFile);
    end
    
    % Create self-contained HTML with absolute paths
    html = sprintf(['<!DOCTYPE html>\n' ...
        '<html lang="en" class="dark">\n' ...
        '<head>\n' ...
        '  <meta charset="UTF-8">\n' ...
        '  <meta name="viewport" content="width=device-width, initial-scale=1.0">\n' ...
        '  <title>BCT Sidebar Demo</title>\n' ...
        '  <link rel="stylesheet" href="file:///%s">\n' ...
        '  <style>\n' ...
        '    * { margin: 0; padding: 0; box-sizing: border-box; }\n' ...
        '    html, body { height: 100%%; overflow: hidden; }\n' ...
        '  </style>\n' ...
        '</head>\n' ...
        '<body class="m-0 p-0 overflow-hidden h-screen">\n' ...
        '  <div id="sidebar" class="h-full flex flex-col bg-light-bg-primary dark:bg-dark-bg-primary border-r border-light-border dark:border-dark-border">\n' ...
        '    <div class="flex items-center justify-between px-4 py-3 border-b border-light-border dark:border-dark-border bg-light-bg-secondary dark:bg-dark-bg-secondary">\n' ...
        '      <h3 class="text-sm font-semibold text-light-text-primary dark:text-dark-text-primary">Properties</h3>\n' ...
        '      <button id="collapse-all" class="btn-icon p-1" title="Collapse all sections">\n' ...
        '        <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">\n' ...
        '          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 9l-7 7-7-7"/>\n' ...
        '        </svg>\n' ...
        '      </button>\n' ...
        '    </div>\n' ...
        '    <div id="sections-container" class="flex-1 overflow-y-auto p-2 space-y-2">\n' ...
        '      <!-- Sections will be inserted here -->\n' ...
        '    </div>\n' ...
        '  </div>\n' ...
        '  <script src="file:///%s"></script>\n' ...
        '  <script src="file:///%s"></script>\n' ...
        '</body>\n' ...
        '</html>'], ...
        strrep(cssFile, '\', '/'), ...
        strrep(jsFile, '\', '/'), ...
        strrep(sidebarJsFile, '\', '/'));
    
    % Create figure
    fig = uifigure('Name', 'Tailwind Sidebar Demo', 'Position', [100 100 400 600]);
    
    % Create HTML component
    htmlControl = uihtml(fig);
    htmlControl.Position = [10 10 380 580];
    htmlControl.HTMLSource = html;
    
    % Wait for HTML to load
    pause(0.5);
    
    % Create mock app
    app = struct();
    app.fig = fig;
    
    % Setup data changed callback to receive messages from JavaScript
    htmlControl.DataChangedFcn = @(src, evt) handleMessage(app, evt.Data);
    
    % Send initial section data
    pause(0.2);
    htmlControl.Data = struct('cmd', 'addSection', 'section', struct(...
        'id', 'filter', ...
        'title', 'Filter Parameters', ...
        'collapsed', false, ...
        'controls', {{
            struct('id', 'center', 'type', 'slider', ...
                   'label', 'Center Frequency', 'min', 0, 'max', 100, ...
                   'step', 1, 'value', 50)
            struct('id', 'sigma', 'type', 'slider', ...
                   'label', 'Bandwidth', 'min', 1, 'max', 20, ...
                   'step', 0.5, 'value', 10)
            struct('id', 'enable', 'type', 'toggle', ...
                   'label', 'Enable Filter', 'value', true)
            struct('id', 'kernelType', 'type', 'dropdown', ...
                   'label', 'Kernel Type', ...
                   'options', {{'gaussian', 'heat', 'bandpass'}}, ...
                   'value', 'gaussian')
        }}...
    ));
    
    % Store in figure for access from callbacks
    fig.UserData = struct('html', htmlControl, 'app', app);
    
    fprintf('Sidebar demo created!\n');
    fprintf('Try interacting with the controls.\n');
    fprintf('Messages from JavaScript will appear in the command window.\n');
end

function handleMessage(app, data)
    % Handle messages from JavaScript
    if isfield(data, 'cmd')
        switch data.cmd
            case 'controlChange'
                fprintf('Control "%s" changed to: %s\n', ...
                    data.controlId, mat2str(data.value));
            case 'buttonClick'
                fprintf('Button "%s" clicked\n', data.controlId);
            otherwise
                fprintf('Received message: %s\n', jsonencode(data));
        end
    end
end
