%% Test TailwindModal Component
% Quick test script for the modal component

clear; clc;
addpath('matlab');

%% Create figure and modal
fig = uifigure('Name', 'Modal Test', 'Position', [100 100 600 400]);

% Create modal component
modal = TailwindModal(fig, [0 0 600 400]);

% Add background content
uilabel(fig, 'Text', 'Background Content', ...
    'Position', [250 180 100 30], ...
    'FontSize', 16, ...
    'FontWeight', 'bold');

%% Test Alert Modal
disp('Showing alert modal...');
modal.send(struct(...
    'cmd', 'show', ...
    'title', 'Information', ...
    'content', 'This is an alert modal. Click OK to continue.', ...
    'type', 'alert'...
));

pause(3);
modal.send(struct('cmd', 'hide'));

%% Test Confirm Modal
pause(1);
disp('Showing confirm modal...');
modal.send(struct(...
    'cmd', 'show', ...
    'title', 'Confirm Action', ...
    'content', 'Are you sure you want to proceed with this operation?', ...
    'type', 'confirm'...
));

pause(3);
modal.send(struct('cmd', 'hide'));

%% Test Prompt Modal
pause(1);
disp('Showing prompt modal...');
modal.send(struct(...
    'cmd', 'show', ...
    'title', 'Enter Value', ...
    'content', 'Please enter a name for the new filter:', ...
    'type', 'prompt', ...
    'promptValue', 'MyFilter'...
));

pause(3);
modal.send(struct('cmd', 'hide'));

%% Test Custom Content Modal
pause(1);
disp('Showing custom content modal...');
modal.send(struct(...
    'cmd', 'show', ...
    'title', 'Filter Settings', ...
    'content', '<div class="space-y-3"><label class="block text-sm">Cutoff Frequency</label><input type="range" class="slider w-full" min="0" max="100" value="50"><label class="block text-sm mt-3">Filter Order</label><input type="number" class="input w-full" value="4"></div>', ...
    'type', 'default'...
));

pause(3);
modal.send(struct('cmd', 'hide'));

disp('Modal test complete!');
