function spec = geometry()
%GEOMETRY Return canonical schema specification for BCT geometry structure
%
% Syntax:
%   spec = bct.schema.geometry()
%
% Description:
%   Defines the authoritative schema for geometry structures in BCT.
%   A geometry structure contains:
%     - .attributes: Group-level metadata (extends bct.schema.group)
%     - .face:  Face geometry subgroup (7 datasets)
%     - .vertex: Vertex geometry subgroup (3 datasets)
%     - .edge:  Edge geometry subgroup (3 datasets)
%     - .dual:  Dual mesh geometry subgroup (2 datasets)
%
%   This schema is used by bct.manifold.geometry() and related functions
%   to ensure consistency in geometry representation across BCT.
%
% Outputs:
%   spec - Structure with fields:
%     .name        - Schema name
%     .version     - Schema version string
%     .description - Human-readable description
%     .attributes  - Group attributes specification
%     .subgroups   - Subgroup specifications (face, vertex, edge, dual)
%     .validation  - Validation function handles
%
% Geometry Structure:
%   geom = struct(...
%       'attributes', struct(...
%           'path', '/geometry', ...
%           'schema', 'bct.manifold.geometry@1.0.0', ...
%           'package', 'bct.manifold.geometry', ...
%           'precision', 'double', ...
%           'circumcenterMethod', 'native', ...
%           'boundaryPolicy', 'error', ...
%           'dualCellType', 'circumcentric'), ...
%       'face', struct(...
%           'areas', dataset, ...
%           'centroids', dataset, ...
%           'circumcenters', dataset, ...
%           'normals', dataset, ...
%           'cotan', dataset, ...
%           'tangent1', dataset, ...
%           'tangent2', dataset), ...
%       'vertex', struct(...
%           'normals', dataset, ...
%           'tangent1', dataset, ...
%           'tangent2', dataset), ...
%       'edge', struct(...
%           'lengths', dataset, ...
%           'weights_cotangent', dataset, ...
%           'weights_euclidean', dataset), ...
%       'dual', struct(...
%           'edgeLengths', dataset, ...
%           'vertexAreas', dataset))
%
% Examples:
%   % Get geometry schema
%   spec = bct.schema.geometry();
%
%   % Validate geometry structure
%   M = bct.Manifold(V, F);
%   geom = bct.manifold.geometry(M);
%   isValid = bct.schema.geometry.validate(geom);
%
% See also: bct.manifold.geometry, bct.schema.group, bct.schema.dataset

% Schema metadata
spec.name = "bct.geometry";
spec.version = "1.0.0";
spec.description = "Schema for geometry structures (manifold geometric properties)";
spec.package = "bct.schema";

%% Group Attributes (extends bct.schema.group)
spec.attributes = struct();

% Base fields (from bct.schema.group)
spec.attributes.base = struct(...
    'path', '/geometry', ...
    'schema', 'bct.manifold.geometry@1.0.0', ...
    'package', 'bct.manifold.geometry');

% Geometry-specific optional fields
spec.attributes.optional = struct();

spec.attributes.optional.precision = struct(...
    'type', 'string', ...
    'description', 'Numeric precision used for computations', ...
    'allowedValues', ["double", "single"], ...
    'default', "double");

spec.attributes.optional.circumcenterMethod = struct(...
    'type', 'string', ...
    'description', 'Method for computing circumcenters', ...
    'allowedValues', ["native", "triangulation"], ...
    'default', "native");

spec.attributes.optional.boundaryPolicy = struct(...
    'type', 'string', ...
    'description', 'Policy for handling mesh boundaries in dual measures', ...
    'allowedValues', ["error", "warn", "clip"], ...
    'default', "error");

spec.attributes.optional.dualCellType = struct(...
    'type', 'string', ...
    'description', 'Type of dual cell for vertex areas', ...
    'allowedValues', ["circumcentric", "barycentric", "mixed"], ...
    'default', "circumcentric");

%% Subgroup Specifications

% Face geometry subgroup
spec.subgroups.face = struct();
spec.subgroups.face.path = '/geometry/face';
spec.subgroups.face.description = 'Face-based geometric properties';
spec.subgroups.face.datasets = struct();

% Face datasets
spec.subgroups.face.datasets.areas = struct(...
    'name', 'areas', ...
    'path', '/geometry/face/areas', ...
    'description', 'Face areas (triangular elements)', ...
    'shape', @(nF) [nF, 1], ...
    'dtype', 'double', ...
    'support', 'face', ...
    'units', 'm^2');

spec.subgroups.face.datasets.centroids = struct(...
    'name', 'centroids', ...
    'path', '/geometry/face/centroids', ...
    'description', 'Face centroids (geometric centers)', ...
    'shape', @(nF) [nF, 3], ...
    'dtype', 'double', ...
    'support', 'face', ...
    'units', 'm');

spec.subgroups.face.datasets.circumcenters = struct(...
    'name', 'circumcenters', ...
    'path', '/geometry/face/circumcenters', ...
    'description', 'Face circumcenters (dual vertex positions)', ...
    'shape', @(nF) [nF, 3], ...
    'dtype', 'double', ...
    'support', 'face', ...
    'units', 'm');

spec.subgroups.face.datasets.normals = struct(...
    'name', 'normals', ...
    'path', '/geometry/face/normals', ...
    'description', 'Face unit normal vectors', ...
    'shape', @(nF) [nF, 3], ...
    'dtype', 'double', ...
    'support', 'face', ...
    'units', '1');

spec.subgroups.face.datasets.cotan = struct(...
    'name', 'cotan', ...
    'path', '/geometry/face/cotan', ...
    'description', 'Cotangent values at face corners (for FEM)', ...
    'shape', @(nF) [nF, 3], ...
    'dtype', 'double', ...
    'support', 'face', ...
    'units', '1');

spec.subgroups.face.datasets.tangent1 = struct(...
    'name', 'tangent1', ...
    'path', '/geometry/face/tangent1', ...
    'description', 'First tangent basis vector (orthogonal to normal)', ...
    'shape', @(nF) [nF, 3], ...
    'dtype', 'double', ...
    'support', 'face', ...
    'units', '1');

spec.subgroups.face.datasets.tangent2 = struct(...
    'name', 'tangent2', ...
    'path', '/geometry/face/tangent2', ...
    'description', 'Second tangent basis vector (completes right-handed frame)', ...
    'shape', @(nF) [nF, 3], ...
    'dtype', 'double', ...
    'support', 'face', ...
    'units', '1');

% Vertex geometry subgroup
spec.subgroups.vertex = struct();
spec.subgroups.vertex.path = '/geometry/vertex';
spec.subgroups.vertex.description = 'Vertex-based geometric properties';
spec.subgroups.vertex.datasets = struct();

% Vertex datasets
spec.subgroups.vertex.datasets.normals = struct(...
    'name', 'normals', ...
    'path', '/geometry/vertex/normals', ...
    'description', 'Vertex unit normal vectors (area-weighted from faces)', ...
    'shape', @(nV) [nV, 3], ...
    'dtype', 'double', ...
    'support', 'vertex', ...
    'units', '1');

spec.subgroups.vertex.datasets.tangent1 = struct(...
    'name', 'tangent1', ...
    'path', '/geometry/vertex/tangent1', ...
    'description', 'First tangent basis vector (orthogonal to normal)', ...
    'shape', @(nV) [nV, 3], ...
    'dtype', 'double', ...
    'support', 'vertex', ...
    'units', '1');

spec.subgroups.vertex.datasets.tangent2 = struct(...
    'name', 'tangent2', ...
    'path', '/geometry/vertex/tangent2', ...
    'description', 'Second tangent basis vector (completes right-handed frame)', ...
    'shape', @(nV) [nV, 3], ...
    'dtype', 'double', ...
    'support', 'vertex', ...
    'units', '1');

% Edge geometry subgroup
spec.subgroups.edge = struct();
spec.subgroups.edge.path = '/geometry/edge';
spec.subgroups.edge.description = 'Edge-based geometric properties';
spec.subgroups.edge.datasets = struct();

% Edge datasets
spec.subgroups.edge.datasets.lengths = struct(...
    'name', 'lengths', ...
    'path', '/geometry/edge/lengths', ...
    'description', 'Euclidean edge lengths', ...
    'shape', @(nE) [nE, 1], ...
    'dtype', 'double', ...
    'support', 'edge', ...
    'units', 'm');

spec.subgroups.edge.datasets.weights_cotangent = struct(...
    'name', 'weights_cotangent', ...
    'path', '/geometry/edge/weights_cotangent', ...
    'description', 'Cotangent-weighted edge lengths (for spectral methods)', ...
    'shape', @(nE) [nE, 1], ...
    'dtype', 'double', ...
    'support', 'edge', ...
    'units', '1');

spec.subgroups.edge.datasets.weights_euclidean = struct(...
    'name', 'weights_euclidean', ...
    'path', '/geometry/edge/weights_euclidean', ...
    'description', 'Euclidean edge weights (normalized lengths)', ...
    'shape', @(nE) [nE, 1], ...
    'dtype', 'double', ...
    'support', 'edge', ...
    'units', '1');

% Dual geometry subgroup
spec.subgroups.dual = struct();
spec.subgroups.dual.path = '/geometry/dual';
spec.subgroups.dual.description = 'Dual mesh geometric properties';
spec.subgroups.dual.datasets = struct();

% Dual datasets
spec.subgroups.dual.datasets.edgeLengths = struct(...
    'name', 'edgeLengths', ...
    'path', '/geometry/dual/edgeLengths', ...
    'description', 'Dual edge lengths (distances between circumcenters)', ...
    'shape', @(nE) [nE, 1], ...
    'dtype', 'double', ...
    'support', 'edge', ...
    'units', 'm');

spec.subgroups.dual.datasets.vertexAreas = struct(...
    'name', 'vertexAreas', ...
    'path', '/geometry/dual/vertexAreas', ...
    'description', 'Dual vertex areas (Voronoi or barycentric cell areas)', ...
    'shape', @(nV) [nV, 1], ...
    'dtype', 'double', ...
    'support', 'vertex', ...
    'units', 'm^2');

%% Structure Specification
spec.structure = struct();
spec.structure.required = ["attributes", "face", "vertex", "edge", "dual"];
spec.structure.description = 'Geometry structure must have attributes and all four subgroups';

%% Validation
spec.validate = @validateGeometry;

%% Helper Functions
spec.make = @makeGeometry;

%% Documentation
spec.documentation = struct(...
    'purpose', 'Enforce uniform geometry structure across BCT', ...
    'usage', 'All geometry computations should return this structure', ...
    'examples', struct(...
        'compute', 'geom = bct.manifold.geometry(M)', ...
        'validate', 'bct.schema.geometry.validate(geom)', ...
        'access', 'areas = geom.face.areas.value; normals = geom.vertex.normals.value'));

end

%% =================================================================
%% VALIDATION FUNCTIONS
%% =================================================================

function isValid = validateGeometry(geom, varargin)
    %VALIDATEGEOMETRY Validate complete geometry structure
    %
    % Inputs:
    %   geom - Geometry structure to validate
    %
    % Name-Value Arguments:
    %   Strict - true (default) to throw errors, false to return report
    %
    % Outputs:
    %   isValid - true if valid, false otherwise
    
    p = inputParser;
    p.addRequired('geom');
    p.addParameter('Strict', true, @islogical);
    p.parse(geom, varargin{:});
    
    strict = p.Results.Strict;
    
    try
        % Get schema
        spec = bct.schema.geometry();
        
        %% Check required fields
        if ~isstruct(geom)
            error('bct:schema:geometry:NotStruct', 'Geometry must be a struct');
        end
        
        requiredFields = spec.structure.required;
        for i = 1:numel(requiredFields)
            field = requiredFields(i);
            if ~isfield(geom, field)
                error('bct:schema:geometry:MissingField', ...
                    'Required field missing: %s', field);
            end
        end
        
        %% Validate group attributes
        attrs = geom.attributes;
        
        % Validate base group fields
        bct.schema.group.validate(attrs);
        
        % Validate geometry-specific optional fields (if present)
        optionalAttrs = fieldnames(spec.attributes.optional);
        for i = 1:numel(optionalAttrs)
            fieldName = optionalAttrs{i};
            if isfield(attrs, fieldName)
                fieldSpec = spec.attributes.optional.(fieldName);
                value = attrs.(fieldName);
                
                % Type check
                if isfield(fieldSpec, 'type')
                    switch fieldSpec.type
                        case 'string'
                            if ~isstring(value) && ~ischar(value)
                                error('bct:schema:geometry:InvalidType', ...
                                    'Attribute %s must be string', fieldName);
                            end
                    end
                end
                
                % Allowed values check
                if isfield(fieldSpec, 'allowedValues')
                    if isstring(value) || ischar(value)
                        value = string(value);
                    end
                    if ~ismember(value, fieldSpec.allowedValues)
                        error('bct:schema:geometry:InvalidValue', ...
                            'Attribute %s has invalid value "%s"', fieldName, string(value));
                    end
                end
            end
        end
        
        %% Validate subgroups
        subgroupNames = ["face", "vertex", "edge", "dual"];
        
        for i = 1:numel(subgroupNames)
            subgroupName = subgroupNames(i);
            subgroup = geom.(subgroupName);
            subgroupSpec = spec.subgroups.(subgroupName);
            
            % Check that subgroup is a struct
            if ~isstruct(subgroup)
                error('bct:schema:geometry:InvalidSubgroup', ...
                    'Subgroup %s must be a struct', subgroupName);
            end
            
            % Validate each dataset in subgroup
            datasetNames = fieldnames(subgroupSpec.datasets);
            for j = 1:numel(datasetNames)
                datasetName = datasetNames{j};
                
                % Check dataset exists
                if ~isfield(subgroup, datasetName)
                    error('bct:schema:geometry:MissingDataset', ...
                        'Dataset %s.%s is missing', subgroupName, datasetName);
                end
                
                % Validate dataset structure
                dataset = subgroup.(datasetName);
                bct.schema.dataset.validate(dataset);
            end
        end
        
        %% Validation passed
        isValid = true;
        
    catch ME
        if strict
            rethrow(ME);
        end
        warning('bct:schema:geometry:ValidationFailed', ...
            'Geometry validation failed: %s', ME.message);
        isValid = false;
    end
end

function geom = makeGeometry(M, varargin)
    %MAKEGEOMETRY Create schema-compliant geometry structure
    %
    % Syntax:
    %   geom = bct.schema.geometry.make(M)
    %   geom = bct.schema.geometry.make(M, 'precision', 'double', ...)
    %
    % Inputs:
    %   M - bct.Manifold object
    %
    % Optional Name-Value Arguments:
    %   precision          - 'double' (default) or 'single'
    %   circumcenterMethod - 'native' (default) or 'triangulation'
    %   boundaryPolicy     - 'error' (default), 'warn', or 'clip'
    %   dualCellType       - 'circumcentric' (default), 'barycentric', or 'mixed'
    %
    % Examples:
    %   M = bct.Manifold(V, F);
    %   geom = bct.schema.geometry.make(M);
    %   geom = bct.schema.geometry.make(M, 'precision', 'single');
    
    p = inputParser;
    p.addRequired('M', @(x) isa(x, 'bct.Manifold'));
    p.addParameter('precision', 'double', @(x) ischar(x) || isstring(x));
    p.addParameter('circumcenterMethod', 'native', @(x) ischar(x) || isstring(x));
    p.addParameter('boundaryPolicy', 'error', @(x) ischar(x) || isstring(x));
    p.addParameter('dualCellType', 'circumcentric', @(x) ischar(x) || isstring(x));
    p.parse(M, varargin{:});
    
    % Use the actual geometry computation function
    geom = bct.manifold.geometry(M, ...
        'precision', p.Results.precision, ...
        'circumcenterMethod', p.Results.circumcenterMethod, ...
        'boundaryPolicy', p.Results.boundaryPolicy, ...
        'dualCellType', p.Results.dualCellType);
    
    % Validate
    bct.schema.geometry.validate(geom);
end
