function spec = operators()
%OPERATORS Return canonical schema specification for BCT operators structure
%
% Syntax:
%   spec = bct.schema.operators()
%
% Description:
%   Defines the authoritative schema for operator structures in BCT.
%   An operators structure contains:
%     - .attributes: Group-level metadata (extends bct.schema.group)
%     - FEM operators: mass, stiffness, laplacebeltrami
%     - DEC operators: d0, d1, dd0, dd1, hd0, hd1, hd2, etc.
%     - Composed operators: gradient, divergence, curl
%
%   This schema is used by bct.manifold.operator() and related functions
%   to ensure consistency in operator representation across BCT.
%
% Outputs:
%   spec - Structure with fields:
%     .name        - Schema name
%     .version     - Schema version string
%     .description - Human-readable description
%     .attributes  - Group attributes specification
%     .datasets    - Dataset specifications
%     .validation  - Validation function handles
%
% Operators Structure:
%   ops = struct(...
%       'attributes', struct(...
%           'path', '/operators', ...
%           'schema', 'bct.manifold.operator@1.0.0', ...
%           'package', 'bct.manifold.operator', ...
%           'massVariant', 'voronoi', ...
%           'stiffnessVariant', 'cotan', ...
%           'stiffnessSign', 'positive', ...
%           'symmetrize', true), ...
%       'mass', dataset, ...
%       'stiffness', dataset, ...
%       'laplacebeltrami', dataset, ...
%       'd0', dataset, ...
%       'd1', dataset, ...
%       ... (all other operators))
%
% Examples:
%   % Get operators schema
%   spec = bct.schema.operators();
%
%   % Validate operators structure
%   M = bct.Manifold(V, F);
%   ops = bct.manifold.operator(M);
%   isValid = bct.schema.operators.validate(ops);
%
% See also: bct.manifold.operator, bct.schema.group, bct.schema.dataset

% Schema metadata
spec.name = "bct.operators";
spec.version = "1.0.0";
spec.description = "Schema for operator structures (differential and DEC operators)";
spec.package = "bct.schema";

%% Group Attributes (extends bct.schema.group)
spec.attributes = struct();

% Base fields (from bct.schema.group)
spec.attributes.base = struct(...
    'path', '/operators', ...
    'schema', 'bct.manifold.operator@1.0.0', ...
    'package', 'bct.manifold.operator');

% Operator-specific optional fields
spec.attributes.optional = struct();

spec.attributes.optional.massVariant = struct(...
    'type', 'string', ...
    'description', 'Mass matrix construction method', ...
    'allowedValues', ["voronoi", "barycentric", "full"], ...
    'default', "voronoi");

spec.attributes.optional.stiffnessVariant = struct(...
    'type', 'string', ...
    'description', 'Stiffness matrix construction method', ...
    'allowedValues', ["cotan"], ...
    'default', "cotan");

spec.attributes.optional.stiffnessSign = struct(...
    'type', 'string', ...
    'description', 'Sign convention for stiffness matrix', ...
    'allowedValues', ["positive", "negative"], ...
    'default', "positive");

spec.attributes.optional.symmetrize = struct(...
    'type', 'logical', ...
    'description', 'Whether to symmetrize operators', ...
    'default', true);

%% Dataset Specifications

% FEM operators
spec.datasets.mass = struct(...
    'name', 'mass', ...
    'path', '/operators/mass', ...
    'description', 'FEM mass matrix (lumped or full)', ...
    'shape', @(nV) [nV, nV], ...
    'dtype', 'double', ...
    'support', 'vertex', ...
    'units', 'm^2');

spec.datasets.stiffness = struct(...
    'name', 'stiffness', ...
    'path', '/operators/stiffness', ...
    'description', 'FEM stiffness matrix (cotangent Laplacian)', ...
    'shape', @(nV) [nV, nV], ...
    'dtype', 'double', ...
    'support', 'vertex', ...
    'units', '1');

spec.datasets.laplacebeltrami = struct(...
    'name', 'laplacebeltrami', ...
    'path', '/operators/laplacebeltrami', ...
    'description', 'Laplace-Beltrami operator (M^-1 * K)', ...
    'shape', @(nV) [nV, nV], ...
    'dtype', 'double', ...
    'support', 'vertex', ...
    'units', '1/m^2');

% DEC exterior derivatives
spec.datasets.d0 = struct(...
    'name', 'd0', ...
    'path', '/operators/d0', ...
    'description', 'Exterior derivative d0: 0-forms (vertex) → 1-forms (edge)', ...
    'shape', @(nE, nV) [nE, nV], ...
    'dtype', 'double', ...
    'support', 'edge', ...
    'units', '1');

spec.datasets.d1 = struct(...
    'name', 'd1', ...
    'path', '/operators/d1', ...
    'description', 'Exterior derivative d1: 1-forms (edge) → 2-forms (face)', ...
    'shape', @(nF, nE) [nF, nE], ...
    'dtype', 'double', ...
    'support', 'face', ...
    'units', '1');

% DEC codifferentials
spec.datasets.dd0 = struct(...
    'name', 'dd0', ...
    'path', '/operators/dd0', ...
    'description', 'Codifferential δ0: 1-forms (edge) → 0-forms (vertex)', ...
    'shape', @(nV, nE) [nV, nE], ...
    'dtype', 'double', ...
    'support', 'vertex', ...
    'units', '1');

spec.datasets.dd1 = struct(...
    'name', 'dd1', ...
    'path', '/operators/dd1', ...
    'description', 'Codifferential δ1: 2-forms (face) → 1-forms (edge)', ...
    'shape', @(nE, nF) [nE, nF], ...
    'dtype', 'double', ...
    'support', 'edge', ...
    'units', '1');

% DEC Hodge stars
spec.datasets.hd0 = struct(...
    'name', 'hd0', ...
    'path', '/operators/hd0', ...
    'description', 'Hodge star *₀: primal 0-forms → dual 2-forms', ...
    'shape', @(nV) [nV, nV], ...
    'dtype', 'double', ...
    'support', 'vertex', ...
    'units', 'm^2');

spec.datasets.hd1 = struct(...
    'name', 'hd1', ...
    'path', '/operators/hd1', ...
    'description', 'Hodge star *₁: primal 1-forms → dual 1-forms', ...
    'shape', @(nE) [nE, nE], ...
    'dtype', 'double', ...
    'support', 'edge', ...
    'units', '1');

spec.datasets.hd2 = struct(...
    'name', 'hd2', ...
    'path', '/operators/hd2', ...
    'description', 'Hodge star *₂: primal 2-forms → dual 0-forms', ...
    'shape', @(nF) [nF, nF], ...
    'dtype', 'double', ...
    'support', 'face', ...
    'units', '1/m^2');

% Composed operators
spec.datasets.gradient = struct(...
    'name', 'gradient', ...
    'path', '/operators/gradient', ...
    'description', 'Gradient operator: scalar(vertex) → tangent2(face)', ...
    'shape', @(nF, nV) [nF, nV], ...
    'dtype', 'double', ...
    'support', 'face', ...
    'units', '1/m');

spec.datasets.divergence = struct(...
    'name', 'divergence', ...
    'path', '/operators/divergence', ...
    'description', 'Divergence operator: tangent2(face) → scalar(vertex)', ...
    'shape', @(nV, nF) [nV, nF], ...
    'dtype', 'double', ...
    'support', 'vertex', ...
    'units', '1/m');

spec.datasets.curl = struct(...
    'name', 'curl', ...
    'path', '/operators/curl', ...
    'description', 'Curl operator: tangent2(face) → scalar(face)', ...
    'shape', @(nF, nF_in) [nF, nF_in], ...
    'dtype', 'double', ...
    'support', 'face', ...
    'units', '1/m');

%% Structure Specification
spec.structure = struct();
spec.structure.required = ["attributes", "mass", "stiffness", "laplacebeltrami", "d0", "d1"];
spec.structure.optional = ["dd0", "dd1", "hd0", "hd1", "hd2", "hdd0", "hdd1", "hdd2", ...
                           "flatPP", "flatDP", "flatDD", "sharpPD", "sharpDD", ...
                           "gradient", "divergence", "curl", "hodgelaplacian"];
spec.structure.description = 'Operators structure must have attributes and core FEM/DEC operators';

%% Validation
spec.validate = @validateOperators;

%% Helper Functions
spec.make = @makeOperators;

%% Documentation
spec.documentation = struct(...
    'purpose', 'Enforce uniform operator structure across BCT', ...
    'usage', 'All operator computations should return this structure', ...
    'examples', struct(...
        'compute', 'ops = bct.manifold.operator(M)', ...
        'validate', 'bct.schema.operators.validate(ops)', ...
        'access', 'L = ops.laplacebeltrami.value; d0 = ops.d0.value'));

end

%% =================================================================
%% VALIDATION FUNCTIONS
%% =================================================================

function isValid = validateOperators(ops, varargin)
    %VALIDATEOPERATORS Validate complete operators structure
    %
    % Inputs:
    %   ops - Operators structure to validate
    %
    % Name-Value Arguments:
    %   Strict - true (default) to throw errors, false to return report
    %
    % Outputs:
    %   isValid - true if valid, false otherwise
    
    p = inputParser;
    p.addRequired('ops');
    p.addParameter('Strict', true, @islogical);
    p.parse(ops, varargin{:});
    
    strict = p.Results.Strict;
    
    try
        % Get schema
        spec = bct.schema.operators();
        
        %% Check required fields
        if ~isstruct(ops)
            error('bct:schema:operators:NotStruct', 'Operators must be a struct');
        end
        
        requiredFields = spec.structure.required;
        for i = 1:numel(requiredFields)
            field = requiredFields(i);
            if ~isfield(ops, field)
                error('bct:schema:operators:MissingField', ...
                    'Required field missing: %s', field);
            end
        end
        
        %% Validate group attributes
        attrs = ops.attributes;
        
        % Validate base group fields
        bct.schema.group.validate(attrs);
        
        % Validate operator-specific optional fields (if present)
        optionalAttrs = fieldnames(spec.attributes.optional);
        for i = 1:numel(optionalAttrs)
            fieldName = optionalAttrs{i};
            if isfield(attrs, fieldName)
                fieldSpec = spec.attributes.optional.(fieldName);
                value = attrs.(fieldName);
                
                % Type check
                if isfield(fieldSpec, 'type')
                    switch fieldSpec.type
                        case 'string'
                            if ~isstring(value) && ~ischar(value)
                                error('bct:schema:operators:InvalidType', ...
                                    'Attribute %s must be string', fieldName);
                            end
                        case 'logical'
                            if ~islogical(value)
                                error('bct:schema:operators:InvalidType', ...
                                    'Attribute %s must be logical', fieldName);
                            end
                    end
                end
                
                % Allowed values check
                if isfield(fieldSpec, 'allowedValues')
                    if isstring(value) || ischar(value)
                        value = string(value);
                    end
                    if ~ismember(value, fieldSpec.allowedValues)
                        error('bct:schema:operators:InvalidValue', ...
                            'Attribute %s has invalid value "%s"', fieldName, string(value));
                    end
                end
            end
        end
        
        %% Validate datasets
        % Required datasets
        for i = 1:numel(requiredFields)
            field = requiredFields(i);
            if field == "attributes"
                continue;
            end
            
            dataset = ops.(field);
            bct.schema.dataset.validate(dataset);
        end
        
        % Optional datasets
        optionalFields = spec.structure.optional;
        for i = 1:numel(optionalFields)
            field = optionalFields(i);
            if isfield(ops, field)
                % Special case: hodgelaplacian is a nested structure
                if field == "hodgelaplacian"
                    continue;  % Skip validation for now
                end
                dataset = ops.(field);
                bct.schema.dataset.validate(dataset);
            end
        end
        
        %% Validation passed
        isValid = true;
        
    catch ME
        if strict
            rethrow(ME);
        end
        warning('bct:schema:operators:ValidationFailed', ...
            'Operators validation failed: %s', ME.message);
        isValid = false;
    end
end

function ops = makeOperators(M, varargin)
    %MAKEOPERATORS Create schema-compliant operators structure
    %
    % Syntax:
    %   ops = bct.schema.operators.make(M)
    %   ops = bct.schema.operators.make(M, 'MassVariant', 'voronoi', ...)
    %
    % Inputs:
    %   M - bct.Manifold object
    %
    % Optional Name-Value Arguments:
    %   MassVariant      - 'voronoi' (default), 'barycentric', 'full'
    %   StiffnessVariant - 'cotan' (default)
    %   StiffnessSign    - 'positive' (default), 'negative'
    %   Symmetrize       - true (default), false
    %
    % Examples:
    %   M = bct.Manifold(V, F);
    %   ops = bct.schema.operators.make(M);
    %   ops = bct.schema.operators.make(M, 'MassVariant', 'barycentric');
    
    p = inputParser;
    p.addRequired('M', @(x) isa(x, 'bct.Manifold'));
    p.addParameter('MassVariant', 'voronoi', @(x) ischar(x) || isstring(x));
    p.addParameter('StiffnessVariant', 'cotan', @(x) ischar(x) || isstring(x));
    p.addParameter('StiffnessSign', 'positive', @(x) ischar(x) || isstring(x));
    p.addParameter('Symmetrize', true, @islogical);
    p.parse(M, varargin{:});
    
    % Use the actual operator computation function
    ops = bct.manifold.operator(M, ...
        'MassVariant', p.Results.MassVariant, ...
        'StiffnessVariant', p.Results.StiffnessVariant, ...
        'StiffnessSign', p.Results.StiffnessSign, ...
        'Symmetrize', p.Results.Symmetrize);
    
    % Validate
    bct.schema.operators.validate(ops);
end
