function topo = topology(M, varargin)
%TOPOLOGY Compute all topological properties of a manifold
%
% Syntax:
%   topo = bct.manifold.topology(M)
%   topo = bct.manifold.topology(V, F)
%
% Inputs:
%   M - bct.Manifold object
%   V - [N×3] vertex coordinates (can be empty [] for pure topology)
%   F - [M×3] face connectivity (1-indexed)
%
% Outputs:
%   topo - Structure matching bct.manifold.topology.schema:
%     .attributes               - Group-level metadata (numVertices, numFaces, numHalfedges)
%     .tailVertex.value         - [nH×1 uint32] Tail vertex indices
%     .tailVertex.attributes    - Dataset metadata
%     .headVertex.value         - [nH×1 uint32] Head vertex indices
%     .headVertex.attributes    - Dataset metadata
%     .face.value               - [nH×1 uint32] Incident face indices
%     .face.attributes          - Dataset metadata
%     .next.value               - [nH×1 uint32] Next halfedge (CCW)
%     .next.attributes          - Dataset metadata
%     .prev.value               - [nH×1 uint32] Previous halfedge (CCW)
%     .prev.attributes          - Dataset metadata
%     .twin.value               - [nH×1 uint32] Twin halfedge (0 if boundary)
%     .twin.attributes          - Dataset metadata
%     .edge.value               - [nH×1 uint32] Undirected edge indices
%     .edge.attributes          - Dataset metadata
%     .isBoundary.value         - [nH×1 logical] Boundary flags
%     .isBoundary.attributes    - Dataset metadata
%     .edgeList.value           - [nE×2 uint32] Undirected edge list
%     .edgeList.attributes      - Dataset metadata
%     .faceHalfedges.value      - [nF×3 uint32] Halfedge indices per face
%     .faceHalfedges.attributes - Dataset metadata
%     .faceNeighbors.value      - [nF×3 int32] Adjacent face indices
%     .faceNeighbors.attributes - Dataset metadata
%     .neighborEdge.value       - [nF×3 uint8] Local edge index in neighbors
%     .neighborEdge.attributes  - Dataset metadata
%     .adjacency.value          - [nV×nV sparse logical] Adjacency matrix
%     .adjacency.attributes     - Dataset metadata
%
% Description:
%   Top-level aggregator that computes complete topological connectivity
%   including halfedge navigation structure, edges, and adjacency. Output
%   conforms to bct.manifold.topology.schema for HDF5/Zarr serialization.
%
%   The topology structure IS a halfedge structure - all connectivity
%   fields are at the top level for direct navigation. Topology is
%   coordinate-free and depends only on face connectivity F.
%
% Examples:
%   % Compute all topology
%   M = bct.Manifold(V, F);
%   topo = bct.manifold.topology(M);
%   
%   % Access halfedge navigation (dataset structure)
%   h = topo.faceHalfedges.value(1, 1);  % First halfedge of face 1
%   h_next = topo.next.value(h);          % Next halfedge (CCW)
%   h_twin = topo.twin.value(h);          % Twin across edge
%   
%   % Access edges and adjacency
%   E = topo.edgeList.value;              % [nE×2] edge list
%   A = topo.adjacency.value;             % [nV×nV] adjacency matrix
%   
%   % From V, F directly
%   topo = bct.manifold.topology(V, F);
%
% See also: bct.manifold.topology.edges, bct.manifold.topology.adjacency,
%           bct.manifold.topology.schema, bct.manifold.topology.edges,
%           bct.manifold.topology.adjacency
% Parse inputs
if nargin == 1
    % Single argument: Manifold object
    if isa(M, 'bct.Manifold')
        V = M.Vertices;
        F = M.Faces;
        nV = M.numVertices();
    else
        error('bct:manifold:topology:InvalidInput', ...
            'Single argument must be a bct.Manifold object');
    end
elseif nargin == 2
    % Two arguments: V, F
    V = M;  % First arg is V
    F = varargin{1};
    
    % Validate inputs
    if ~isnumeric(F) || size(F, 2) ~= 3
        error('bct:manifold:topology:InvalidFaces', ...
            'Faces must be M×3 numeric array');
    end
    
    % V can be empty for pure topology, or [nV×3] coordinates
    if isempty(V)
        nV = max(F(:));
    elseif isnumeric(V)
        nV = size(V, 1);
    else
        error('bct:manifold:topology:InvalidVertices', ...
            'Vertices must be empty [] or N×3 numeric array');
    end
else
    error('bct:manifold:topology:InvalidNumArgs', ...
        'Expected 1 (Manifold) or 2 (V, F) input arguments');
end

nF = size(F, 1);
nH = 3 * nF;

% Initialize output structure matching schema
topo = struct();

% Group-level attributes (matches s.group.attributes in schema)
topo.attributes = struct();
topo.attributes.schema = 'bct.manifold.topology@1.0.0';
topo.attributes.package = 'bct.manifold.topology';
topo.attributes.numVertices = nV;
topo.attributes.numFaces = nF;
topo.attributes.numHalfedges = nH;
topo.attributes.numEdges = [];
topo.attributes.convention = 'CCW orientation: h12->h23->h31->h12';
topo.attributes.boundary_convention = 'twin=0 for boundary halfedges';
topo.attributes.computed_utc = char(datetime('now', 'TimeZone', 'UTC', ...
    'Format', 'yyyy-MM-dd''T''HH:mm:ss''Z'''));

% Compute halfedge connectivity using modular functions
% Dataset 1, 2: tail and head vertices
[tailVertex_val, headVertex_val] = bct.manifold.topology.vertices(F);
topo.tailVertex.value = tailVertex_val;
topo.tailVertex.attributes = struct(...
    'name', 'tailVertex', ...
    'path', 'topology/tailVertex', ...
    'description', 'Tail vertex index of each halfedge', ...
    'shape', [nH, 1], ...
    'dtype', 'uint32', ...
    'computedBy', 'bct.manifold.topology.vertices');
topo.headVertex.value = headVertex_val;
topo.headVertex.attributes = struct(...
    'name', 'headVertex', ...
    'path', 'topology/headVertex', ...
    'description', 'Head vertex index of each halfedge', ...
    'shape', [nH, 1], ...
    'dtype', 'uint32', ...
    'computedBy', 'bct.manifold.topology.vertices');

% Dataset 3: incident face indices
face_val = bct.manifold.topology.faces(F);
topo.face.value = face_val;
topo.face.attributes = struct(...
    'name', 'face', ...
    'path', 'topology/face', ...
    'description', 'Incident face index for each halfedge', ...
    'shape', [nH, 1], ...
    'dtype', 'uint32', ...
    'computedBy', 'bct.manifold.topology.faces');

% Dataset 4, 5: next/prev circulation
[next_val, prev_val] = bct.manifold.topology.circulation(F);
topo.next.value = next_val;
topo.next.attributes = struct(...
    'name', 'next', ...
    'path', 'topology/next', ...
    'description', 'Next halfedge around face (CCW)', ...
    'shape', [nH, 1], ...
    'dtype', 'uint32', ...
    'computedBy', 'bct.manifold.topology.circulation');
topo.prev.value = prev_val;
topo.prev.attributes = struct(...
    'name', 'prev', ...
    'path', 'topology/prev', ...
    'description', 'Previous halfedge around face (CCW)', ...
    'shape', [nH, 1], ...
    'dtype', 'uint32', ...
    'computedBy', 'bct.manifold.topology.circulation');

% Dataset 6: twin halfedges
twin_val = bct.manifold.topology.twins(topo.tailVertex.value, topo.headVertex.value, nV);
topo.twin.value = twin_val;
topo.twin.attributes = struct(...
    'name', 'twin', ...
    'path', 'topology/twin', ...
    'description', 'Opposite halfedge across undirected edge (0 if boundary)', ...
    'shape', [nH, 1], ...
    'dtype', 'uint32', ...
    'computedBy', 'bct.manifold.topology.twins');

% Dataset 7: edge indices
edge_val = bct.manifold.topology.edgeIndices(F);
topo.edge.value = edge_val;
topo.edge.attributes = struct(...
    'name', 'edge', ...
    'path', 'topology/edge', ...
    'description', 'Undirected edge index for each halfedge', ...
    'shape', [nH, 1], ...
    'dtype', 'uint32', ...
    'computedBy', 'bct.manifold.topology.edgeIndices');

% Dataset 8: boundary flags
isBoundary_val = (topo.twin.value == 0);
topo.isBoundary.value = isBoundary_val;
topo.isBoundary.attributes = struct(...
    'name', 'isBoundary', ...
    'path', 'topology/isBoundary', ...
    'description', 'Boundary flag (true if twin=0)', ...
    'shape', [nH, 1], ...
    'dtype', 'logical', ...
    'computedBy', 'derived');

% Dataset 9: undirected edge list
edgeList_val = bct.manifold.topology.edges(F);
nE = size(edgeList_val, 1);
topo.attributes.numEdges = nE;
topo.edgeList.value = edgeList_val;
topo.edgeList.attributes = struct(...
    'name', 'edgeList', ...
    'path', 'topology/edgeList', ...
    'description', 'Undirected edge list (sorted vertex indices)', ...
    'shape', [nE, 2], ...
    'dtype', 'uint32', ...
    'computedBy', 'bct.manifold.topology.edges');

% Dataset 10: face halfedges
faceHalfedges_val = bct.manifold.topology.faceHalfedges(F);
topo.faceHalfedges.value = faceHalfedges_val;
topo.faceHalfedges.attributes = struct(...
    'name', 'faceHalfedges', ...
    'path', 'topology/faceHalfedges', ...
    'description', 'Halfedge indices per face [h12 h23 h31]', ...
    'shape', [nF, 3], ...
    'dtype', 'uint32', ...
    'computedBy', 'bct.manifold.topology.faceHalfedges');

% Dataset 11, 12: face neighbors
[faceNeighbors_val, neighborEdge_val] = bct.manifold.topology.neighbors(...
    F, topo.faceHalfedges.value, topo.twin.value, topo.face.value);
topo.faceNeighbors.value = faceNeighbors_val;
topo.faceNeighbors.attributes = struct(...
    'name', 'faceNeighbors', ...
    'path', 'topology/faceNeighbors', ...
    'description', 'Adjacent face indices (-1 for boundary)', ...
    'shape', [nF, 3], ...
    'dtype', 'int32', ...
    'computedBy', 'bct.manifold.topology.neighbors');
topo.neighborEdge.value = neighborEdge_val;
topo.neighborEdge.attributes = struct(...
    'name', 'neighborEdge', ...
    'path', 'topology/neighborEdge', ...
    'description', 'Local edge index (1..3) in neighbor face', ...
    'shape', [nF, 3], ...
    'dtype', 'uint8', ...
    'computedBy', 'bct.manifold.topology.neighbors');

% Dataset 13: adjacency matrix
adjacency_val = bct.manifold.topology.adjacency(F, nV);
topo.adjacency.value = adjacency_val;
topo.adjacency.attributes = struct(...
    'name', 'adjacency', ...
    'path', 'topology/adjacency', ...
    'description', 'Sparse binary adjacency matrix', ...
    'shape', [nV, nV], ...
    'dtype', 'logical', ...
    'computedBy', 'bct.manifold.topology.adjacency');
