classdef FEM < handle
    %FEM  Finite Element Method representation of scalar fields on a manifold
    %
    % Defines a Hilbert space of scalar functions and canonical operators
    % generated by the Laplace–Beltrami operator.
    %
    % FEM is the module that defines how scalar fields live, evolve, and are
    % measured on a manifold, with eigenpairs as the atomic spectral units.
    %
    % Design principles (from FEMContract):
    %   - Eigenpairs are atomic units (λ, u) with inner product M
    %   - FEM defines function space, variational operators, evolution
    %   - Uses gptoolbox as authoritative source for FEM computations
    %   - Independent from DEC, Graph, UI
    %
    % Usage:
    %   % From Manifold
    %   M = bct.Manifold(struct('V', V, 'F', F));
    %   fem = bct.FEM(M);
    %   
    %   % Get eigenpairs
    %   E = fem.eigenpairs(100);
    %   
    %   % Evolution operators
    %   signal_t = fem.heat(signal, t, k);
    %   signal_t = fem.wave(signal, t, k);
    %
    % See also: bct.Manifold, bct.Eigenpairs

    properties (SetAccess = private)
        Manifold         % Manifold object (immutable)
        Mass             % [N×N] sparse mass matrix (FEM inner product)
        Stiffness        % [N×N] sparse stiffness/cotangent matrix
        MassType         % 'voronoi' (default), 'barycentric', or 'full'
    end

    properties (Access = private)
        EigenpairCache   % containers.Map: caches computed eigenpairs
    end

    methods
        function obj = FEM(M, options)
            %FEM Constructor for FEM object from Manifold
            %
            % Syntax:
            %   fem = FEM(M)
            %   fem = FEM(M, 'MassType', type)
            %
            % Inputs:
            %   M - bct.Manifold object
            %
            % Optional Parameters:
            %   MassType - 'voronoi' (default), 'barycentric', 'full'
            %
            % Outputs:
            %   fem - FEM object
            
            arguments
                M (1,1) bct.Manifold
                options.MassType (1,1) string {mustBeMember(options.MassType, ["voronoi","barycentric","full"])} = "voronoi"
            end

            obj.Manifold = M;
            obj.MassType = options.MassType;

            % Delegate matrix assembly to bct.fem package (Contract §3.1)
            obj.Mass = bct.fem.assembleMass(M, options.MassType);
            obj.Stiffness = bct.fem.assembleStiffness(M);

            % Initialize eigenpair cache
            obj.EigenpairCache = containers.Map('KeyType','char','ValueType','any');
        end

        % =========================================================
        % SPECTRAL DECOMPOSITION (Contract §4.4.1)
        % =========================================================
        
        function E = eigenpairs(obj, k, options)
            %EIGENPAIRS Compute first k eigenpairs of Laplace-Beltrami operator
            %
            % Syntax:
            %   E = fem.eigenpairs(k)
            %   E = fem.eigenpairs(k, 'Force', true)
            %
            % Inputs:
            %   k - Number of eigenpairs to compute
            %
            % Optional Parameters:
            %   Force - If true, recompute even if cached (default: false)
            %
            % Outputs:
            %   E - bct.Eigenpairs object
            %
            % Guarantees:
            %   - evecs' * M * evecs = I (M-orthonormal)
            %   - K * evecs = M * evecs * diag(evals)
            %   - Eigenvalues in ascending order
            %
            % Note: Uses MATLAB eigs() for sparse generalized eigenvalue problem
            
            arguments
                obj
                k (1,1) double {mustBePositive, mustBeInteger}
                options.Force (1,1) logical = false
            end
            
            % Check cache
            key = sprintf("k=%d", k);
            if ~options.Force && isKey(obj.EigenpairCache, key)
                E = obj.EigenpairCache(key);
                return;
            end

            % Delegate to bct.fem.eigensolve (Contract §3.2)
            E = bct.fem.eigensolve(obj, k);
            
            % Cache result
            obj.EigenpairCache(key) = E;
        end

        % =========================================================
        % PROJECTION OPERATORS (Contract §4.4.2)
        % =========================================================
        
        function c = project(obj, signal, k)
            %PROJECT Project signal onto first k eigenmodes
            %
            % Syntax:
            %   c = fem.project(signal, k)
            %
            % Inputs:
            %   signal - [N×1] signal on vertices
            %   k      - Number of eigenmodes to use
            %
            % Outputs:
            %   c - [k×1] spectral coefficients
            %
            % This is the forward transform in the eigenspace
            
            E = obj.eigenpairs(k);
            c = E.project(signal);
        end

        function signal = reconstruct(obj, coeffs, k)
            %RECONSTRUCT Reconstruct signal from spectral coefficients
            %
            % Syntax:
            %   signal = fem.reconstruct(coeffs, k)
            %
            % Inputs:
            %   coeffs - [k×1] spectral coefficients
            %   k      - Number of eigenmodes (must match size of coeffs)
            %
            % Outputs:
            %   signal - [N×1] reconstructed signal
            %
            % This is the inverse transform from eigenspace
            
            E = obj.eigenpairs(k);
            signal = E.reconstruct(coeffs);
        end

        % =========================================================
        % EVOLUTION OPERATORS (Contract §4.4.3)
        % =========================================================
        
        function out = heat(obj, signal, t, k)
            %HEAT Heat equation evolution operator
            %
            % Syntax:
            %   signal_t = fem.heat(signal, t, k)
            %
            % Inputs:
            %   signal - [N×1] initial condition
            %   t      - Time parameter (diffusion time)
            %   k      - Number of eigenmodes for approximation
            %
            % Outputs:
            %   signal_t - [N×1] evolved signal
            %
            % Evolution: exp(-t*Δ) where Δ is Laplace-Beltrami
            % This is a model of diffusion, not just a low-pass filter
            
            E = obj.eigenpairs(k);
            c = E.project(signal);
            c = exp(-t * E.Values) .* c;
            out = E.reconstruct(c);
        end

        function out = wave(obj, signal, t, k)
            %WAVE Wave equation evolution operator
            %
            % Syntax:
            %   signal_t = fem.wave(signal, t, k)
            %
            % Inputs:
            %   signal - [N×1] initial condition
            %   t      - Time parameter
            %   k      - Number of eigenmodes
            %
            % Outputs:
            %   signal_t - [N×1] evolved signal
            %
            % Evolution: cos(t*sqrt(Δ)) where Δ is Laplace-Beltrami
            % Models wave propagation on the manifold
            
            E = obj.eigenpairs(k);
            c = E.project(signal);
            c = cos(t * sqrt(E.Values)) .* c;
            out = E.reconstruct(c);
        end

        function out = schrodinger(obj, signal, t, k)
            %SCHRODINGER Schrödinger equation evolution operator
            %
            % Syntax:
            %   signal_t = fem.schrodinger(signal, t, k)
            %
            % Inputs:
            %   signal - [N×1] initial condition (can be complex)
            %   t      - Time parameter
            %   k      - Number of eigenmodes
            %
            % Outputs:
            %   signal_t - [N×1] evolved signal (complex)
            %
            % Evolution: exp(-i*t*Δ) where Δ is Laplace-Beltrami
            % Models quantum dynamics on the manifold
            
            E = obj.eigenpairs(k);
            c = E.project(signal);
            c = exp(-1i * t * E.Values) .* c;
            out = E.reconstruct(c);
        end

        % =========================================================
        % SPECTRAL FILTERING (Contract §4.4.4)
        % =========================================================
        
        function out = filter(obj, signal, kernel, k)
            %FILTER Apply spectral filter to signal
            %
            % Syntax:
            %   filtered = fem.filter(signal, kernel, k)
            %
            % Inputs:
            %   signal - [N×1] signal on vertices
            %   kernel - Function handle @(lambda) or [k×1] vector
            %   k      - Number of eigenmodes
            %
            % Outputs:
            %   filtered - [N×1] filtered signal
            %
            % Note: FEM does not define kernels, it applies them
            % See bct.kernel.dictionary() for available kernels
            %
            % Example:
            %   heat_kernel = @(lam) exp(-tau * lam);
            %   filtered = fem.filter(signal, heat_kernel, 100);
            
            E = obj.eigenpairs(k);
            c = E.project(signal);
            
            % Apply kernel (support both function handle and vector)
            if isa(kernel, 'function_handle')
                kernel_vals = kernel(E.Values);
            else
                kernel_vals = kernel;
            end
            
            c = kernel_vals .* c;
            out = E.reconstruct(c);
        end

        % =========================================================
        % ENERGY AND NORMS (Contract §4.4.5)
        % =========================================================
        
        function n = norm(obj, signal)
            %NORM Compute L2 norm of signal with respect to mass matrix
            %
            % Syntax:
            %   n = fem.norm(signal)
            %
            % Inputs:
            %   signal - [N×1] signal on vertices
            %
            % Outputs:
            %   n - Scalar L2 norm
            %
            % Computes: sqrt(signal' * M * signal)
            % Essential for normalization and uncertainty quantification
            
            n = sqrt(signal' * obj.Mass * signal);
        end

        function e = energy(obj, signal)
            %ENERGY Compute Dirichlet energy of signal
            %
            % Syntax:
            %   e = fem.energy(signal)
            %
            % Inputs:
            %   signal - [N×1] signal on vertices
            %
            % Outputs:
            %   e - Scalar energy
            %
            % Computes: signal' * K * signal
            % Measures "roughness" or total variation on manifold
            
            e = signal' * obj.Stiffness * signal;
        end

        function y = applyLaplacian(obj, x)
            %APPLYLAPLACIAN Apply Laplace-Beltrami operator to signal
            %
            % Syntax:
            %   y = fem.applyLaplacian(x)
            %
            % Inputs:
            %   x - [N×1] signal on vertices
            %
            % Outputs:
            %   y - [N×1] result of L*x where L = M^(-1)*K
            %
            % Delegates to bct.fem.applyLaplacian (Contract §3.3)
            % This is numerical application, not spectral computation
            
            y = bct.fem.applyLaplacian(obj.Stiffness, obj.Mass, x);
        end

        % =========================================================
        % GEOMETRIC OPERATIONS (using gptoolbox)
        % =========================================================
        
        function G = gradient(obj)
            %GRADIENT Compute discrete gradient operator
            %
            % Syntax:
            %   G = fem.gradient()
            %
            % Outputs:
            %   G - [#F*dim × #V] sparse gradient operator
            %
            % Uses gptoolbox grad() function
            % Maps vertex values to face-based vector fields
            
            G = grad(obj.Manifold.Vertices, obj.Manifold.Faces);
        end

        function D = divergence(obj)
            %DIVERGENCE Compute discrete divergence operator
            %
            % Syntax:
            %   D = fem.divergence()
            %
            % Outputs:
            %   D - [#V × #F*dim] sparse divergence operator
            %
            % Dual to gradient: D = -G' * A where A is area matrix
            % Maps face vector fields to vertex values
            
            G = obj.gradient();
            dblA = doublearea(obj.Manifold.Vertices, obj.Manifold.Faces);
            A = spdiags(dblA/2, 0, length(dblA), length(dblA));
            dim = size(obj.Manifold.Vertices, 2);
            A_rep = kron(speye(dim), A);
            D = -G' * A_rep;
        end

        function A = areas(obj, options)
            %AREAS Compute areas associated with vertices
            %
            % Syntax:
            %   A = fem.areas()
            %   A = fem.areas('Type', type)
            %
            % Optional Parameters:
            %   Type - 'voronoi' (default), 'barycentric'
            %
            % Outputs:
            %   A - [N×1] areas for each vertex
            %
            % These are the diagonal elements of the mass matrix
            
            arguments
                obj
                options.Type (1,1) string {mustBeMember(options.Type, ["voronoi","barycentric"])} = "voronoi"
            end
            
            M = massmatrix(obj.Manifold.Vertices, obj.Manifold.Faces, char(options.Type));
            A = full(diag(M));
        end

        function L = edgeLengths(obj)
            %EDGELENGTHS Compute edge lengths in mesh
            %
            % Syntax:
            %   L = fem.edgeLengths()
            %
            % Outputs:
            %   L - [#E×1] edge lengths
            %
            % Uses gptoolbox edge_lengths()
            
            L = edge_lengths(obj.Manifold.Vertices, obj.Manifold.Faces);
        end

        function N = vertexNormals(obj)
            %VERTEXNORMALS Compute per-vertex normals
            %
            % Syntax:
            %   N = fem.vertexNormals()
            %
            % Outputs:
            %   N - [#V×3] unit normal vectors at vertices
            %
            % Uses gptoolbox per_vertex_normals()
            
            N = per_vertex_normals(obj.Manifold.Vertices, obj.Manifold.Faces);
        end

        function FN = faceNormals(obj)
            %FACENORMALS Compute per-face normals
            %
            % Syntax:
            %   FN = fem.faceNormals()
            %
            % Outputs:
            %   FN - [#F×3] unit normal vectors for faces
            %
            % Uses gptoolbox normals()
            
            FN = normals(obj.Manifold.Vertices, obj.Manifold.Faces);
        end

        function [H, K] = curvature(obj)
            %CURVATURE Compute mean and Gaussian curvature
            %
            % Syntax:
            %   [H, K] = fem.curvature()
            %
            % Outputs:
            %   H - [#V×1] mean curvature at vertices
            %   K - [#V×1] Gaussian curvature at vertices
            %
            % Uses gptoolbox discrete_curvatures()
            
            [H, K, ~, ~] = discrete_curvatures(obj.Manifold.Vertices, obj.Manifold.Faces);
        end

        % =========================================================
        % UTILITY METHODS
        % =========================================================
        
        function clearCache(obj)
            %CLEARCACHE Clear eigenpair cache
            %
            % Syntax:
            %   fem.clearCache()
            %
            % Use when manifold geometry changes (though FEM is immutable)
            
            obj.EigenpairCache = containers.Map('KeyType','char','ValueType','any');
        end

        function info = getInfo(obj)
            %GETINFO Get information about FEM discretization
            %
            % Syntax:
            %   info = fem.getInfo()
            %
            % Outputs:
            %   info - Struct with fields:
            %          .NumVertices
            %          .NumFaces
            %          .MassType
            %          .CachedEigenvalues (array of k values)
            
            info.NumVertices = size(obj.Manifold.Vertices, 1);
            info.NumFaces = size(obj.Manifold.Faces, 1);
            info.MassType = obj.MassType;
            info.CachedEigenvalues = cell2mat(keys(obj.EigenpairCache));
        end
    end
end
